hyperledger-bevel/bevel

docs/source/faq.md

Update repo links

---

platforms/hyperledger-indy/configuration/deploy-network.yaml
platforms/hyperledger-indy/configuration/roles/create/namespace/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/k8_component/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/k8_component/templates/namespace_component.tpl
platforms/hyperledger-indy/configuration/roles/k8_component/vars/main.yaml

Added namespace role for Hyperledger-Indy

---

platforms/hyperledger-indy/configuration/roles/create/helm_component/templates/crypto-generate.tpl

Add docker repository url from network.yaml (#66)

---

platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml

Signed-off-by: Juraj Durech <juraj.durech@accenture.com>

Changed trustees and endorsers to a list

---

platforms/r3-corda/configuration/roles/create/certificates/doorman/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/certificates/nms/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/certificates/notary/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/k8_component/templates/create_doorman.tpl
platforms/r3-corda/configuration/roles/create/k8_component/templates/network_map.tpl
platforms/r3-corda/configuration/roles/setup/doorman/tasks/main.yml
platforms/r3-corda/configuration/roles/setup/nms/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/node/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/notary/tasks/main.yaml

Signed-off-by: srinivasan.sankaran <srinivasan.sankaran@accenture.com>

Code fix for hardcoded value corda

---

platforms/hyperledger-indy/images/indy-key-mgmt/src/identity_crypto_generator.py

Signed-off-by: Juraj Durech <juraj.durech@accenture.com>

Fixed public key format

---

platforms/hyperledger-indy/charts/indy-node/templates/statefulset.yaml

Create directory structure for indy-node init container (Bug #94)

---

platforms/hyperledger-indy/charts/indy-domain-genesis/Chart.yaml
platforms/hyperledger-indy/charts/indy-domain-genesis/templates/configmap.yaml
platforms/hyperledger-indy/charts/indy-domain-genesis/values.yaml
platforms/hyperledger-indy/charts/indy-node/templates/configmap.yaml
platforms/hyperledger-indy/charts/indy-node/templates/statefulset.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/node/templates/node.tpl

indy-domain-genesis-config-map-helm-chart 21

---

platforms/hyperledger-indy/charts/indy-pool-genesis/Chart.yaml
platforms/hyperledger-indy/charts/indy-pool-genesis/templates/configmap.yaml
platforms/hyperledger-indy/charts/indy-pool-genesis/values.yaml

Signed-off-by: Juraj Durech <juraj.durech@accenture.com>

Added pool genesis config map helm chart

---

platforms/hyperledger-indy/images/indy-node/Dockerfile
platforms/hyperledger-indy/images/indy-node/start-indy-node.sh

Signed-off-by: Juraj Durech <juraj.durech@accenture.com>

Added indy-node Docker image

---

examples/supplychain-app/charts/frontend/templates/deployment.yaml
examples/supplychain-app/charts/frontend/values.yaml
examples/supplychain-app/configuration/deploy-supplychain-app.yaml
examples/supplychain-app/configuration/roles/create/frontend/tasks/main.yaml
examples/supplychain-app/configuration/roles/helm_component/templates/frontend.tpl

Adding google api key as k8 secret

---

platforms/hyperledger-indy/charts/indy-node/templates/statefulset.yaml

fixed bug with checking if vault is up

---

examples/supplychain-app/charts/expressapp/templates/service.yaml
platforms/hyperledger-fabric/charts/ca/templates/service.yaml

Fixed nullpointer exception error

---

platforms/hyperledger-indy/configuration/deploy-network.yaml
platforms/hyperledger-indy/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/setup/vault_kubernetes/templates/admin-rw.tpl

Indy: Create the admin K8S auth Ansible role #80

---

docs/source/operations/corda_networkyaml.md
platforms/hyperledger-fabric/configuration/roles/create/chaincode/upgrade/tasks/valuefile.yaml
platforms/r3-corda/configuration/deploy-network.yaml
platforms/r3-corda/configuration/deploy-nodes.yaml
platforms/r3-corda/configuration/roles/check/k8_component/tasks/main.yaml
platforms/r3-corda/configuration/roles/check/node_component/tasks/main.yaml
platforms/r3-corda/configuration/samples/network-cordav2.yaml
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml
platforms/shared/configuration/roles/setup/flux/tasks/main.yaml

Fixed retry count

---

platforms/hyperledger-indy/charts/indy-key-mgmt/templates/job.yaml
platforms/hyperledger-indy/charts/indy-key-mgmt/values.yaml
platforms/hyperledger-indy/configuration/deploy-network.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/crypto/templates/crypto-generate.tpl
platforms/hyperledger-indy/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/setup/vault_kubernetes/templates/admin-rw.tpl

creating the pull request again to receive comments

---

platforms/hyperledger-indy/charts/indy-key-mgmt/templates/job.yaml

Change a way for test received token (#150)

---

docs/source/operations/corda_networkyaml.md
docs/source/releasenotes.md

Added release notes and some changes in corda configuration file

Release notes v0.3.0.0

---

platforms/hyperledger-indy/charts/indy-ledger-txn/Chart.yaml
platforms/hyperledger-indy/charts/indy-ledger-txn/README.md
platforms/hyperledger-indy/charts/indy-ledger-txn/templates/job.yaml
platforms/hyperledger-indy/charts/indy-ledger-txn/values.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/ledger_txn/templates/ledger-txn.tpl

Signed-off-by: Lal <himanshu.a.lal@accenture.com>

Indy Ledger Txn Job modified for init container and Helm Release Updated

---

platforms/hyperledger-indy/charts/indy-auth-job/templates/job.yaml
platforms/hyperledger-indy/charts/indy-auth-job/values.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/auth_job/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/auth_job/templates/auth_job.tpl

added content of job that will create the auth for org #76

---

platforms/hyperledger-fabric/charts/join_channel/templates/join_channel.yaml

Added patch fix for join channel

---

platforms/quorum/charts/raft_constellation/templates/configmap.yaml
platforms/quorum/charts/raft_constellation/templates/deployment.yaml
platforms/quorum/charts/raft_constellation/values.yaml
platforms/quorum/charts/raft_tessera/Chart.yaml
platforms/quorum/charts/raft_tessera/templates/_helpers.tpl
platforms/quorum/charts/raft_tessera/templates/configmap.yaml
platforms/quorum/charts/raft_tessera/templates/deployment.yaml
platforms/quorum/charts/raft_tessera/templates/ingress.yaml
platforms/quorum/charts/raft_tessera/templates/service.yaml
platforms/quorum/charts/raft_tessera/values.yaml

Update existing constellation charts as well add new chart for tessera

Add helmchart for Tessera with RAFT

---

platforms/hyperledger-indy/configuration/roles/check/auth_job/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/check/crypto/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/check/k8_component/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml

retry_count for Indy checks is taken from network.yaml file

---

platforms/hyperledger-indy/configuration/README.md

Add readme file for configuration folder of hyperledger indy (#131)

---

README.md

Added rocket chat badge

---

platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml

added comments for ssample network indy file

---

README.md

The current CII badge is at 97% 

CII badge added

---

README.md
docs/source/operations/fabric_networkyaml.md
docs/source/operations/upgrading_chaincode.md
platforms/hyperledger-fabric/configuration/roles/create/channels/tasks/peercheck.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrg.tpl
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml

Non-anchor peer fix

---

platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml

added context to indy sample network yaml

---

platforms/quorum/configuration/deploy_network.yaml
platforms/quorum/configuration/roles/create/generate_crypto_raft/Readme.md
platforms/quorum/configuration/roles/create/generate_crypto_raft/tasks/main.yaml
platforms/quorum/configuration/roles/setup/bootnode/Readme.md
platforms/quorum/configuration/roles/setup/bootnode/tasks/main.yaml
platforms/quorum/configuration/roles/setup/bootnode/vars/main.yaml
platforms/quorum/configuration/roles/setup/geth/Readme.md
platforms/quorum/configuration/roles/setup/geth/tasks/main.yaml
platforms/quorum/configuration/roles/setup/geth/vars/main.yaml

Quorum crypto generation for RAFT consensus

---

docs/source/operations/configure_prerequisites.md
docs/source/operations/fabric_networkyaml.md
docs/source/prerequisites.md
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml

Added more details to docs

---

README.md

updated docker run command in main readme

---

platforms/hyperledger-fabric/configuration/roles/create/new_organization/create_block/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/new_organization/create_block/tasks/create_json.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/create_block/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/create_block/templates/organisation_script.tpl
platforms/hyperledger-fabric/configuration/roles/setup/config_block/fetch/tasks/nested_fetch_role.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/sign_and_update/tasks/main.yaml

Signed-off-by: Kumar <lakshya.kumar@accenture.com>
#308

308- adding anchor peer information to the channel

---

platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/orderer.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/common.yaml

Signed-off-by: Kumar <lakshya.kumar@accenture.com>
Adding the patch for permissions required for msp

permission patch

---

platforms/quorum/configuration/deploy-network.yaml
platforms/quorum/configuration/roles/create/crypto/tessera/Readme.md
platforms/quorum/configuration/roles/create/crypto/tessera/tasks/main.yaml
platforms/quorum/configuration/roles/create/crypto/tessera/tasks/nested_main.yaml

Crypto for tessera TM #182

---

platforms/hyperledger-fabric/charts/invoke_chaincode/Chart.yaml
platforms/hyperledger-fabric/charts/invoke_chaincode/templates/_helpers.tpl
platforms/hyperledger-fabric/charts/invoke_chaincode/templates/invoke_chaincode.yaml
platforms/hyperledger-fabric/charts/invoke_chaincode/values.yaml
platforms/hyperledger-fabric/configuration/chaincode-install-instantiate.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels_join/tasks/check.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels_join/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/invoke_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/vars/main.yaml
platforms/shared/configuration/add-new-organization.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml
platforms/shared/configuration/site.yaml

#316 install and invoke chaincode for newly added organization

Invoke chaincode

---

platforms/quorum/configuration/deploy-network.yaml
platforms/quorum/configuration/roles/create/crypto/ibft/Readme.md
platforms/quorum/configuration/roles/create/crypto/ibft/meta/main.yaml
platforms/quorum/configuration/roles/create/crypto/ibft/tasks/main.yaml
platforms/quorum/configuration/roles/create/crypto/ibft/tasks/nested_main.yaml
platforms/quorum/configuration/roles/create/genesis_nodekey/Readme.md
platforms/quorum/configuration/roles/create/genesis_nodekey/meta/main.yaml
platforms/quorum/configuration/roles/create/genesis_nodekey/tasks/main.yaml
platforms/quorum/configuration/roles/create/genesis_nodekey/tasks/nested_nodekey_vault_check.yaml
platforms/quorum/configuration/roles/create/genesis_nodekey/tasks/nodekey_vault_check.yaml
platforms/quorum/configuration/roles/create/genesis_nodekey/tasks/validator_node_data.yaml
platforms/quorum/configuration/roles/setup/istanbul/Readme.md
platforms/quorum/configuration/roles/setup/istanbul/tasks/main.yaml
platforms/quorum/configuration/roles/setup/istanbul/vars/main.yaml

Crypto IBFT

---

platforms/quorum/configuration/deploy-network.yaml
platforms/quorum/configuration/roles/create/certificates/ambassador/tasks/main.yaml
platforms/quorum/configuration/roles/create/crypto/constellation/Readme.md
platforms/quorum/configuration/roles/create/crypto/constellation/meta/main.yaml
platforms/quorum/configuration/roles/create/crypto/constellation/tasks/main.yaml
platforms/quorum/configuration/roles/create/crypto/constellation/tasks/nested_main.yaml
platforms/quorum/configuration/roles/setup/constellation-node/Readme.md
platforms/quorum/configuration/roles/setup/constellation-node/tasks/main.yaml
platforms/quorum/configuration/roles/setup/constellation-node/vars/main.yaml

Fix for Issue #181

---

examples/supplychain-app/corda/cordApps_springBoot/build.gradle
examples/supplychain-app/quorum/smartContracts/productContract.sol

Sprint 8, issue # 277 create new product

Product smart contract

---

platforms/hyperledger-indy/configuration/deploy-network.yaml

Currently breaks deploy script for me.

Fix indentation of indy network.yaml validation

---

platforms/hyperledger-fabric/configuration/roles/create/chaincode/upgrade/tasks/valuefile.yaml

Changed upgrade-chaincode value file name

---

platforms/quorum/configuration/deploy-network.yaml
platforms/quorum/configuration/roles/create/constellation/Readme.md
platforms/quorum/configuration/roles/create/constellation/tasks/enode_data.yaml
platforms/quorum/configuration/roles/create/constellation/tasks/main.yaml
platforms/quorum/configuration/roles/create/constellation/tasks/nested_enode_data.yaml
platforms/quorum/configuration/roles/helm_component/tasks/main.yaml
platforms/quorum/configuration/roles/helm_component/templates/constellation.tpl
platforms/quorum/configuration/roles/helm_component/vars/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

#Fix for 188

---

docs/source/developer/fabric-ansible.md
platforms/hyperledger-fabric/configuration/roles/create/crypto/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/Readme.md

#322 removed the dos2unix utility.
This removes the outdated references in the documentation and Readmes

Remove outdated dos2unix references

---

docs/source/architectureref/certificates_path_list_indy.md
docs/source/architectureref/hyperledger-indy.md
docs/source/developer/indy-helmcharts.md

Fixed indy readthedocs md formatting issue

---

docs/source/architectureref/certificates_path_list_indy.md
docs/source/architectureref/hyperledger-indy.md
docs/source/developer/indy-helmcharts.md

Fixed md formatting for indy readthedocs

---

examples/supplychain-app/quorum/smartContracts/contracts/ContainerContract.sol
examples/supplychain-app/quorum/smartContracts/contracts/ProductContract.sol

package trackables for both container and product. story #304

Package trackables

---

examples/supplychain-app/quorum/express_nodeJS/controllers/container.js
examples/supplychain-app/quorum/smartContracts/contracts/ContainerContract.sol

Quorum update container custodian

---

examples/supplychain-app/quorum/express_nodeJS/controllers/product.js
examples/supplychain-app/quorum/smartContracts/contracts/ProductContract.sol

get single product
story #300 and #301

Get single product contract

---

platforms/hyperledger-fabric/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/quorum/configuration/reset-network.yaml
platforms/quorum/configuration/roles/delete/flux_releases/Readme.md
platforms/quorum/configuration/roles/delete/flux_releases/meta/main.yaml
platforms/quorum/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/quorum/configuration/roles/delete/gitops_files/Readme.md
platforms/quorum/configuration/roles/delete/gitops_files/tasks/main.yaml
platforms/quorum/configuration/roles/delete/vault_secrets/Readme.md
platforms/quorum/configuration/roles/delete/vault_secrets/meta/main.yaml
platforms/quorum/configuration/roles/delete/vault_secrets/tasks/main.yaml

Reset network playbook for Quorum

---

docs/source/contributing.md

Signed-off-by: Pri-vats <priyanka.a.vats@accenture.com>

Updated contributing.md file

---

examples/supplychain-app/quorum/express_nodeJS/controllers/general.js
examples/supplychain-app/quorum/smartContracts/contracts/General.sol

Story #281 
Returns ownership status

Quorum - scan

---

platforms/quorum/configuration/deploy-network.yaml
platforms/quorum/configuration/roles/create/constellation/meta/main.yaml
platforms/quorum/configuration/roles/create/constellation/tasks/nested_enode_data.yaml
platforms/quorum/configuration/roles/create/tessera/meta/main.yaml
platforms/quorum/configuration/roles/create/tessera/tasks/nested_enode_data.yaml

Fixed code

---

examples/supplychain-app/corda/cordApps_springBoot/build.gradle
examples/supplychain-app/corda/cordApps_springBoot/gradle.properties

Signed-off-by: suvajit-sarkar <baf@accenture.com>

Explore: Gradle publish to Nexus repository

---

automation/Jenkinsfile
docs/source/architectureref/corda.md
examples/supplychain-app/corda/cordApps_springBoot/cordapp-contracts-states/build.gradle
examples/supplychain-app/corda/cordApps_springBoot/cordapp-supply-chain/build.gradle
platforms/hyperledger-fabric/configuration/samples/network-minikube.yaml

Signed-off-by: Roy, Sownak <sownak.roy@accenture.com>

Add minikube sample

---

platforms/hyperledger-fabric/charts/zkkafka/templates/deployment.yaml

Kafka cluster doesnt retain data on restart - fix

---

platforms/hyperledger-indy/images/indy-cli/indy-ledger.sh

Indy check correct endorser creation

---

docs/source/operations/adding_new_org_corda.md
platforms/r3-corda/configuration/roles/create/storageclass/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/doorman/tasks/main.yml

Bug fixing and adding env in docs

---

examples/supplychain-app/tests/SupplyChainTest.postman_collection.json

Signed-off-by: Roy, Sownak <sownak.roy@accenture.com>

Updated postman test suite

---

docs/source/operations/adding_cordapps.md

Updating the add cordapps jar readthedocs

---

platforms/hyperledger-fabric/configuration/roles/create/anchorpeer/tasks/nested_anchorpeer.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-server/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/instantiate/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels/tasks/orderercheck.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels/tasks/peercheck.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels_join/tasks/check.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels_join/tasks/nested_channel_join.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/orderer.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/orderercheck.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/namespace_vaultauth/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/storageclass/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/shared/configuration/roles/check/helm_component/Readme.md
platforms/shared/configuration/roles/check/helm_component/tasks/main.yaml
platforms/shared/configuration/roles/check/k8_component/Readme.md
platforms/shared/configuration/roles/check/k8_component/tasks/main.yaml
platforms/shared/configuration/roles/check/setup/Readme.md
platforms/shared/configuration/roles/check/setup/tasks/main.yaml

412 reuse component

---

examples/supplychain-app/quorum/smartContracts/package-lock.json
examples/supplychain-app/quorum/smartContracts/truffle-config.js
platforms/quorum/charts/node_constellation/templates/deployment.yaml
platforms/quorum/configuration/roles/helm_component/templates/constellation.tpl

quorum updation

---

examples/supplychain-app/fabric/chaincode_rest_server/README.md
platforms/hyperledger-fabric/charts/instantiate_chaincode/templates/instantiate_chaincode.yaml

Fixed chaincode error

---

platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/hyperledger-fabric/configuration/samples/network-minikube.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube.yaml
platforms/quorum/configuration/samples/network-minikube.yaml
platforms/quorum/configuration/samples/network-quorum.yaml
platforms/r3-corda/configuration/roles/create/k8_component/templates/create_doorman.tpl
platforms/r3-corda/configuration/roles/create/k8_component/templates/network_map.tpl
platforms/r3-corda/configuration/samples/network-cordav2.yaml
platforms/r3-corda/configuration/samples/network-minikube.yaml

Fixing some issues with corda minikube configuration

---

platforms/quorum/charts/node_tessera/templates/configmap.yaml
platforms/quorum/charts/node_tessera/templates/deployment.yaml
platforms/quorum/configuration/roles/helm_component/templates/tessera.tpl

Quourm db password from vault

---

docs/source/glossary.md

glossary 472

---

platforms/quorum/charts/node_tessera/templates/deployment.yaml

tessera version check fix

---

platforms/hyperledger-indy/images/indy-node/README.md
platforms/shared/scripts/pre_setup_mac.sh

Create script for install prerequisites on mac (525)

---

docs/source/commandsref.md

Signed-off-by: Lal <himanshu.a.lal@accenture.com>
#473

Command reference Doc Updated for Indy and Quorum

---

examples/supplychain-app/quorum/smartContracts/README.md
examples/supplychain-app/quorum/smartContracts/compile.js
examples/supplychain-app/quorum/smartContracts/deploy.js
examples/supplychain-app/quorum/smartContracts/package-lock.json
examples/supplychain-app/quorum/smartContracts/package.json

576  deploying smart contract

---

platforms/shared/scripts/pre_setup_win.bat

Signed-off-by: jagpreetsinghsasan <jagpreet.singh.sasan>
#575

Enchanced developer pre-requisite script for Windows

---

platforms/r3-corda/charts/node/templates/deployment.yaml
platforms/r3-corda/configuration/roles/create/node_component/templates/node.tpl
platforms/r3-corda/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/node/tasks/main.yaml

Adding check for node registration job

---

examples/supplychain-app/configuration/roles/deploy/quorum/smartContract/tasks/nested_deploy.yaml
examples/supplychain-app/configuration/samples/network-quorumv2.yaml
examples/supplychain-app/quorum/smartContracts/README.md
examples/supplychain-app/quorum/smartContracts/compile.js
examples/supplychain-app/quorum/smartContracts/deploy.js
examples/supplychain-app/quorum/smartContracts/package-lock.json

645 adding privateFor support

---

platforms/r3-corda/charts/notary/templates/deployment.yaml
platforms/r3-corda/configuration/roles/setup/notary/tasks/main.yaml

Adding notary registration check in chart

---

platforms/hyperledger-fabric/configuration/add-organization.yaml
platforms/hyperledger-fabric/configuration/chaincode-install-instantiate.yaml
platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrderer.tpl
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrg.tpl

adding policies for fabric version below 2.0

---

platforms/r3-corda/configuration/deploy-network.yaml
platforms/r3-corda/configuration/molecule/default/converge.yml
platforms/r3-corda/configuration/molecule/default/verify.yml
platforms/r3-corda/configuration/roles/create/storageclass/tasks/main.yaml

Fixed storageclass name and added variable in network.yaml

---

.github/pull_request_template.md

create a pull request template

---

docs/source/operationalguide.rst
docs/source/operations/adding_new_storageclass.md

**Changelog**
- Add operations guide to add new storageclass
@lakshyakumar 
#668

Operations guide to add new storageclass

---

examples/identity-app/charts/faber/Chart.yaml
examples/identity-app/charts/faber/templates/service.yaml
examples/identity-app/charts/faber/templates/statefulset.yaml
examples/identity-app/charts/faber/values.yaml

**Changelog**
- Add helm chart for agent Faber (university) of Aries Demo
@sownak 
#175 
Commit message
-------------
Add/fix/update issue_description

Create a Helm chart for faber university demo (#175)

---

.github/pull_request_template.md

**Changelog**
- Fix pull request template
@deepakkumardbd

Fix Pull request template

---

platforms/hyperledger-besu/configuration/samples/network-besu.yaml

**Changelog**
- Add besu config file
#452

add configuration file for besu

---

platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/openssl.conf
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/Readme.md
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/vars/main.yaml
platforms/hyperledger-besu/configuration/roles/setup/get_crypto/Readme.md
platforms/hyperledger-besu/configuration/roles/setup/get_crypto/tasks/main.yaml

**Changelog**
- Add ansible role for ambassador certificates generation in besu
@deepakkumardbd 
#516

add ambassador certificates

---

examples/identity-app/README.md
examples/identity-app/images/agents/README.md
platforms/hyperledger-indy/configuration/samples/network-indyv3-aries.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube-aries.yaml

**Changelog**
- Update documentation to run the Aries Demo
- Update sample network.yaml files for Aries Demo
@sownak 
#670

[aries] Update readme file to run the demo.

---

examples/identity-app/README.md
examples/identity-app/images/agents/README.md

**Changelog**
- Fix typos in documentation of Identity App
@sownak

[aries] Fix typos in documentation of Identity App.

---

platforms/r3-corda/configuration/molecule/default/cleanup.yml
platforms/r3-corda/configuration/molecule/default/converge.yml
platforms/r3-corda/configuration/molecule/default/molecule.yml
platforms/r3-corda/configuration/molecule/doorman/cleanup.yml
platforms/r3-corda/configuration/molecule/doorman/converge.yml
platforms/r3-corda/configuration/molecule/doorman/molecule.yml
platforms/r3-corda/configuration/molecule/doorman/prepare.yml
platforms/r3-corda/configuration/molecule/doorman/verify.yml
platforms/r3-corda/configuration/roles/create/certificates/ambassador/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/certificates/doorman/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/imagepullsecret/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/k8_component/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/doorman/tasks/main.yml
platforms/r3-corda/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/shared/configuration/roles/check/setup/tasks/main.yaml

**Changelog**
- Add molecule scenario for doorman
#624

Adding molecule test for doorman

---

platforms/quorum/configuration/deploy-network.yaml
platforms/quorum/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

**Changelog**
- Fix vault policy check in quorum
#749

[Quorum] Fix Vault Policies Bug in Quorum

---

platforms/hyperledger-besu/README.md
platforms/hyperledger-besu/charts/README.md
platforms/hyperledger-besu/configuration/README.md
platforms/hyperledger-besu/releases/README.md

**Changelog**
- Add besu folder structure
NA
#451

[Besu] Adding besu folder structure and readme

---

README.md

Signed-off-by: Tracy Kuhrt <tracy.a.kuhrt@accenture.com>
**Changelog**
- docs: Add links for Hyperledger Indy and Quorum to README 
N/A
N/A

docs: Add links for Indy and Quorum

---

docs/source/faq.md
docs/source/operations/corda_networkyaml.md

**Changelog**
- Update `readthedocs`
NA
NA

[ci skip] added latest platform version, updated faq section

---

platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/add_to_vault.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/orion/Readme.md
platforms/hyperledger-besu/configuration/roles/create/crypto/orion/tasks/check_vault.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/orion/tasks/generate_nodekey.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/orion/tasks/main.yaml

**Changelog**
- Add ansible role for generation of crypto material for orion transaction manager
#518

[Besu] Add orion crypto

---

platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/hyperledger-besu/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

**Changelog**
- Fix besu undefined variables and alignment issues
#774

fix besu bug

---

platforms/hyperledger-fabric/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/quorum/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/shared/configuration/roles/check/setup/tasks/main.yaml

**Changelog**
-Fix vault_auth task
@lakshyakumar 
#750

[shared] Vault-auth fix

---

platforms/hyperledger-besu/configuration/reset-network.yaml
platforms/hyperledger-besu/configuration/roles/delete/flux_releases/Readme.md
platforms/hyperledger-besu/configuration/roles/delete/flux_releases/meta/main.yaml
platforms/hyperledger-besu/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/delete/gitops_files/Readme.md
platforms/hyperledger-besu/configuration/roles/delete/gitops_files/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/delete/vault_secrets/Readme.md
platforms/hyperledger-besu/configuration/roles/delete/vault_secrets/meta/main.yaml
platforms/hyperledger-besu/configuration/roles/delete/vault_secrets/tasks/main.yaml

**Changelog**
- Add reset network playbook for besu
#798

[ Besu ] Add reset network for besu

---

platforms/corda-ent/charts/generate-pki/files/pki.conf
platforms/corda-ent/charts/generate-pki/templates/job.yaml
platforms/corda-ent/charts/generate-pki/values.yaml
platforms/corda-ent/charts/signer/files/signer.conf
platforms/corda-ent/charts/signer/templates/deployment.yaml

**Changelog**
- Update cert to vault path
@jagpreetsinghsasan @lakshyakumar 
#785

Adding cert to vaul path

---

platforms/r3-corda/configuration/samples/network-cordav2.yaml
platforms/r3-corda/configuration/samples/network-minikube.yaml

**Changelog**
- Fix db_sub in samples yaml
@lakshyakumar 
#issue_number

Adding db_sub in samples yaml

---

platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/Readme.md
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/enode_data.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/nested_enode_data.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/nested_nodelist.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/nodelist.yaml
platforms/hyperledger-besu/configuration/roles/helm_component/Readme.md
platforms/hyperledger-besu/configuration/roles/helm_component/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/helm_component/templates/helm_component.tpl
platforms/hyperledger-besu/configuration/roles/helm_component/templates/node_orion.tpl
platforms/hyperledger-besu/configuration/roles/helm_component/vars/main.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml
platforms/shared/configuration/site.yaml

**Changelog**
- Add ansible code for deploying orion chart
#519

[ Besu ] add ansible code for deploying orion chart

---

platforms/corda-ent/configuration/roles/setup/signer/tasks/main.yml

**Changelog**
- Update variable names
#802

[ci skip] change variable name for setup signer role

---

platforms/corda-ent/configuration/samples/network-cordaent.yaml

**Changelog**
- Fix network.yaml for corda enterprise

[ Ent-corda ] Fix network.yaml

---

platforms/corda-ent/charts/idman/templates/service.yaml
platforms/corda-ent/charts/signer/templates/deployment.yaml
platforms/corda-ent/charts/signer/templates/service.yaml
platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/openssl.conf
platforms/corda-ent/configuration/roles/create/certificates/ambassador/idman/Readme.md
platforms/corda-ent/configuration/roles/create/certificates/ambassador/idman/tasks/main.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/idman.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/get_crypto/Readme.md
platforms/corda-ent/configuration/roles/setup/get_crypto/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/idman/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/pki-generator/tasks/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add ambassador crypto and annotations for Idman
- Add role to create value file for Idman
#800

[ Ent-corda ] Add ambassador annotations and value file for Idman

---

platforms/corda-ent/charts/nmap/templates/deployment.yaml
platforms/corda-ent/charts/nmap/templates/service.yaml
platforms/corda-ent/charts/notary-initial-registration/files/create-network-parameters-file.sh
platforms/corda-ent/charts/notary-initial-registration/templates/job.yaml

**Changelog**
- Fix getting `nodeInfoFile` & `network-parameters-initial.conf` from Vault
- Update `notary-initial-registration` to have static `nodeInfoFile` name
#778

[ Ent-corda ] Adding nmap service

---

platforms/hyperledger-besu/charts/node_orion/templates/configmap.yaml
platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_orion/values.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/orion/tasks/generate_nodekey.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/orion/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/nested_nodelist.yaml
platforms/hyperledger-besu/configuration/roles/helm_component/templates/node_orion.tpl
platforms/hyperledger-besu/configuration/samples/network-besu.yaml
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

**Changelog**
- Add TLS option for besu
#828

[Besu] add tls option to orion transaction manager

---

examples/supplychain-app/tests/README.md

Signed-off-by: sownak sownak.roy@accenture.com
**Changelog**
- Add
- Fix
- Update
#issue_number

[ci skip] Fix readme

---

platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/roles/create/certificates/ambassador/nmap/Readme.md
platforms/corda-ent/configuration/roles/create/certificates/ambassador/nmap/tasks/main.yaml

Signed-off-by: jagpreetsinghsasan <baf@accenture.com>
**Changelog**
- Add ambassador certificate creation role/tasks
#809

[ Ent-corda ] Added ambassador role/tasks for nmap

---

platforms/corda-ent/charts/notary-initial-registration/templates/configmap.yaml
platforms/corda-ent/charts/notary-initial-registration/templates/job.yaml
platforms/corda-ent/charts/notary/Chart.yaml
platforms/corda-ent/charts/notary/files/notary.conf
platforms/corda-ent/charts/notary/files/run.sh
platforms/corda-ent/charts/notary/templates/_helpers.tpl
platforms/corda-ent/charts/notary/templates/configmap.yaml
platforms/corda-ent/charts/notary/templates/deployment.yaml
platforms/corda-ent/charts/notary/templates/pvc.yaml
platforms/corda-ent/charts/notary/templates/service.yaml
platforms/corda-ent/charts/notary/values.yaml

**Changelog**
- Add notary charts
@jagpreetsinghsasan @suvajit-sarkar 
#779

[ Ent-Corda ] Adding notary charts

---

platforms/corda-ent/charts/idman/templates/service.yaml
platforms/corda-ent/charts/idman/values.yaml
platforms/corda-ent/charts/nmap/files/run.sh
platforms/corda-ent/charts/nmap/templates/deployment.yaml
platforms/corda-ent/charts/nmap/templates/service.yaml
platforms/corda-ent/charts/nmap/values.yaml
platforms/corda-ent/charts/signer/values.yaml
platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/roles/helm_component/tasks/main.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/nmap.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/idman/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/nmap/Readme.md
platforms/corda-ent/configuration/roles/setup/nmap/tasks/main.yml
platforms/corda-ent/configuration/samples/network-cordaent.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add nmap helm release creation
- Fix cenm service value files variables and comments
- Update sample network yaml
**to be reviewed by**
@jagpreetsinghsasan  @deepakkumardbd 
#801

[ Ent-Corda ] Ansible role to create networkmap helm release file 

---

platforms/hyperledger-besu/charts/node_orion/values.yaml
platforms/hyperledger-besu/charts/node_validator/Chart.yaml
platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/Readme.md
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/add_to_vault.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/check_vault.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/node_data.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/validator_node_data.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/orion/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/nested_nodelist.yaml
platforms/hyperledger-besu/configuration/roles/create/validator/Readme.md
platforms/hyperledger-besu/configuration/roles/create/validator/tasks/enode_data.yaml
platforms/hyperledger-besu/configuration/roles/create/validator/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/validator/tasks/nested_enode_data.yaml
platforms/hyperledger-besu/configuration/roles/helm_component/templates/validator.tpl
platforms/hyperledger-besu/configuration/roles/helm_component/vars/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add ansible code to deploy the validator nodes using deploy-network.yaml
#857

[ Besu ] Add ansible code to deploy validator peers using deploy-network.yaml

---

platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/roles/create/certificates/ambassador/notary/Readme.md
platforms/corda-ent/configuration/roles/create/certificates/ambassador/notary/tasks/main.yaml

**Changelog**
- Add ambassador credentials for notary
@deepakkumardbd 
#810

[ Ent-corda ] Notary ambassador credentials

---

docs/source/architectureref/certificates_path_list_corda_ent.md
platforms/corda-ent/charts/generate-pki/values.yaml
platforms/corda-ent/charts/idman/values.yaml
platforms/corda-ent/charts/notary-initial-registration/Chart.yaml
platforms/corda-ent/charts/notary-initial-registration/files/notary.conf
platforms/corda-ent/charts/notary-initial-registration/values.yaml
platforms/corda-ent/charts/signer/values.yaml
platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/roles/create/certificates/ambassador/idman/tasks/main.yaml
platforms/corda-ent/configuration/roles/create/certificates/ambassador/nmap/tasks/main.yaml
platforms/corda-ent/configuration/roles/create/certificates/ambassador/notary/tasks/main.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/notary_initial_registration.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/idman/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/nmap/tasks/main.yml
platforms/corda-ent/configuration/roles/setup/notary-initial-registration/Readme.md
platforms/corda-ent/configuration/roles/setup/notary-initial-registration/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/corda-ent/configuration/samples/network-cordaent.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add ansible role for notary initial registration value file creation
** to be Reviewed by**
@jagpreetsinghsasan  @deepakkumardbd 
#855

[ Ent-corda ] Ansible role to create helm release for notary registration

---

platforms/corda-ent/charts/h2/Chart.yaml
platforms/corda-ent/charts/h2/templates/deployment.yaml
platforms/corda-ent/charts/h2/templates/pvc.yaml
platforms/corda-ent/charts/h2/templates/service.yaml
platforms/corda-ent/charts/h2/values.yaml
platforms/corda-ent/charts/notary/files/run.sh
platforms/corda-ent/charts/notary/templates/deployment.yaml
platforms/corda-ent/charts/notary/templates/pvc.yaml
platforms/corda-ent/charts/notary/values.yaml

**Changelog**
- Add db chart 
@jagpreetsinghsasan @suvajit-sarkar 
#853

[ Ent-Corda ] Adding db chart

---

platforms/corda-ent/charts/notary/templates/deployment.yaml
platforms/corda-ent/charts/notary/templates/service.yaml
platforms/corda-ent/charts/notary/values.yaml
platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/db.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/notary.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/notary/Readme.md
platforms/corda-ent/configuration/roles/setup/notary/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/notary/tasks/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add helm release file for notary
#803

[ Ent-Corda ] Adding helm release file for notary

---

automation/Jenkinsfile
platforms/hyperledger-fabric/configuration/roles/setup/config_block/sign_and_update/tasks/nested_update_channel.yaml
platforms/shared/images/ansibleSlave.Dockerfile

[ci skip] Update to jdk14 for jenkins dockerfile

---

docs/source/roadmap.rst

**Changelog**
- Add software tools upgrade task
- Updated timelines 
**to be Reviewed by**
@Pri-vats 
Review link : https://ssarkar-baf.readthedocs.io/en/roadmap/roadmap.html
NA

[ci skip] Roadmap update

---

platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/float.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/float/Readme.md
platforms/corda-ent/configuration/roles/setup/float/tasks/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add ansible role for float component
#805

[ Ent-Corda ] Float ansible role

---

platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml

**Changelog**
- Add privacy flags in the besu chart.
#903

[ Besu ] Add --privacy flags to besu chart

---

platforms/corda-ent/charts/node-initial-registration/Chart.yaml
platforms/corda-ent/charts/node-initial-registration/files/node-initial-registration.sh
platforms/corda-ent/charts/node-initial-registration/files/node.conf
platforms/corda-ent/charts/node-initial-registration/templates/_helpers.tpl
platforms/corda-ent/charts/node-initial-registration/templates/configmap.yaml
platforms/corda-ent/charts/node-initial-registration/templates/job.yaml
platforms/corda-ent/charts/node-initial-registration/values.yaml

**Changelog**
- Add Node registration
**to be reviewed by**
@deepakkumardbd @jagpreetsinghsasan 
#901

[ Ent-Corda ] Node registration helm chart

---

.travis.yml
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxinit.tpl

**Changelog**
- Updated: Channel capabilities for fabric 2.0 
@sownak @jagpreetsinghsasan 
#886

[fabric] Upgrade the channel capability to version 2.0 

---

examples/supplychain-app/besu/smartContracts/README.md
examples/supplychain-app/besu/smartContracts/compile.js
examples/supplychain-app/besu/smartContracts/deploy.js
examples/supplychain-app/besu/smartContracts/package.json

**Changelog**
- Add code to compile and deploy smartcontracts
#895

[ besu ]Add code to compile and deploy smartcontracts

---

platforms/corda-ent/charts/node-initial-registration/templates/job.yaml
platforms/corda-ent/charts/node/Chart.yaml
platforms/corda-ent/charts/node/files/node.conf
platforms/corda-ent/charts/node/files/run.sh
platforms/corda-ent/charts/node/templates/_helpers.tpl
platforms/corda-ent/charts/node/templates/configmap.yaml
platforms/corda-ent/charts/node/templates/deployment.yaml
platforms/corda-ent/charts/node/templates/pvc.yaml
platforms/corda-ent/charts/node/templates/service.yaml
platforms/corda-ent/charts/node/values.yaml

**Change log**
- Add Node helm chart
- Fix Node registration variable name error 
#747

[ Ent-Corda ] Corda ent node setup helm chart

---

docs/source/operations/besu_networkyaml.md
platforms/hyperledger-besu/configuration/roles/create/crypto/orion/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml

**Changelog**
- Fix reset network to delete validatorx secrets and items
#916

fix besu bugs

---

docs/source/architectureref/certificates_path_list_corda_ent.md
platforms/corda-ent/charts/generate-pki/files/pki.conf
platforms/corda-ent/charts/node-initial-registration/templates/job.yaml
platforms/corda-ent/charts/node-initial-registration/values.yaml
platforms/corda-ent/charts/signer/files/signer.conf
platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/node_registration.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/pki-generator.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/networkroottruststore/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/node_registration/Readme.md
platforms/corda-ent/configuration/roles/setup/node_registration/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/notary/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/pki-generator/tasks/main.yaml
platforms/corda-ent/configuration/samples/network-cordaent.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add node initial registration ansible role
#919

[ Ent-Corda ] Node initial registration ansible role

---

platforms/hyperledger-besu/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml
platforms/quorum/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

Fix quorum and indy issues

---

platforms/corda-ent/configuration/roles/setup/vault_kubernetes/Readme.md
platforms/corda-ent/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

**Changelog**
- Fix regcred not created error
#920

[ci skip] Corda ent regcred bug fix

---

docs/source/architectureref/certificates_path_list_besu.md
platforms/hyperledger-besu/charts/node_orion/templates/configmap.yaml
platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_validator/values.yaml
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/Readme.md
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/hyperledger-besu/configuration/roles/helm_component/templates/validator.tpl

**Changelog**
- Add tls option for besu nodes.
#939

[ Besu ] add tls option for besu

---

platforms/corda-ent/charts/nmap/templates/deployment.yaml
platforms/corda-ent/charts/nmap/templates/pvc.yaml

**Changelog**
Fixed networkmap crashing after autoscale up and down.
Added a pvc for the networkmap so it persist initial-parameters-succesfully file 
#910

Fixed networkmap crashing after autoscaling down and up

---

platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/roles/create/cli_pod/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxinit.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/cli.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/vars/main.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/hyperledger-fabric/configuration/samples/network-minikube.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Added Ansible Role for Fabric Peer CLI
#956

Ansible Role for Fabric Peer CLI

---

docs/source/operations/adding_new_org_quorum.md
docs/source/operations/quorum_networkyaml.md
examples/supplychain-app/configuration/samples/network-quorum-supplychain.yaml
platforms/quorum/configuration/samples/network-minikube.yaml
platforms/quorum/configuration/samples/network-quorum-newnode.yaml
platforms/quorum/configuration/samples/network-quorum.yaml

**Changelog**
- Update tessera version to 0.10.4
#900

[ Quorum ] Changing quorum tessera version to 0.10.4

---

platforms/hyperledger-fabric/configuration/roles/create/cli_pod/tasks/main.yaml

Signed-off-by: himanshulalarya <himanshu.a.lal@accenture.com>
**Changelog**
- Add Peer CLI check for backward compatibility so that peer cli can be choice
#967

Cli check updated

---

automation/Jenkinsfile
docs/source/faq.md
platforms/corda-ent/charts/nmap/Chart.yaml
platforms/corda-ent/charts/nmap/templates/deployment.yaml
platforms/corda-ent/charts/node-initial-registration/Chart.yaml
platforms/corda-ent/charts/notary-initial-registration/Chart.yaml
platforms/corda-ent/configuration/roles/delete/flux_releases/meta/main.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/node_registration.tpl
platforms/corda-ent/configuration/samples/network-cordaent.yaml
platforms/hyperledger-besu/configuration/roles/delete/flux_releases/meta/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/flux_releases/meta/main.yaml
platforms/quorum/configuration/roles/delete/flux_releases/meta/main.yaml
platforms/r3-corda/configuration/roles/delete/flux_releases/meta/main.yaml
platforms/r3-corda/configuration/roles/deploy/cordapps/meta/main.yaml
platforms/shared/configuration/environment-setup.yaml
platforms/shared/configuration/molecule/default/converge.yml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml
platforms/shared/configuration/roles/setup/ambassador/meta/main.yaml
platforms/shared/configuration/roles/setup/flux/meta/main.yaml
platforms/shared/configuration/roles/setup/haproxy-ingress/meta/main.yaml
platforms/shared/configuration/roles/setup/helm/vars/main.yaml
platforms/shared/configuration/roles/setup/kubectl/vars/main.yaml
platforms/shared/configuration/roles/setup/tiller/tasks/main.yaml
platforms/shared/configuration/site.yaml

**Changelog**
- Fix Corda opensource bug #948 
- Update Helm to 2.16.10 compatible for Kubernetes 1.16
- Update Kubectl to 1.16.13 compatible for Kubernetes 1.16

Bug Fixes and upgrades

---

docs/source/operations/besu_networkyaml.md
platforms/hyperledger-besu/charts/node_orion/templates/configmap.yaml
platforms/hyperledger-besu/charts/node_orion/values.yaml
platforms/hyperledger-besu/configuration/roles/helm_component/templates/node_orion.tpl
platforms/hyperledger-besu/configuration/samples/network-besu.yaml

**Changelog**
- Add option to enable tls trust for orion from network.yaml
#941

[ Besu ] Add option to enable tls trust from network.yaml

---

platforms/corda-ent/charts/node/values.yaml
platforms/corda-ent/configuration/roles/setup/bridge/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/float/tasks/main.yaml

**Changelog**
- Added option to disable external firewall float & bridge
@abevers 
#945

[ Corda-Ent ] Added option to disable firewall (float & bridge)

---

docs/source/developer/dev_prereq.md
docs/source/faq.md
docs/source/operations/quorum_networkyaml.md

Upgrade kubernetes version

---

docs/source/developer/dev_prereq.md

Updated links to documentation

[ci skip] Fix links

---

platforms/corda-ent/charts/node/files/node.conf
platforms/corda-ent/charts/node/templates/deployment.yaml
platforms/corda-ent/charts/node/values.yaml
platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/roles/create/certificates/ambassador/node/task/main.yaml
platforms/corda-ent/configuration/roles/create/certificates/ambassador/node/task/nested_main.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/node/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/node_registration/tasks/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add Node Setup Role 
@jagpreetsinghsasan @suvajit-sarkar @sownak 
#804

[Corda-Ent] Added Node Setup Role

---

platforms/corda-ent/configuration/roles/setup/node/tasks/main.yaml

**Changelog**
- Update Node Setup Role
@sownak @abevers @suvajit-sarkar 
#804

[Corda-Ent] Updated Node Setup Role

---

platforms/corda-ent/charts/node/files/node.conf
platforms/corda-ent/charts/node/templates/deployment.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/corda-ent/configuration/roles/setup/node/tasks/main.yaml

**Changelog**
- Fixed `externalBridge` toggle so it actually disables or enables the firewall
@sownak 
#944

Toggle to enable/disable firewall works now

---

platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/Readme.md
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/node_data.yaml

**Changelog**
- Add logic to create member peers in besu network
@jagpreetsinghsasan @azoumi 
#993

[ Besu ] Add logic to create member nodes in besu

---

platforms/corda-ent/charts/notary-initial-registration/templates/job.yaml
platforms/corda-ent/charts/notary-initial-registration/values.yaml
platforms/corda-ent/charts/notary/templates/deployment.yaml
platforms/corda-ent/charts/notary/values.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/notary.tpl

**Changelog**
- Fix removed cenmServices and moved items under it to networkServices
**to be Reviewed by**
@sownak 
#961

[ Corda-Ent ] Notary chart clean up

---

platforms/corda-ent/charts/nmap/templates/deployment.yaml
platforms/corda-ent/charts/node-initial-registration/templates/job.yaml
platforms/corda-ent/charts/node/templates/deployment.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/nmap.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/node_registration.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/notary.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/notary_initial_registration.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/idman/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/node/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/node_registration/tasks/nested_main.yaml
platforms/corda-ent/configuration/roles/setup/notary-initial-registration/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/notary/tasks/main.yaml

**Changelog**
- Fix error with Vault logic to fetch `nodeInfoFileName`
- Update logic for `notary`, `notary-initial-registration`, `node` & `node-initial-registration` to fetch Docker images from (private) repository
@suvajit-sarkar @jagpreetsinghsasan 
#977

[ Corda-Ent ] Fix nmap & nodeInfoFileName error, docker image logic

---

automation/Jenkinsfile
docs/source/architectureref/certificates_path_list_corda_ent.md
docs/source/architectureref/corda-ent.md
docs/source/faq.md
docs/source/operations/configure_prerequisites.md
docs/source/operations/corda_networkyaml.md
docs/source/roadmap.rst
platforms/corda-ent/charts/generate-pki/templates/job.yaml
platforms/corda-ent/charts/node-initial-registration/templates/job.yaml
platforms/corda-ent/charts/notary-initial-registration/templates/job.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/idman.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/nmap.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/notary_initial_registration.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/idman/tasks/main.yaml
platforms/corda-ent/configuration/samples/network-cordaent.yaml

**Changelog**
- Fix VAULT_TOKEN expiring in jobs
- Fix idman charts
- Update documentation and readmes

[corda-ent] Fix jobs, idman and docs

---

platforms/corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/node_registration.tpl

**Changelog**
- Updated Node and Node Registration TPL
@sownak 
#976

[ci skip] Updated Node and Node Registration TPL

---

platforms/corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/node_registration.tpl

**Changelog**
- Update Node and Node Reg TPL Files
#976

[Corda-Ent] Updated Node and Node Registration TPL

---

docs/source/operationalguide.rst
docs/source/operations/adding_new_org_besu.md
examples/supplychain-app/besu/smartContracts/deploy.js
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/Readme.md
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/Readme.md
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/templates/ibftConfigFile.tpl
platforms/hyperledger-besu/configuration/roles/create/ibft/Readme.md
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/add_new_peer.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/nested_nodelist.yaml
platforms/hyperledger-besu/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/shared/configuration/add-new-organization.yaml

**Changelog**
- Add logic to add new member peer in existing besu network.
- Add sample network-besu-newnode.yaml.
- Add operation guide for adding new member node in besu.
@jagpreetsinghsasan @azoumi 
#975

[ Besu ] Add new member peer in existing network.

---

docs/source/prerequisites.md
docs/source/roadmap.rst

**Changelog**
- Update the EKS version details on doc
- Update roadmap ( not the final version )

Document EKS version reference change

---

docs/source/prerequisites.md

**Changelog**
- Fix indentation issue causing incorrect formatting in documentation

fixed an indentation bug in documentation

---

platforms/hyperledger-besu/configuration/samples/network-besu-newnode.yaml
platforms/hyperledger-fabric/configuration/add-organization.yaml
platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/roles/create/cli_pod/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/create_block/tasks/create_json.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/create_block/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/anchorpeer_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/cli.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/join_channel_job.tpl
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/existing_peer_cli.tpl
platforms/hyperledger-fabric/configuration/roles/setup/config_block/fetch/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/fetch/tasks/nested_fetch_role.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/sign_and_update/tasks/nested_sign_and_update.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/sign_and_update/tasks/nested_update_channel.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/hyperledger-fabric/configuration/samples/network-minikube.yaml

**Changelog**
- Add Besu `samples/network-besu-newnode.yaml`.
- Fix fabric `gossippeeraddress` bug.
- Fix clashing of peercli pods in add-organization.yaml in fabric.
- Fix same release name for multiple peer cli pod under one organization in fabric.
- Fix duplicate attribute `alpine_image` in `cli_pod/tasks/main.yaml` in fabric.
@jagpreetsinghsasan @himanshulalarya 
#1003

[ Fabric ] Fabric bugfixes

---

platforms/r3-corda-ent/charts/node/templates/deployment.yaml
platforms/r3-corda-ent/charts/node/templates/pvc.yaml
platforms/r3-corda-ent/charts/node/values.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node.tpl

**Changelog**
- Fix persistent volume for node
- Update baseDir; made it consistent with notary
@sauveergoel @jagpreetsinghsasan 
#1043

[ Corda-Ent ] Fixed persistent volume issue with node

---

platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/main.yaml

**Changelog**
-Fixed not able to do a transactions as a member node by setting min gas price to 0 as this is an enterprise network.
@lakshyakumar 
#999

Added parameter to set gas price for transaction to 0

---

docs/source/architectureref/certificates_path_list_fabric.md
docs/source/developer/fabric-ansible.md
platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/reset-network.yaml
platforms/hyperledger-fabric/configuration/roles/create/channel_artifacts/README.md
platforms/hyperledger-fabric/configuration/roles/create/channel_artifacts/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/genesis/README.md
platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/genesis/README.md
platforms/hyperledger-fabric/configuration/roles/delete/genesis/tasks/main.yaml

**Changelog**
- Add tasks to role `create/channel_artifacts` to check if genesis block has been written to Vault
- Add tasks to role `create/channel_artifacts` to write genesis block to Vault path `secret/crypto/ordererOrganizations` with name `genesisBlock_{{ channel_name }}`
- Add delete role to remove genesis blocks from the Vault 
- Update documentation associated with the tasks
@lakshyakumar @jagpreetsinghsasan @himanshulalarya 
#1028

[ Fabric ] Add writing genesis block for each channel to Vault

---

platforms/r3-corda-ent/charts/bridge/Chart.yaml
platforms/r3-corda-ent/charts/float/Chart.yaml
platforms/r3-corda-ent/charts/generate-pki/Chart.yaml
platforms/r3-corda-ent/charts/h2/Chart.yaml
platforms/r3-corda-ent/charts/idman/Chart.yaml
platforms/r3-corda-ent/charts/nmap/Chart.yaml
platforms/r3-corda-ent/charts/node-initial-registration/Chart.yaml
platforms/r3-corda-ent/charts/node/Chart.yaml
platforms/r3-corda-ent/charts/notary-initial-registration/Chart.yaml
platforms/r3-corda-ent/charts/notary/Chart.yaml
platforms/r3-corda-ent/charts/signer/Chart.yaml
platforms/r3-corda-ent/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/bridge.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/db.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/float.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/idman.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/nmap.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node_registration.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary_initial_registration.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/pki-generator.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/signer.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml

**Changelog**
- Add corda enterprise helm3 upgrade
- Changed all charts and helm release template files
- Updated reset roles for helm3 specific changes
- Fix create_signer.tpl name to signer.tpl for consistency
@sownak 
#1020

[ Corda-Ent ] Corda enterprise helm3 upgrade

---

platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/main.yaml

**Changelog**
- Fixed redeployment of besu deployment when its already deployed. It will deploy now fine when a deployment is already there and not crash
@lakshyakumar 
#1034

Fixed bug of redeployment of besu network while its already running

---

platforms/hyperledger-fabric/configuration/samples/network-minikube.yaml

[ci skip] Update minikube sample

---

docs/source/operations/fabric_networkyaml.md

[ci skip] Update networkyaml docs

---

platforms/hyperledger-indy/charts/indy-auth-job/Chart.yaml
platforms/hyperledger-indy/charts/indy-domain-genesis/Chart.yaml
platforms/hyperledger-indy/charts/indy-key-mgmt/Chart.yaml
platforms/hyperledger-indy/charts/indy-ledger-txn/Chart.yaml
platforms/hyperledger-indy/charts/indy-ledger-txn/templates/job.yaml
platforms/hyperledger-indy/charts/indy-node/Chart.yaml
platforms/hyperledger-indy/charts/indy-pool-genesis/Chart.yaml
platforms/hyperledger-indy/configuration/roles/clean/flux/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/clean/k8s_resources/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/auth_job/templates/auth_job.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/crypto/templates/crypto-generate.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/domain_genesis/templates/domain_genesis.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/ledger_txn/templates/ledger-txn.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/node/templates/node.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/pool_genesis/templates/pool_genesis.tpl
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

**Changelog**
- Updated Indy to helm3
#1026

[HL-Indy] Indy Helm 3 Upgrade

---

docs/source/operationalguide.rst
docs/source/operations/adding_new_peer_fabric.md
platforms/hyperledger-fabric/configuration/README.md
platforms/hyperledger-fabric/configuration/add-peer.yaml
platforms/hyperledger-fabric/configuration/roles/create/add_new_peer/crypto_script/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/add_new_peer/crypto_script/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/add_new_peer/crypto_script/templates/organisation_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels_join/tasks/nested_channel_join.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/common.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/peers/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv-add-peer.yaml

**Changelog**
- Add the playbook to add new peers to an existing organization in a running fabric network.
#1022

[ Fabric ] Add a playbook for addition of new peer to an existing organization in fabric

---

docs/source/architectureref/certificates_path_list_corda_ent.md
docs/source/operations/corda_networkyaml.md
platforms/r3-corda-ent/charts/node-initial-registration/templates/job.yaml
platforms/r3-corda-ent/charts/node/templates/deployment.yaml
platforms/r3-corda-ent/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/credentials/tasks/node_tasks_nested.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml

Signed-off-by: jagpreetsinghsasan <baf@accenture.com>
**Changelog**
- Update node credentials structure
#1073

[ Corda-Ent ] Fixed node credential structure

---

examples/identity-app/charts/acme/Chart.yaml
examples/identity-app/charts/alice/Chart.yaml
examples/identity-app/charts/faber/Chart.yaml
examples/identity-app/charts/webserver/Chart.yaml
examples/identity-app/configuration/roles/create/helm_component/templates/employer.tpl
examples/identity-app/configuration/roles/create/helm_component/templates/university.tpl
examples/identity-app/configuration/roles/create/helm_component/templates/webserver.tpl

**Changelog**
- Upgraded IdentityRefApp to Helm 3
#1065

[HL Indy] Upgraded IdentityRefApp to Helm 3

---

automation/Jenkinsfile
docs/source/architectureref/certificates_path_list_corda_ent.md
docs/source/operations/corda_networkyaml.md
platforms/quorum/releases/README.md
platforms/r3-corda-ent/charts/node-initial-registration/templates/job.yaml
platforms/r3-corda-ent/charts/node/templates/deployment.yaml
platforms/r3-corda-ent/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/signer.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/credentials/tasks/node_tasks_nested.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml

Signed-off-by: Sownak Roy <sownak.roy@accenture.com>

[corda-ent] update credentials

---

platforms/r3-corda-ent/charts/generate-pki/values.yaml

Signed-off-by: jagpreetsinghsasan <baf@accenture.com>
**Changelog**
- Fix pki chart value file

Fixing the value file description of pki chart

---

platforms/r3-corda-ent/charts/generate-pki/values.yaml

Signed-off-by: jagpreetsinghsasan <baf@accenture.com>
Co-authored-by: jagpreetsinghsasan <baf@accenture.com>
Merging the nodepki branch into feature/helm3

 Merging the nodepki branch into feature/helm3

---

platforms/r3-corda-ent/charts/generate-pki-node/Chart.yaml
platforms/r3-corda-ent/charts/generate-pki-node/README.md
platforms/r3-corda-ent/charts/generate-pki-node/templates/_helpers.tpl
platforms/r3-corda-ent/charts/generate-pki-node/templates/job.yaml
platforms/r3-corda-ent/charts/generate-pki-node/values.yaml

**Changelog**
- Add node pki chart 
#930

[ Corda-Ent ] Add node pki chart

---

platforms/hyperledger-besu/charts/node_orion/Chart.yaml
platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_validator/Chart.yaml
platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml
platforms/hyperledger-besu/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/helm_component/templates/node_orion.tpl
platforms/hyperledger-besu/configuration/roles/helm_component/templates/validator.tpl

**Changelog**
- Updated charts from helm 2 to helm 3 
- Tested creating network but adding new organization could not be tested because of new network security rules
#1027

Conversion helm 2 to helm 3 for besu

---

docs/source/operations/add_new_channel_fabric.md
platforms/hyperledger-fabric/configuration/add-new-channel.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml

**Changelog**
- Add new channel to the existing network.
@jagpreetsinghsasan @lakshyakumar 
#1030

[ Fabric ] Add new channel to an existing hyperledger fabric network

---

platforms/hyperledger-fabric/configuration/roles/create/storageclass/templates/azureorderer_sc.tpl
platforms/hyperledger-fabric/configuration/roles/create/storageclass/templates/azurepeer_sc.tpl

Signed-off-by: sivaramsk <sivaramsk@gmail.com>
**Changelog**
- Set volumeexpansion flat to true for Azure Storageclass. 
#1086

Set azure storageclass volumeexpansion to true

---

docs/source/architectureref/certificates_path_list_corda_ent.md
docs/source/operations/corda_networkyaml.md
platforms/r3-corda-ent/charts/generate-pki-node/templates/job.yaml
platforms/r3-corda-ent/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/pki-generator-node.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/credentials/tasks/node_tasks_nested.yaml
platforms/r3-corda-ent/configuration/roles/setup/node/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/pki-generator-node/Readme.md
platforms/r3-corda-ent/configuration/roles/setup/pki-generator-node/tasks/main.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add ansible role for pki node chart
#811

[ Corda-Ent ] Add pki node chart ansible role

---

examples/supplychain-app/charts/expressapp-quorum/Chart.yaml
examples/supplychain-app/charts/expressapp-quorum/templates/deployment.yaml
examples/supplychain-app/charts/expressapp/Chart.yaml
examples/supplychain-app/charts/expressapp/templates/deployment.yaml
examples/supplychain-app/charts/expressapp/templates/service.yaml
examples/supplychain-app/charts/frontend/Chart.yaml
examples/supplychain-app/charts/frontend/templates/deployment.yaml
examples/supplychain-app/configuration/roles/helm_component/templates/expressapi-quorum.tpl
examples/supplychain-app/configuration/roles/helm_component/templates/restserver.tpl

Signed-off-by: azoumi hafid.azoumi@accenture.com
Changelog
Updated supplychainapp to be compatible with helm 3
Reviewed by
Linked issue
#1068

[Quorum] Update supplychain app to be compatible with helm3 

---

platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/common.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto_script/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/crypto_script/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto_script/templates/orderer_organisation_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/crypto_script/templates/orderer_script.tpl

**Changelog**
- Fix enrollment of orderer admin user for orderer organization.
#1094

[ Fabric ] Fix admin user enrollment for orderer organization

---

docs/source/architectureref/certificates_path_list_fabric.md
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/common.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto_script/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/crypto_script/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto_script/templates/orderer_organisation_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/crypto_script/templates/orderer_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/orderer_cli.tpl
platforms/hyperledger-fabric/configuration/roles/k8_component/vars/main.yaml

**Changelog**
- Added the changes in PR #1079 and PR #1102 

[ Fabric ] sync feature/helm3 with latest changes

---

examples/supplychain-app/charts/expressapp/templates/deployment.yaml
examples/supplychain-app/charts/expressapp/templates/service.yaml
examples/supplychain-app/charts/springbootwebserver/templates/deployment.yaml
examples/supplychain-app/charts/springbootwebserver/values.yaml
examples/supplychain-app/configuration/roles/create/corda/webserver/tasks/main.yaml
examples/supplychain-app/configuration/roles/helm_component/templates/webserver.tpl

**Changelog**
- Update springboot chart
- Fix expressapi chart
#1050 #1103 #1106

Update springboot and expressapi chart

---

docs/source/architectureref/certificates_path_list_corda_ent.md
examples/supplychain-app/configuration/deploy-supplychain-app.yaml
examples/supplychain-app/configuration/roles/create/corda/webserver/tasks/main.yaml
examples/supplychain-app/configuration/roles/helm_component/templates/webserver-cordaent.tpl
examples/supplychain-app/configuration/roles/helm_component/vars/main.yaml
examples/supplychain-app/configuration/roles/helm_lint/vars/main.yaml
examples/supplychain-app/tests/SupplyChainTest.postman_collection.json
platforms/r3-corda-ent/configuration/roles/setup/credentials/tasks/node_tasks_nested.yaml

**Changelog**
- Add express api, webserver chart
- Fix postman collection
#1051 #1054

[ Corda-Ent ] Updated application charts for R3-Corda Enterprise

---

platforms/quorum/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/quorum/configuration/roles/setup/get_crypto/tasks/main.yaml

**Changelog**
Storing all generated certificates to the vault as redeploying them on a running network fails.
Regenerating of certificates is removed.
@lakshyakumar 
#905

[QUORUM] Bugfix #905 idempotent deployment quorum

---

docs/source/architectureref/certificates_path_list_corda_ent.md
platforms/r3-corda-ent/charts/node/templates/deployment.yaml
platforms/r3-corda-ent/charts/node/values.yaml
platforms/r3-corda-ent/charts/notary/templates/deployment.yaml
platforms/r3-corda-ent/charts/notary/values.yaml
platforms/r3-corda-ent/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary.tpl
platforms/r3-corda-ent/configuration/roles/setup/credentials/tasks/cenm_tasks.yaml
platforms/r3-corda-ent/configuration/roles/setup/credentials/tasks/node_tasks_nested.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml
platforms/r3-corda/charts/node/templates/deployment.yaml
platforms/r3-corda/charts/notary/templates/deployment.yaml

**Changelog**
1. Add vault paths for corDapps repo credentials
2. Add init-cordapps container in node and notary charts to fetch cordapps before node startup
3. Update setup/credentials role to write cordapps repo credentials to vault path
4. Update node and notary tpl file to provide cordapps details as an options 
#1049

Automated loading of CorDapps from Nexus repository

---

docs/source/operationalguide.rst
docs/source/operations/adding_new_orderer_fabric.md
platforms/hyperledger-fabric/configuration/README.md
platforms/hyperledger-fabric/configuration/add-orderer.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/tasks/nested_create_appchannel_block.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/templates/update_channel_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/vars/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/tasks/orderercheck.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/templates/syschannel_update_address_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/templates/syschannel_update_consenter_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/vars/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/crypto_script/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/crypto_script/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/crypto_script/templates/orderer_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/orderers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft-add-orderer.yaml

**Changelog**
- Add the changes to add a new raft orderer
- Add the role to add new genesis block to the vault
#1031

[ Fabric ] Addition of a new raft orderer in Fabric

---

platforms/shared/charts/haproxy/templates/deployment.yaml
platforms/shared/charts/haproxy/templates/service.yaml

**Changelog**
- Updated Stat Port for HAProxy
@abevers @lakshyakumar @sownak 
#1120

[Shared] Updated Stat Port for HAProxy

---

docs/source/operationalguide.rst
docs/source/operations/upgrade_helm_deployments.md

**Changelog**
- Add helm upgradation guide
#1089

[ Docs ] Add operational guide for helm upgrade

---

platforms/r3-corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary.tpl
platforms/r3-corda-ent/configuration/roles/setup/credentials/tasks/cenm_tasks.yaml
platforms/r3-corda-ent/configuration/roles/setup/credentials/tasks/node_tasks_nested.yaml
platforms/shared/configuration/roles/setup/flux/tasks/main.yaml

**Changelog**
- Fix error when org.cordapps is not defined
- Fix incorrect helm3 crd

Corda Ent Bug fix

---

docs/source/operationalguide.rst
docs/source/operations/removing_org_fabric.md
platforms/hyperledger-fabric/configuration/remove-organization.yaml
platforms/hyperledger-fabric/configuration/roles/create/delete_org_script/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/delete_org_script/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/delete_org_script/templates/organisation_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/delete_org_script/vars/main.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-remove-organization.yaml

Signed-off-by: rahultoraskarr <rahul.p.toraskar@accenture.com>
**Changelog**
- Add functionality to remove an organization from existing fabric network using the playbook remove-organization.yaml
@jagpreetsinghsasan @lakshyakumar
#1101

[ Fabric ] Removing organization from existing Fabric network

---

docs/source/operations/corda_networkyaml.md
platforms/r3-corda-ent/charts/float/templates/deployment.yaml
platforms/r3-corda-ent/charts/float/templates/service.yaml
platforms/r3-corda-ent/charts/float/values.yaml
platforms/r3-corda-ent/charts/node/templates/deployment.yaml
platforms/r3-corda-ent/configuration/roles/create/certificates/node/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/bridge.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/float.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node_registration.tpl
platforms/r3-corda-ent/configuration/roles/setup/node/README.md
platforms/r3-corda-ent/configuration/roles/setup/node/tasks/main.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml

**Changelog**
- Fix float to be exposed via ambassador
#1149

[ Corda-Ent ] Exposing float via ambassador

---

platforms/r3-corda-ent/configuration/roles/helm_component/templates/node.tpl

**Changelog**
- Fixed ambassador p2pAddress 

Corda-ent bug fix

---

platforms/shared/configuration/roles/setup/kubectl/tasks/main.yaml

**Changelog**
- Add addition check in role "Changing current context namespace" for molecule scenario

Molecule Test fix

---

docs/source/operations/besu_networkyaml.md
examples/supplychain-app/besu/smartContracts/deploy.js
examples/supplychain-app/configuration/README.md
examples/supplychain-app/configuration/deploy-supplychain-app.yaml
examples/supplychain-app/configuration/roles/deploy/besu/smartContract/tasks/main.yaml
examples/supplychain-app/configuration/roles/deploy/besu/smartContract/tasks/nested_deploy.yaml
examples/supplychain-app/configuration/samples/network-besu-supplychain.yaml

**Changelog**
- Add ansible code to deploy the smartcontracts on existing Hyperledger-Besu network
#940

[ Besu ] Adding ansible code to deploy the smartcontracts on existing Hyperledger-Besu network

---

examples/supplychain-app/charts/expressapp-quorum/templates/deployment.yaml
examples/supplychain-app/configuration/roles/helm_component/templates/expressapi-quorum.tpl
examples/supplychain-app/quorum/express_nodeJS/Dockerfile
examples/supplychain-app/quorum/express_nodeJS/config.js
examples/supplychain-app/quorum/express_nodeJS/controllers/container.js
examples/supplychain-app/quorum/express_nodeJS/controllers/general.js
examples/supplychain-app/quorum/express_nodeJS/controllers/product.js
examples/supplychain-app/quorum/express_nodeJS/web3services.js

Signed-off-by: srinivasan.sankaran <srinivasan.sankaran@accenture.com>
**Changelog**
- Added protocol in expressapp-quorum/templates/deployment.yaml file as env variable
- Added protocol in expressapi-quorum.tpl to make it available in value files
- Added env protocol in quorum dockerfile
- Added env variable in quorum config.js file
- Added code to do timestamp conversion based on consensus used in the container.js,product.js and general.js routes
- Added code to fetch protocol as variable to make it available to routes in examples/supplychain-app/quorum/express_nodeJS/web3services.js
@lakshyakumar 
#581

[ Quorum ] Added fix for raft timestamp issue

---

examples/supplychain-app/configuration/deploy-supplychain-app.yaml
examples/supplychain-app/configuration/roles/create/corda/expressapi/tasks/main.yaml
examples/supplychain-app/configuration/roles/create/corda/webserver/tasks/main.yaml

**Changelog**
- Fix reference  to shared helm component check for Corda OS and Corda ent ref app roles"
#1181

Fixed reference  to shared helm component

---

examples/supplychain-app/configuration/deploy-supplychain-app.yaml

**Changelog**
- Fix when cause for corda expressapi, webserver and frontend

Fixed a bug causing deploy supplychain failing for quorum

---

examples/supplychain-app/tests/SupplychainDemo_corda-ent.postman_environment.json

**Changelog**
- Fix external url for corda-ent for demo cluster
@sownak

Fix url for corda-ent postman collection 

---

docs/source/operationalguide.rst
docs/source/operations/install_instantiate_chaincode.md

-  Add Operational guide for installing and instantiating chaincode
#1165

[ Fabric ] Operational guide for install-instantiate chaincode

---

docs/source/developer/indy-ansible.md
docs/source/developer/indy-helmcharts.md
docs/source/operations/adding_new_org_indy.md
platforms/hyperledger-indy/charts/indy-ledger-txn/templates/job.yaml
platforms/hyperledger-indy/charts/indy-ledger-txn/values.yaml
platforms/hyperledger-indy/charts/indy-node/Readme.md
platforms/hyperledger-indy/charts/indy-node/templates/statefulset.yaml
platforms/hyperledger-indy/charts/indy-node/values.yaml
platforms/hyperledger-indy/configuration/cleanup.yaml
platforms/hyperledger-indy/configuration/deploy-network.yaml
platforms/hyperledger-indy/configuration/roles/check/validation/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/copy/vault_crypto_values/README.md
platforms/hyperledger-indy/configuration/roles/copy/vault_crypto_values/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/ledger_txn/templates/ledger-txn.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/node/templates/node.tpl
platforms/hyperledger-indy/configuration/samples/network-indy-newnode.yaml

**Changelog**
- Added Indy validator nodes 
#986

[HL Indy] Add Indy VALIDATOR Nodes

---

README.md

**Changelog**
- Typo: Replaced Jeknins with Jenkins

Changed Jeknins to Jenkins

---

README.md
examples/supplychain-app/fabric/chaincode_rest_server/rest-server/yarn.lock
platforms/r3-corda/images/doorman/website/package-lock.json
platforms/r3-corda/images/doorman/website/package.json
platforms/r3-corda/images/networkmap/website/package-lock.json
platforms/r3-corda/images/networkmap/website/package.json

merge latest from master

---

platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/main.yaml

**Changelog**
- Fix the image repository for couchdb
@jagpreetsinghsasan @suvajit-sarkar 
#1213

Fix couchdb repository for Fabric

---

platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

**Changelog**
- Fixed quotes format for AWS CLI updates 
@sownak @suvajit-sarkar

[Shared] Fixed quotes format for AWS CLI updates

---

automation/Jenkinsfile

**Changelog**
- Added "removal of an org" in Jenkins stage for Hyperledger Fabric for v2.2.0
- Replaced version 2.0.0 with with 2.2.0 as Fabric version choice from Jenkins build options

Jenkins script update 

---

automation/Jenkinsfile

**Changelog**
- Fix file check 
- Added a dummy removeorg.yaml file its not there in configuration repo

Jenkis fixes

---

platforms/hyperledger-fabric/configuration/roles/create/crypto_script/templates/organisation_script.tpl

**Changelog**
- Fix the incorrect OU for fabric
#1191

[fabric] Fix Fabric updating incorrect OU

---

docs/source/operations/adding_new_org_besu.md
docs/source/operations/besu_networkyaml.md
platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-newnode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml

**Changelog**
- Upgraded HL Besu to v1.5.5 and Orion to v1.6.0 
@sownak @suvajit-sarkar @lakshyakumar  
#1160

[HL Besu] Upgraded HL Besu to v1.5.5 and Orion to v1.6.0

---

docs/source/example/supplychain.md

**Changelog**
- Update documentation for supplychain reference application 
#864

Update supplychain app docs

---

docs/source/roadmap.rst

**Changelog**
- Update the roadmap

Update the roadmap post release v0.7

---

platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/tasks/main.yaml

**Changelog**
- Add wait for chaincode installation for other peer till first peer of an organization packages and install chaincode 
- Fix the chaincode installation so that the chaincode packaging is once per organization
#1264

[Fabric] fix chaincode installation and packaging for Fabric version 2.2.x

---

Dockerfile

**Changelog**
- Fix openshift version 

[Hotfix] Fixed the openshift version from latest to 0.10.1

---

docs/source/operations/adding_new_org_besu.md
docs/source/operations/besu_networkyaml.md
platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/add_new_peer.yaml
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/nested_enode_data.yaml
platforms/hyperledger-besu/configuration/roles/create/validator/tasks/nested_enode_data.yaml
platforms/hyperledger-besu/configuration/roles/helm_component/templates/node_orion.tpl
platforms/hyperledger-besu/configuration/roles/helm_component/templates/validator.tpl
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

**Changelog**
- Update deployment to allow DNS on network.yaml
#983

[ Besu ] Enablement of DNS support in HL Besu

---

platforms/shared/configuration/kubernetes-env-setup.yaml

Fixed a Bug causing git ssh protocol not working
RCA - git_url variable was missing and typo error

Fix git ssh protocol not working

---

docs/source/roadmap.rst

**Changelog**
- Update roadmap feature list

Roadmap update

---

platforms/r3-corda-ent/charts/nmap/templates/deployment.yaml
platforms/r3-corda-ent/charts/nmap/values.yaml
platforms/r3-corda-ent/charts/notary-initial-registration/templates/job.yaml
platforms/r3-corda-ent/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/nmap.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/pki-generator.tpl
platforms/r3-corda-ent/configuration/roles/setup/nmap/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/notary-initial-registration/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/notary-initial-registration/tasks/nested_main.yaml
platforms/r3-corda-ent/configuration/roles/setup/notary/tasks/main.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml
platforms/shared/configuration/kubernetes-env-setup.yaml

**Changelog**
- Add multiple notary option in network.yaml
- Update nmap chart logic to create network-initial-param with multiple notaries
- Fix git SSH protocol not working 
#1222

Enable multi notary deployment

---

docs/source/example/supplychain.md
docs/source/operations/install_instantiate_chaincode.md
docs/source/operations/upgrading_chaincode.md
examples/supplychain-app/README.md
platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
platforms/hyperledger-fabric/configuration/README.md
platforms/hyperledger-fabric/configuration/chaincode-ops.yaml
platforms/shared/configuration/add-new-organization.yaml
platforms/shared/configuration/site.yaml

**Changelog**
- Updated documentation for fabric v2.2
- Renamed chaincode-install-instantiate yaml file to chaincode-ops
- Tested changes deploying fabric v2.2
#1282

[ Fabric ] Updated doc Install and Instantiation Chaincode guide

---

platforms/r3-corda/charts/nms/templates/deployment.yaml
platforms/r3-corda/charts/nms/templates/volume.yaml
platforms/r3-corda/configuration/deploy-network.yaml
platforms/r3-corda/configuration/roles/create/certificates/doorman/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/certificates/nms/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/certificates/node/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/certificates/notary/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/k8_component/templates/create_doorman.tpl
platforms/r3-corda/configuration/roles/create/k8_component/templates/network_map.tpl
platforms/r3-corda/configuration/roles/create/node_component/templates/node.tpl
platforms/r3-corda/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/r3-corda/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda/configuration/roles/delete/vault_secrets/tasks/nested_main.yaml
platforms/shared/configuration/kubernetes-env-setup.yaml

**Changelog**
- Add proxy node option for BAF Corda OS
- Update NMS (non TLS) chart to add log container 
#1290

Proxy none option for Corda OS

---

platforms/hyperledger-besu/charts/node_orion/templates/service.yaml
platforms/hyperledger-besu/charts/node_validator/templates/service.yaml
platforms/shared/charts/ambassador/values.yaml
platforms/shared/configuration/roles/setup/ambassador/vars/main.yaml

Signed-off-by: ragalz <r.galan.lopez@accenture.com>
**Changelog**
- Update besu's ambassador annotations to v2
- Update docs
#1286

Upgrade besu's ambassador annotations to v2

---

platforms/hyperledger-fabric/charts/anchorpeer/templates/anchorpeer.yaml
platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml
platforms/hyperledger-fabric/charts/ca/templates/deployment.yaml
platforms/hyperledger-fabric/charts/commit_chaincode/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/charts/create_channel/templates/create_channel.yaml
platforms/hyperledger-fabric/charts/fabric_cli/templates/deployment.yaml
platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
platforms/hyperledger-fabric/charts/instantiate_chaincode/templates/instantiate_chaincode.yaml
platforms/hyperledger-fabric/charts/invoke_chaincode/templates/invoke_chaincode.yaml
platforms/hyperledger-fabric/charts/join_channel/templates/join_channel.yaml
platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml
platforms/hyperledger-fabric/charts/peernode/templates/deployment.yaml
platforms/hyperledger-fabric/charts/upgrade_chaincode/templates/upgrade_chaincode.yaml
platforms/hyperledger-fabric/charts/verify_chaincode/templates/verify_chaincode.yaml

**Changelog**
- Add improved validation function for vault response
@jagpreetsinghsasan @suvajit-sarkar 
#issue_number

[ Fabric ]Fix for issue #1179

---

platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/approve/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/chaincode/approve/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/commit/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/chaincode/commit/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/instantiate/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/chaincode/instantiate/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/upgrade/tasks/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/chaincode/upgrade/tasks/valuefile.yaml

Signed-off-by: ragalz <r.galan.lopez@accenture.com>
**Changelog**
- Update chaincode checking tasks to use shared roles
- Update documentation
#1298

Use shared roles for chaincode checks

---

README.md

Signed-off-by: Jagpreet Singh Sasan <jagpreet.singh.sasan@accenture.com>
**Changelog**
- Update Readme.md for the all-contributors bot
@sownak

Updated readme to include all-contributor-bot

---

.all-contributorsrc
README.md

Reverts hyperledger-labs/blockchain-automation-framework#1340

Revert "docs: add RafaelAPB as a contributor"

---

.github/workflows/molecule_test.yml
platforms/hyperledger-fabric/configuration/molecule/crypto/converge.yml
platforms/hyperledger-fabric/configuration/molecule/crypto/verify.yml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/tasks/nested_create_appchannel_block.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/storageclass/vars/main.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft-add-orderer.yaml

[fabric] updated vault

---

platforms/hyperledger-fabric/configuration/chaincode-ops.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/tasks/nested_install.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/tasks/valuefile.yaml

**Changelog**
- Fix different number of orgs in channel section than org section
@jagpreetsinghsasan @alvaropicazo 
#1308

[ Fabric ]Bug fix for different number of orgs in channel section than org section

---

platforms/hyperledger-fabric/configuration/add-peer.yaml
platforms/hyperledger-fabric/configuration/roles/create/add_new_peer/update_block/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/add_new_peer/update_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/add_new_peer/update_block/tasks/nested_update_channel.yaml
platforms/hyperledger-fabric/configuration/roles/create/add_new_peer/update_block/tasks/peercheck.yaml
platforms/hyperledger-fabric/configuration/roles/create/add_new_peer/update_block/templates/add_peer.tpl
platforms/hyperledger-fabric/configuration/roles/create/add_new_peer/update_block/vars/main.yaml

**Changelog**
- Added update block folder under add_new_peer folder to fetch the block, decode it, add the anchor part to the json and do the update.
#1307 
**Screenshot**
After adding the new peer to the existing organization, I fetched the block and decoded it, and the information of the new added peer appears in the anchorpeers section as we have created an anchorpeer.

[fabric] Fixed addition of new anchor peer to the existing org

---

platforms/hyperledger-fabric/configuration/molecule/orderer/converge.yml
platforms/hyperledger-fabric/configuration/molecule/peer/cleanup.yml
platforms/hyperledger-fabric/configuration/molecule/peer/converge.yml
platforms/hyperledger-fabric/configuration/molecule/peer/molecule.yml
platforms/hyperledger-fabric/configuration/molecule/peer/prepare.yml
platforms/hyperledger-fabric/configuration/molecule/peer/verify.yml
platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/main.yaml
platforms/shared/configuration/roles/check/helm_component/tasks/main.yaml

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>
**Changelog**
- Added the 'peer' molecule scenario to fabric
@sownak 
#636

[fabric] Created the peer molecule scenario

---

platforms/r3-corda/charts/doorman-tls/templates/deployment.yaml
platforms/r3-corda/charts/doorman/templates/deployment.yaml
platforms/r3-corda/charts/h2-addUser/templates/job.yaml
platforms/r3-corda/charts/h2-password-change/templates/job.yaml
platforms/r3-corda/charts/mongodb-tls/templates/deployment.yaml
platforms/r3-corda/charts/mongodb/templates/deployment.yaml
platforms/r3-corda/charts/nms-tls/templates/deployment.yaml
platforms/r3-corda/charts/nms/templates/deployment.yaml
platforms/r3-corda/charts/node-initial-registration/templates/job.yaml
platforms/r3-corda/charts/node/templates/deployment.yaml
platforms/r3-corda/charts/notary-initial-registration/templates/job.yaml
platforms/r3-corda/charts/notary/templates/deployment.yaml
platforms/r3-corda/configuration/roles/setup/node/tasks/main.yaml

**Changelog**
- Add enhancement for vault responses
#1270

[ Corda ] Enhancing vault response for corda OS helm charts

---

docs/source/roadmap.rst

Signed-off-by: suvajit-sarkar <suvajit.sarkar@accenture.com> 
@sownak
for preview : https://ssarkar-baf.readthedocs.io/en/roadmap/roadmap.html
#1354

Roadmap update post release 0.8

---

platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/molecule/crypto/converge.yml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto_script/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/crypto_script/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/crypto_script/templates/orderer_script.tpl

Fixes for network.env.proxy and failing github actions

[fabric] proxy fixes

---

platforms/r3-corda/configuration/molecule/networkmap/cleanup.yml
platforms/r3-corda/configuration/molecule/networkmap/converge.yml
platforms/r3-corda/configuration/molecule/networkmap/molecule.yml
platforms/r3-corda/configuration/molecule/networkmap/prepare.yml
platforms/r3-corda/configuration/molecule/networkmap/verify.yml
platforms/r3-corda/configuration/molecule/node/INSTALL.rst
platforms/r3-corda/configuration/molecule/node/cleanup.yml
platforms/r3-corda/configuration/molecule/node/converge.yml
platforms/r3-corda/configuration/molecule/node/molecule.yml
platforms/r3-corda/configuration/molecule/node/prepare.yml
platforms/r3-corda/configuration/molecule/node/verify.yml
platforms/r3-corda/configuration/roles/create/certificates/nms/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/nms/tasks/main.yaml
platforms/shared/configuration/roles/check/k8_component/tasks/main.yaml

Signed-off-by: Angela.Alagbe <54588164+angelaalagbe@users.noreply.github.com>
**Changelog**
- Added networkmap molecule scenario
#625 #1327

[corda] Added networkmap molecule scenario

---

docs/source/faq.md
docs/source/operations/fabric_networkyaml.md
docs/source/operations/upgrade_fabricnetwork.md
platforms/hyperledger-fabric/charts/approve_chaincode/values.yaml
platforms/hyperledger-fabric/charts/commit_chaincode/values.yaml
platforms/hyperledger-fabric/charts/install_chaincode/values.yaml
platforms/hyperledger-fabric/charts/instantiate_chaincode/values.yaml
platforms/hyperledger-fabric/charts/invoke_chaincode/values.yaml
platforms/hyperledger-fabric/charts/peernode/values.yaml
platforms/hyperledger-fabric/charts/upgrade_chaincode/values.yaml
platforms/hyperledger-fabric/charts/verify_chaincode/values.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/peer.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-remove-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv-add-peer.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft-add-orderer.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/hyperledger-fabric/configuration/samples/network-proxy-none.yaml

**Changelog**
- Updated the supported Fabric versions on docs and on sample network.yamls
- Fixed a condition which threw error when using proxy as none

Fabric version updates in docs and samples

---

.all-contributorsrc
README.md
docs/source/roadmap.rst
examples/supplychain-app/fabric/chaincode_rest_server/rest-server/yarn.lock
platforms/hyperledger-fabric/configuration/add-peer.yaml

Resolve master to develop merge conflicts

---

.all-contributorsrc
README.md

Signed-off-by: Ry Jones <ry@linux.com>
**Changelog**
- fix Readme

docs: update README.md [skip ci]

---

.all-contributorsrc
README.md

Signed-off-by: Ry Jones <ry@linux.com>

Add Alvaro Picazo

---

README.md

Merge latest master to develop

---

.github/workflows/molecule_test.yml
platforms/hyperledger-fabric/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node_registration.tpl
platforms/r3-corda-ent/configuration/roles/setup/node_registration/tasks/nested_main.yaml

**Changelog**
- Fix usage of correct subject for Peers
- Removed wait time for node registration as the wait is built-in charts

[corda-ent] Peer subject fix

---

platforms/r3-corda/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/r3-corda/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda/configuration/roles/delete/vault_secrets/tasks/nested_main.yaml

Fix deployment issues for Corda

[corda] fix k8s module

---

platforms/hyperledger-indy/images/indy-node/Dockerfile

Signed-off-by: Dimbu Afonso <dimbu.k.afonso@accenture.com>
**Changelog**
- Fixing outdated packages that were causing indy node from building
#1396

Fixing issue with outdated packages

---

Dockerfile

Signed-off-by: Dimbu Afonso <dimbu.k.afonso@accenture.com>
**Changelog**
- Fixed broken pip version not working with python
#1406

rewritten Dockerfile to install python 3.6.5

---

examples/supplychain-app/charts/expressapp/templates/service.yaml
examples/supplychain-app/charts/frontend/templates/service.yaml
platforms/r3-corda/charts/doorman-tls/templates/service.yaml
platforms/r3-corda/charts/doorman/templates/service.yaml
platforms/r3-corda/charts/nms-tls/templates/service.yaml
platforms/r3-corda/charts/nms/templates/service.yaml
platforms/r3-corda/charts/node/templates/service.yaml
platforms/r3-corda/charts/notary/templates/service.yaml
platforms/r3-corda/configuration/samples/network-cordav2.yaml

**Changelog**
- Update ambassador annotations to v2 for Corda OS and supplychain ref. app services 
@sownak 
#1288

Updated ambassador annotations to v2

---

platforms/quorum/configuration/.yamllint
platforms/quorum/configuration/molecule/ambassador-certs/cleanup.yml
platforms/quorum/configuration/molecule/ambassador-certs/converge.yml
platforms/quorum/configuration/molecule/ambassador-certs/molecule.yml
platforms/quorum/configuration/molecule/ambassador-certs/prepare.yml
platforms/quorum/configuration/molecule/ambassador-certs/verify.yml
platforms/quorum/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml

Signed-off-by: Angela Alagbe <angela.alagbe@accenture.com>
**Changelog**
- Added a molecule ambassador-certs test scenario
- Updated ambassador-certs nested_main.yaml file
@sownak 
#719

[Quorum] added molecule ambassador-certs scenario

---

docs/source/roadmap.rst

**Changelog**
- Update roadmap
@sownak

Updated Roadmap

---

platforms/r3-corda/charts/nms-tls/templates/deployment.yaml
platforms/r3-corda/charts/nms/templates/deployment.yaml
platforms/r3-corda/images/networkmap/website/app/scripts/processData.js

[corda] fix networkmap frontend for Opensource Corda

---

platforms/hyperledger-fabric/configuration/remove-organization.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/sign_and_update/tasks/main.yaml

- Fix bug removing an org in DR
@alvaropicazo 
#1408

[ fabric ]bug resolve for removeOrg in DR scenario

---

platforms/r3-corda-ent/charts/float/templates/service.yaml
platforms/r3-corda-ent/charts/generate-pki/values.yaml
platforms/r3-corda-ent/charts/idman/templates/service.yaml
platforms/r3-corda-ent/charts/nmap/templates/service.yaml
platforms/r3-corda-ent/charts/node/templates/service.yaml
platforms/r3-corda-ent/charts/notary/templates/service.yaml
platforms/r3-corda-ent/charts/signer/values.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/pki-generator.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/signer.tpl
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml

Ambassador V2 changes for corda enterprise
Resolves #1287

[corda-ent] ambassadorv2 upgrade

---

platforms/quorum/configuration/molecule/default/cleanup.yml
platforms/quorum/configuration/molecule/default/converge.yml
platforms/quorum/configuration/molecule/default/molecule.yml
platforms/quorum/configuration/molecule/default/prepare.yml
platforms/quorum/configuration/molecule/default/verify.yml

**Changelog**
- Added molecule test for default scenario
@suvajit-sarkar @deepakkumardbd @jagpreetsinghsasan 
#718

added default molecule tests

---

platforms/hyperledger-besu/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/hyperledger-fabric/configuration/reset-network.yaml
platforms/hyperledger-indy/configuration/roles/clean/flux/tasks/main.yaml
platforms/quorum/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/r3-corda-ent/configuration/reset-network.yaml
platforms/r3-corda/configuration/reset-network.yaml
platforms/shared/configuration/roles/setup/flux/tasks/main.yaml

Signed-off-by: Jose <pppazos@gmail.com>
**Changelog**
- Add namespace for flux  named as flux-<environment>
- Create flux inside new namespace
- Delete namespace on reset playbooks for all networks
1292

create namespace for flux deployment

---

platforms/quorum/configuration/molecule/default/cleanup.yml
platforms/quorum/configuration/molecule/default/converge.yml
platforms/quorum/configuration/molecule/default/verify.yml
platforms/quorum/configuration/roles/create/namespace_serviceaccount/tasks/main.yaml
platforms/quorum/configuration/roles/create/storageclass/tasks/main.yaml

Signed-off-by: Dimbu Afonso <dimbu.k.afonso@accenture.com>
**Changelog**
- Fixed vars errors and storage class creation loop
@deepakkumardbd 
#718

fixed vars errors and storage class creation loop

---

platforms/r3-corda-ent/charts/bridge/templates/deployment.yaml
platforms/r3-corda-ent/charts/float/templates/deployment.yaml
platforms/r3-corda-ent/charts/generate-pki-node/templates/job.yaml
platforms/r3-corda-ent/charts/generate-pki/templates/job.yaml
platforms/r3-corda-ent/charts/idman/templates/deployment.yaml
platforms/r3-corda-ent/charts/nmap/templates/deployment.yaml
platforms/r3-corda-ent/charts/node-initial-registration/templates/job.yaml
platforms/r3-corda-ent/charts/node/templates/deployment.yaml
platforms/r3-corda-ent/charts/notary-initial-registration/templates/job.yaml
platforms/r3-corda-ent/charts/notary/templates/deployment.yaml
platforms/r3-corda-ent/charts/signer/templates/deployment.yaml
platforms/shared/configuration/kubernetes-env-setup.yaml

- Add Enhancement for vault responses
#1269

[ corda ]Enhancing vault responses

---

examples/supplychain-app/fabric/chaincode_rest_server/rest-server/yarn.lock
platforms/r3-corda/images/doorman/website/package-lock.json
platforms/r3-corda/images/networkmap/website/package-lock.json
platforms/shared/configuration/kubernetes-env-setup.yaml
platforms/shared/configuration/molecule/kubernetes-corda/verify.yml
platforms/shared/configuration/molecule/kubernetes-fabric/verify.yml
platforms/shared/configuration/molecule/kubernetes-indy/verify.yml
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

**Changelog**
- Add
- Fix
- Update
#issue_number

[shared] latest merge master

---

.github/workflows/chaincode_test.yml

Signed-off-by: Dimbu Afonso <dimbu.k.afonso@accenture.com>
**Changelog**
- Adding chaincode static tests
#739

adding chaincode static tests

---

automation/Jenkinsfile
examples/identity-app/README.md
examples/identity-app/charts/acme/templates/service.yaml
examples/identity-app/charts/acme/values.yaml
examples/identity-app/charts/alice/templates/service.yaml
examples/identity-app/charts/alice/values.yaml
examples/identity-app/charts/faber/templates/service.yaml
examples/identity-app/charts/faber/values.yaml
examples/identity-app/configuration/roles/create/helm_component/templates/employer.tpl
examples/identity-app/configuration/roles/create/helm_component/templates/university.tpl
platforms/hyperledger-indy/charts/indy-key-mgmt/templates/job.yaml
platforms/hyperledger-indy/charts/indy-ledger-txn/templates/job.yaml
platforms/hyperledger-indy/charts/indy-node/templates/statefulset.yaml
platforms/hyperledger-indy/configuration/samples/network-indy-newnode.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3-aries.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube-aries.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube.yaml
platforms/hyperledger-indy/images/indy-cli/indy-ledger.sh
platforms/hyperledger-indy/images/indy-key-mgmt/Dockerfile
platforms/hyperledger-indy/images/indy-key-mgmt/src/identity_crypto_generator.py
platforms/hyperledger-indy/images/indy-node/Dockerfile
platforms/r3-corda/charts/node-initial-registration/README.md
platforms/r3-corda/charts/node/README.md
platforms/r3-corda/charts/notary-initial-registration/README.md
platforms/r3-corda/charts/notary/README.md

**Changelog**
- Update Indy docker images to support Indy version 1.12.1
- Allow webhook ports to be exposed over Ambassador
Resolves #1256

[indy] Upgrade Indy to 1.12.1

---

platforms/quorum/configuration/molecule/crypto-tessera/cleanup.yml
platforms/quorum/configuration/molecule/crypto-tessera/converge.yml
platforms/quorum/configuration/molecule/crypto-tessera/molecule.yml
platforms/quorum/configuration/molecule/crypto-tessera/prepare.yml
platforms/quorum/configuration/molecule/crypto-tessera/verify.yml
platforms/quorum/configuration/roles/create/crypto/tessera/tasks/nested_main.yaml

to include idempotence-notest
Signed-off-by: Angela Alagbe <angela.alagbe@accenture.com>
**Changelog**
- Added molecule scenario
- Updated existing crypto-tessera role
#722

Added molecule scenario for crypto-tessera and modified crypto-tessera role

---

.github/workflows/molecule_test.yml

Signed-off-by: Angela Alagbe <angela.alagbe@accenture.com>
**Changelog**
- Added changes to github workflows
#722 (and all prev issues I've worked on)

added all changes made to changes to github workflows

---

docs/source/operations/besu_networkyaml.md
platforms/hyperledger-besu/configuration/samples/network-besu-newnode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml

Deployed 21.1.1 Besu version using latest Orion version (21.1.0) and also 1.6.0.
**Changelog**
- Updated orion and besu versions in samples and docs
#1452

[besu] Updated besu and orion version in samples and docs

---

platforms/hyperledger-besu/configuration/add-validator.yaml
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/Readme.md
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/add_to_vault.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/check_vault.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/create_enode.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/enode_data.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/nested_enode_data.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/nested_nodelist.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/node_data.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/nodelist.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/validator_vote.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-new-validatornode.yaml

**Changelog**
- Added validator_node role for creating new enode, certs and doing the voting process by existing validator nodes
- Fixed create/ambassador nested_main condition
- Updated docs for new role
#1494 
**Screenshots**
Helm releases files are updated correctly with all the static nodes

[besu] Adding new validator node to existing network

---

platforms/shared/configuration/environment-setup.yaml
platforms/shared/configuration/roles/setup/aws-cli/tasks/main.yaml
platforms/shared/configuration/roles/setup/aws-cli/vars/main.yaml

**Changelog**
- Update aws cli to v2
@sownak 
#1514

[shared] update AWS cli to v2

---

examples/supplychain-app/besu/smartContracts/package-lock.json
examples/supplychain-app/fabric/chaincode_rest_server/rest-server/package.json
examples/supplychain-app/fabric/chaincode_rest_server/rest-server/yarn.lock

[fabric] upgrade versions

---

.github/workflows/molecule_test.yml
platforms/quorum/configuration/molecule/crypto-constellation/converge.yml
platforms/quorum/configuration/roles/create/crypto/constellation/tasks/nested_main.yaml

**Changelog**
- Add required libraries in molecule test workflow

[quorum] Added constellation prereq. in the molecule test workflow

---

docs/source/prerequisites.md
platforms/hyperledger-fabric/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/shared/charts/ambassador/values.yaml

**Changelog**
- Update versions for software in docs
- Fix empty cacert file
- Update default ambassador ports

[indy] fix docs

---

platforms/quorum/configuration/molecule/crypto-ibft/converge.yml
platforms/quorum/configuration/roles/create/crypto/ibft/tasks/nested_main.yaml
platforms/quorum/configuration/roles/create/genesis_nodekey/tasks/main.yaml
platforms/quorum/configuration/roles/setup/golang/tasks/main.yaml
platforms/quorum/configuration/roles/setup/golang/vars/main.yaml

**Changelog**
- Fixed quorum crypto-ibft molecule test errors

[quorum] fixed molecule test errors

---

platforms/quorum/configuration/molecule/constellation/cleanup.yml
platforms/quorum/configuration/molecule/constellation/converge.yml
platforms/quorum/configuration/molecule/constellation/molecule.yml
platforms/quorum/configuration/molecule/constellation/prepare.yml
platforms/quorum/configuration/molecule/constellation/verify.yml
platforms/quorum/configuration/roles/create/constellation/tasks/main.yaml
platforms/quorum/configuration/roles/create/constellation/tasks/nested_enode_data.yaml
platforms/quorum/configuration/roles/create/genesis_raft/tasks/main.yaml
platforms/quorum/configuration/roles/create/genesis_raft/tasks/nested_validator_node_data.yaml
platforms/quorum/configuration/roles/helm_component/tasks/main.yaml
platforms/shared/configuration/roles/helm_lint/tasks/main.yaml

**Changelog**
- Add new test for create/constellation rol
- Fixed task using notest tag or changed_when: false to be able to run the implemented test
@alvaropicazo
#725

[quorum] Implemented test for create/constellation rol

---

platforms/shared/configuration/roles/git_push/tasks/main.yaml
platforms/shared/configuration/roles/setup/kubectl/defaults/main.yaml

Signed-off-by: pppazos <pppazos@gmail.com>
**Changelog**
- upgrade kubectl 1.19.8
#1538

[shared] update kubectl to 1.19.8

---

platforms/hyperledger-besu/charts/node_besu/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_tessera/templates/deployment.yaml

**Changelog**
- Add improved validation function for vault response in besu: node_tessera and node_besu. 
**Tested Scenarios**
Besu tessera/besu vault sealed
Besu tessera/besu vault port changed
@alvaropicazo
#1364

[besu] Vault validation function improvement for tessera and besu nodes

---

Dockerfile
Dockerfile.jdk8
docs/source/operations/corda_networkyaml.md
platforms/network-schema.json
platforms/r3-corda/configuration/samples/network-cordav2.yaml
platforms/r3-corda/configuration/samples/network-minikube.yaml
platforms/shared/configuration/network-schema-validator.yaml
platforms/shared/configuration/site.yaml
run.sh

**Changelog**
- Add network-schema.json with shared and corda schemas
- Add ajv-cli tool to docker image
- Update run.sh script to validate network.yaml file before execution
#1558 
#1559

[shared] network.yaml schema validator

---

docs/source/faq.md

Signed-off-by: Tracy Kuhrt <tracy.a.kuhrt@accenture.com>
**Changelog**
- Fix typo
@tkuhrt
N/A

[docs] change Fulcrum to Blockchain Automation Framework

---

platforms/quorum/charts/node_tessera/templates/service.yaml
platforms/quorum/configuration/roles/helm_component/templates/quorum.tpl
platforms/quorum/configuration/roles/helm_component/templates/tessera.tpl
platforms/quorum/configuration/samples/network-minikube.yaml
platforms/quorum/configuration/samples/network-quorum-newnode.yaml
platforms/quorum/configuration/samples/network-quorum-tessera.yaml
platforms/quorum/configuration/samples/network-quorum.yaml

**Changelog**
- Add clientport variable under transaction_manager field
- Fix clientport hardcoded in tessera service.yaml
- Update tessera and quorum release file template
@sownak

[quorum] update sample yamls for quourm, changed variable name for q2t port

---

automation/Jenkinsfile
platforms/network-schema.json
platforms/quorum/configuration/roles/create/crypto/tessera/tasks/check_vault.yaml

Fixed deployment issues with network validation

[quorum] fix deployment issues

---

docs/source/operations/fabric_networkyaml.md
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/anchorpeer_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/create_channel_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/orderernode.tpl
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-ordererorg.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-remove-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv-add-peer.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft-add-orderer.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/hyperledger-fabric/configuration/samples/network-proxy-none.yaml
platforms/network-schema.json

**Changelog**
- Update network-schema.json with HL Fabric rules
- Update fabric operation guide with json-schema instructions and missing fields description
- Update fabric sample network templates with meta directive $schema
@pppazos
#1589

[fabric] Schema validation for fabric  network.yaml 

---

platforms/hyperledger-besu/configuration/roles/create/crypto/tessera/Readme.md
platforms/hyperledger-besu/configuration/roles/create/crypto/tessera/tasks/main.yaml
platforms/quorum/charts/node_quorum/templates/deployment.yaml
platforms/quorum/charts/node_tessera/templates/deployment.yaml
platforms/quorum/charts/tessera_key_mgmt/templates/job.yaml
platforms/quorum/configuration/reset-network.yaml
platforms/quorum/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/quorum/configuration/roles/create/crypto/ibft/Readme.md
platforms/quorum/configuration/roles/create/crypto/ibft/tasks/nested_main.yaml
platforms/quorum/configuration/roles/create/crypto/raft/Readme.md
platforms/quorum/configuration/roles/create/crypto/raft/tasks/nested_main.yaml
platforms/quorum/configuration/roles/create/crypto/tessera/Readme.md
platforms/quorum/configuration/roles/create/crypto/tessera/tasks/check_vault.yaml
platforms/quorum/configuration/roles/create/crypto/tessera/vars/main.yaml
platforms/quorum/configuration/roles/create/genesis_raft/tasks/nested_validator_node_data.yaml
platforms/quorum/configuration/roles/create/tessera/tasks/nested_enode_data.yaml
platforms/quorum/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/quorum/configuration/roles/helm_component/templates/crypto_tessera.tpl
platforms/quorum/configuration/roles/helm_component/templates/quorum.tpl
platforms/quorum/configuration/roles/helm_component/templates/tessera.tpl
platforms/quorum/configuration/roles/setup/get_crypto/tasks/main.yaml
platforms/quorum/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/quorum/configuration/samples/network-quorum-newnode.yaml
platforms/quorum/configuration/samples/network-quorum-tessera.yaml
platforms/quorum/configuration/samples/network-quorum.yaml
platforms/quorum/releases/README.md
platforms/r3-corda/configuration/roles/create/certificates/ambassador/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/certificates/doorman/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/get_crypto/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

**Changelog**
- Update vault commands to v2
- Update any file paths, as per needed
@sownak 
#1549

[quorum] Update to vault v2

---

platforms/quorum/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml

**Changelog**
- Fix typo in create ambassador cert role
#1549

[quorum] support for vaultv2

---

docs/source/operations/besu_networkyaml.md
platforms/hyperledger-besu/configuration/samples/network-besu-new-validatornode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-new-validatororg.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-newnode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml
platforms/network-schema.json
platforms/r3-corda-ent/configuration/samples/network-addNotary.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml
platforms/r3-corda/configuration/samples/network-cordav2.yaml
platforms/r3-corda/configuration/samples/network-minikube.yaml

**Changelog**
- Update network-schema.json to include besu network validation
@pppazos 
#1591

[besu] add schema definition for besu

---

docs/source/operations/besu_networkyaml.md
platforms/network-schema.json

**Changelog**
- Update instructions in besu doc and minor regex update
@pppazos
#1591

[besu] Besu schema update

---

platforms/r3-corda/charts/node/templates/deployment.yaml
platforms/r3-corda/charts/notary/templates/deployment.yaml

Added Run Schema migration command before node and notary startup

---

docs/source/roadmap.rst

[docs] fix gnatt chart

---

platforms/shared/configuration/network-schema-validator.yaml

**Changelog**
- Update validation to use yaml file created from ansible network variable
@pppazos

[shared] Schema validation based on ansible network variable

---

docs/source/operations/indy_networkyaml.md
platforms/hyperledger-indy/configuration/samples/network-indy-newnode.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3-aries.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube-aries.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube.yaml
platforms/network-schema.json

**Changelog**
- Update network-schema.yaml to include indy network schema validations
@pppazos
#1616

[indy] schema validation for indy network

---

.github/workflows/networkschema_test_.yml

**Changelog**
- Add git action to validate sample network templates
@pppazos 

[shared] add git action to validate sample networks

---

docs/source/operations/quorum_networkyaml.md
platforms/network-schema.json
platforms/quorum/configuration/samples/network-minikube.yaml
platforms/quorum/configuration/samples/network-quorum-constellation.yaml
platforms/quorum/configuration/samples/network-quorum-newnode.yaml
platforms/quorum/configuration/samples/network-quorum-tessera.yaml
platforms/quorum/configuration/samples/network-quorum.yaml

**Changelog**
- Update network-schema.yaml to include quorum network schema definition
@pppazos
#1590

[quorum] add quorum schema definition

---

.github/workflows/docker_build.yml

**Changelog**
- Add git action to build baf-build image
@pppazos
#743

[shared] create git actions to build baf-build image and push to dockerhub

---

.github/workflows/molecule_test.yml
platforms/quorum/configuration/molecule/tessera/converge.yml
platforms/quorum/configuration/roles/create/crypto/raft/tasks/nested_main.yaml
platforms/quorum/configuration/roles/create/tessera/tasks/nested_enode_data.yaml

- Updated quorum molecule tests in git actions
- Updated molecule scenario files, as required.
#735

[quorum] Updated Quorum molecule tests in Git Actions

---

platforms/hyperledger-fabric/configuration/roles/create/k8s_secrets/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/shared/configuration/network-schema-validator.yaml

**Changelog**
- Fix secrets not getting created because of kubeconfig missed
- Fix creation of docker secret before the charts are created and not after
- Allow network schema errors to be printed always

[fabric] Fix vault_kubernetes errors

---

.github/workflows/chaincode_test.yml
.github/workflows/docker_build.yml
platforms/r3-corda/images/Dockerfile-corda-tls

Signed-off-by: pppazos <hgartti@gmail.com>
**Changelog**
- Update git workflow docker_build.yml to include build of corda images
@pppazos 
#741

[corda] build docker images

---

automation/Jenkinsfile
platforms/hyperledger-besu/configuration/roles/create/crypto/ethash/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/ibft/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/main.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-new-validatornode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-new-validatororg.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-newnode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml

**Changelog**
- Update default tessera version
- Update Besu binary paths

[besu] updated binary paths

---

platforms/hyperledger-besu/configuration/roles/create/k8_component/templates/gcp-storageclass.tpl
platforms/hyperledger-besu/configuration/roles/create/k8_component/vars/main.yaml

**Changelog**
- Add gcp-storageclass
- Update main.yml file to add an entry
@sownak 
#1295

[besu] added gcp-storageclass

---

platforms/quorum/charts/README.md
platforms/quorum/charts/crypto_ibft/Chart.yaml
platforms/quorum/charts/crypto_ibft/templates/job.yaml
platforms/quorum/charts/crypto_ibft/values.yaml
platforms/quorum/configuration/deploy-network.yaml
platforms/quorum/configuration/molecule/crypto-ibft/converge.yml
platforms/quorum/configuration/roles/create/crypto/ibft/tasks/nested_main.yaml
platforms/quorum/configuration/roles/create/genesis_nodekey/tasks/add_to_vault.yaml
platforms/quorum/configuration/roles/create/genesis_nodekey/tasks/main.yaml
platforms/quorum/configuration/roles/helm_component/templates/crypto_ibft_job.tpl
platforms/quorum/configuration/roles/helm_component/vars/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Added crypto_ibft helm chart for generating the crypto materials needed
- Updated some tasks from different roles in order to make it work
@sownak 
#1626

[quorum] Decoupling crypto/ibft role with crypto_ibft helm chart

---

docs/source/architectureref/certificates_path_list_quorum.md
docs/source/developer/besu-helmcharts.md

Signed-off-by: Khaneja <kaveri.khaneja@accenture.com>
**Changelog**
- Updated certificates and their paths in documentation.
@sownak @jagpreetsinghsasan @suvajit-sarkar 
#1637

[quorum] update certificate paths in documentation

---

.github/workflows/chaincode_test.yml

**Changelog**
- Add quorum smartcontract test on git actions
@pppazos
#740

[quorum] smc test on git actions

---

.github/workflows/chaincode_test.yml

**Changelog**
- Fix chaincode tests

[fabric] fix chaincode test

---

platforms/hyperledger-fabric/charts/ca_server/Chart.yaml
platforms/hyperledger-fabric/charts/ca_server/templates/job.yaml
platforms/hyperledger-fabric/charts/ca_server/values.yaml
platforms/hyperledger-fabric/configuration/molecule/crypto/converge.yml
platforms/hyperledger-fabric/configuration/molecule/crypto/prepare.yml
platforms/hyperledger-fabric/configuration/molecule/crypto/verify.yml
platforms/hyperledger-fabric/configuration/molecule/pre-vault-setup/converge.yml
platforms/hyperledger-fabric/configuration/molecule/pre-vault-setup/prepare.yml
platforms/hyperledger-fabric/configuration/molecule/pre-vault-setup/verify.yml
platforms/hyperledger-fabric/configuration/roles/create/ca-server/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/ca-server/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/k8s_secrets/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/k8s_secrets/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca_server_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/vars/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add ca_server chart
- Update create/k8s_secrets role and create/ca-server role
@alvaropicazo
#1573

[fabric] Ansible decoupling for create/ca-server role

---

platforms/hyperledger-besu/charts/node_besu/values.yaml
platforms/hyperledger-besu/charts/node_orion/values.yaml
platforms/hyperledger-besu/charts/node_tessera/values.yaml
platforms/hyperledger-besu/charts/node_validator/values.yaml
platforms/hyperledger-besu/configuration/add-validator.yaml
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/node_besu.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/node_orion.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/tessera.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/validator.tpl
platforms/hyperledger-besu/configuration/roles/create/ibft/tasks/nested_enode_data.yaml
platforms/hyperledger-besu/configuration/roles/create/validator/tasks/nested_enode_data.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-new-validatornode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-newnode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml
platforms/hyperledger-besu/configuration/samples/network-proxy-none.yaml

**Changelog**
- Add support for proxy = none
- Add sample for proxy = none (to be used for single kubernetes cluster)
resolves #1592

[besu] add support for proxy none

---

platforms/hyperledger-besu/configuration/samples/network-proxy-none.yaml

[besu] full format for internal url

---

platforms/r3-corda-ent/configuration/roles/create/certificates/cenm/README.md
platforms/r3-corda-ent/configuration/roles/delete/vault_secrets/README.md
platforms/r3-corda-ent/configuration/roles/setup/bridge/README.md
platforms/r3-corda-ent/configuration/roles/setup/credentials/README.md
platforms/r3-corda-ent/configuration/roles/setup/float-environment/tasks/README.md
platforms/r3-corda-ent/configuration/roles/setup/float/README.md
platforms/r3-corda-ent/configuration/roles/setup/node/README.md
platforms/r3-corda-ent/configuration/roles/setup/notary-initial-registration/README.md
platforms/r3-corda-ent/configuration/roles/setup/notary/README.md
platforms/r3-corda-ent/configuration/roles/update/nmap/Readme.md

Updated platform r3 corda-ent roles README.md files.
1624

[corda-ent] Updated platform r3 corda-ent roles README.md files.

---

platforms/quorum/charts/node_quorum/templates/deployment.yaml

[quorum] fixed quorum keystore password issue

---

examples/supplychain-app/charts/springbootwebserver/templates/deployment.yaml
examples/supplychain-app/configuration/roles/helm_component/templates/webserver.tpl

**Changelog**
- Update vault v2 for corda-os ref. app 
#1664

[corda]vaultv2 for corda-os ref. app

---

platforms/quorum/charts/crypto_ibft/templates/job.yaml
platforms/quorum/charts/crypto_ibft/values.yaml
platforms/quorum/charts/node_quorum/templates/deployment.yaml
platforms/quorum/charts/node_quorum_validator/templates/deployment.yaml

**Changelog**
- Fix `authpath` typo

[quorum] fixed authpath issue

---

platforms/network-schema.json

**Changelog**
- Fix network schema

[shared] Fix network-schema to allow null for loadbalanceraddress

---

examples/supplychain-app/corda/cordApps_springBoot/gradle.properties
platforms/r3-corda-ent/configuration/samples/network-addNotary.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml
platforms/r3-corda/configuration/samples/network-cordav2.yaml

**Changelog**
- Update sample nexus url

[chore] updated sample url

---

platforms/hyperledger-fabric/configuration/molecule/crypto/prepare.yml
platforms/hyperledger-fabric/configuration/molecule/orderer/prepare.yml
platforms/hyperledger-fabric/configuration/molecule/peer/prepare.yml
platforms/hyperledger-fabric/configuration/molecule/pre-vault-setup/prepare.yml
platforms/quorum/configuration/molecule/ambassador-certs/prepare.yml
platforms/quorum/configuration/molecule/constellation/prepare.yml
platforms/quorum/configuration/molecule/crypto-constellation/prepare.yml
platforms/quorum/configuration/molecule/crypto-ibft/prepare.yml
platforms/quorum/configuration/molecule/crypto-raft/prepare.yml
platforms/quorum/configuration/molecule/crypto-tessera/prepare.yml
platforms/quorum/configuration/molecule/tessera/prepare.yml
platforms/r3-corda/configuration/molecule/delete_node_flux_gitops/converge.yml
platforms/r3-corda/configuration/molecule/delete_notary/converge.yml
platforms/r3-corda/configuration/molecule/networkmap/prepare.yml
platforms/r3-corda/configuration/molecule/node/prepare.yml
platforms/r3-corda/configuration/molecule/notary/prepare.yml

Added secret v2 creation molecule 

---

platforms/hyperledger-fabric/configuration/molecule/crypto/prepare.yml
platforms/hyperledger-fabric/configuration/molecule/orderer/prepare.yml
platforms/hyperledger-fabric/configuration/molecule/peer/prepare.yml
platforms/hyperledger-fabric/configuration/molecule/pre-vault-setup/prepare.yml
platforms/quorum/configuration/molecule/ambassador-certs/prepare.yml
platforms/quorum/configuration/molecule/constellation/prepare.yml
platforms/quorum/configuration/molecule/crypto-constellation/prepare.yml
platforms/quorum/configuration/molecule/crypto-ibft/prepare.yml
platforms/quorum/configuration/molecule/crypto-raft/prepare.yml
platforms/quorum/configuration/molecule/crypto-tessera/prepare.yml
platforms/quorum/configuration/molecule/tessera/prepare.yml
platforms/r3-corda/configuration/molecule/delete_node_flux_gitops/converge.yml
platforms/r3-corda/configuration/molecule/delete_node_flux_gitops/prepare.yml
platforms/r3-corda/configuration/molecule/delete_notary/converge.yml
platforms/r3-corda/configuration/molecule/delete_notary/prepare.yml
platforms/r3-corda/configuration/molecule/networkmap/prepare.yml
platforms/r3-corda/configuration/molecule/node/prepare.yml
platforms/r3-corda/configuration/molecule/notary/prepare.yml

Fixed secrets path name for molecule test

---

platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/orderer.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/peer.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/peercheck.yaml
platforms/quorum/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/r3-corda-ent/configuration/roles/create/certificates/cenm/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/signer/tasks/main.yml
platforms/r3-corda/configuration/roles/create/certificates/ambassador/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/certificates/doorman/tasks/main.yaml

Added idempotence no test for req. tasks

---

platforms/hyperledger-fabric/configuration/molecule/peer/converge.yml
platforms/hyperledger-fabric/configuration/molecule/pre-vault-setup/prepare.yml
platforms/quorum/configuration/molecule/constellation/converge.yml
platforms/quorum/configuration/molecule/constellation/verify.yml
platforms/quorum/configuration/molecule/crypto-ibft/converge.yml
platforms/quorum/configuration/molecule/crypto-raft/converge.yml
platforms/quorum/configuration/molecule/crypto-raft/verify.yml
platforms/quorum/configuration/molecule/crypto-tessera/converge.yml
platforms/quorum/configuration/molecule/tessera/converge.yml
platforms/quorum/configuration/molecule/tessera/verify.yml
platforms/r3-corda/configuration/molecule/delete_node_flux_gitops/converge.yml
platforms/r3-corda/configuration/molecule/delete_node_flux_gitops/verify.yml
platforms/r3-corda/configuration/molecule/delete_notary/converge.yml
platforms/r3-corda/configuration/molecule/delete_notary/verify.yml

fixed molecule v2 paths and ref.

---

platforms/quorum/configuration/molecule/crypto-tessera/converge.yml
platforms/quorum/configuration/molecule/tessera/converge.yml
platforms/quorum/configuration/roles/create/tessera/tasks/member_main.yaml
platforms/quorum/configuration/roles/create/tessera/tasks/validator_main.yaml
platforms/r3-corda/configuration/molecule/notary/converge.yml

fixed typos and checks in molecule

---

platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/clique/Readme.md
platforms/hyperledger-besu/configuration/roles/create/crypto/clique/tasks/add_to_vault.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/clique/tasks/check_vault.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/clique/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/clique/tasks/node_data.yaml
platforms/hyperledger-besu/configuration/roles/create/crypto/clique/templates/cliqueConfigFile.tpl
platforms/hyperledger-besu/configuration/samples/network-proxy-none.yaml

Signed-off-by: roshan13046 <roshanpk.raut@gmail.com>
**Changelog**
- Added a new role for the clique consensus to generate a clique genesis file
- Updated deploy-network to include the option for generating crypto for the clique network and to deploy nodes for Clique consensus
@sownak 
#510

[besu] added clique consensus

---

docs/source/roadmap.rst

**Changelog**
- Update roadmap
#1668

update roadmap for post release v0.10.0

---

Dockerfile

**Changelog**
- Downloaded openjdk tar file and set up the JAVA_HOME
@suvajit-sarkar @sownak
Resolves #1711

[shared] resolved the openjdk-14 issue in baf-build

---

CODEOWNERS
MAINTAINERS.md

Add @weihong-ou as a committer and a code-owner.

Add Weihong as a maintainer

---

docs/pip-requirements.txt

**Changelog**
- Fix readthedocs build

[shared] Fix docutils so readthedocs don't fail

---

docs/source/architectureref/certificates_path_list_corda_ent.md
docs/source/architectureref/certificates_path_list_fabric.md
docs/source/architectureref/corda.md
docs/source/architectureref/hyperledger-fabric.md

Signed-off-by: Sownak Roy <sownak.roy@accenture.com>
**Changelog**
- Fix formatting error for docs

[shared] Fixed docs formatting

---

platforms/r3-corda-ent/images/enterprise-cenmcli1.5.0.dockerfile

**Changelog**
- Add cenm-cli docker file
@jagpreetsinghsasan @suvajit-sarkar @sownak 
#1545

[corda-ent] Added cenm-cli docker file

---

docs/source/operations/adding_new_member_org_besu.md
docs/source/operations/adding_new_org_quorum.md
docs/source/operations/quorum_networkyaml.md
examples/supplychain-app/configuration/samples/network-quorum-supplychain.yaml
platforms/quorum/charts/node_quorum_member/templates/deployment.yaml
platforms/quorum/configuration/deploy-network.yaml
platforms/quorum/configuration/molecule/tessera/converge.yml
platforms/quorum/configuration/roles/create/genesis_nodekey/tasks/validator_node_data.yaml
platforms/quorum/configuration/roles/create/genesis_raft/tasks/main.yaml
platforms/quorum/configuration/roles/create/genesis_raft/tasks/nested_validator_node_data.yaml
platforms/quorum/configuration/roles/create/genesis_raft/tasks/validator_node_data.yaml
platforms/quorum/configuration/roles/create/tessera/tasks/main.yaml
platforms/quorum/configuration/roles/create/tessera/tasks/validator_main.yaml
platforms/quorum/configuration/samples/network-minikube.yaml
platforms/quorum/configuration/samples/network-quorum-constellation.yaml
platforms/quorum/configuration/samples/network-quorum-newnode.yaml
platforms/quorum/configuration/samples/network-quorum-tessera.yaml
platforms/quorum/configuration/samples/network-quorum.yaml

**Changelog**
- Fix generic RAFT errors

[quorum] Fixed raft errors

---

platforms/r3-corda-ent/charts/gateway/Chart.yaml
platforms/r3-corda-ent/charts/gateway/files/gateway.conf
platforms/r3-corda-ent/charts/gateway/files/groups/network-maintainers.json
platforms/r3-corda-ent/charts/gateway/files/groups/network-operation-readers.json
platforms/r3-corda-ent/charts/gateway/files/groups/network-operators.json
platforms/r3-corda-ent/charts/gateway/files/roles/NetworkMaintainer.json
platforms/r3-corda-ent/charts/gateway/files/roles/NetworkOperationsReader.json
platforms/r3-corda-ent/charts/gateway/files/roles/NetworkOperator.json
platforms/r3-corda-ent/charts/gateway/files/setupAuth.sh
platforms/r3-corda-ent/charts/gateway/files/users/business-reader.json
platforms/r3-corda-ent/charts/gateway/files/users/network-maintainer.json
platforms/r3-corda-ent/charts/gateway/files/users/network-operator.json
platforms/r3-corda-ent/charts/gateway/templates/_helpers.tpl
platforms/r3-corda-ent/charts/gateway/templates/configmap.yaml
platforms/r3-corda-ent/charts/gateway/templates/deployment.yaml
platforms/r3-corda-ent/charts/gateway/templates/job.yaml
platforms/r3-corda-ent/charts/gateway/templates/pvc.yaml
platforms/r3-corda-ent/charts/gateway/templates/service.yaml
platforms/r3-corda-ent/charts/gateway/values.yaml

**Changelog**
- Add gateway chart
@sownak @jagpreetsinghsasan 
#1507

[ci skip] Added gateway chart

---

platforms/r3-corda-ent/charts/auth/Chart.yaml
platforms/r3-corda-ent/charts/auth/files/authservice.conf
platforms/r3-corda-ent/charts/auth/templates/_helpers.tpl
platforms/r3-corda-ent/charts/auth/templates/configmap.yaml
platforms/r3-corda-ent/charts/auth/templates/deployment.yaml
platforms/r3-corda-ent/charts/auth/templates/pvc.yaml
platforms/r3-corda-ent/charts/auth/templates/service.yaml
platforms/r3-corda-ent/charts/auth/values.yaml
platforms/r3-corda-ent/charts/generate-pki/templates/job.yaml

**Changelog**
- Add helm chart for auth service
- Update pki job to create auth trust store
**TODO**
Creds for the crypto materials needs to fetch vault and replaced
JWT creation can be moved to PKI job
@sownak @jagpreetsinghsasan 
#1506

[skip ci] Added auth chart

---

platforms/r3-corda-ent/charts/zone/Chart.yaml
platforms/r3-corda-ent/charts/zone/files/run.sh
platforms/r3-corda-ent/charts/zone/templates/_helpers.tpl
platforms/r3-corda-ent/charts/zone/templates/configmap.yaml
platforms/r3-corda-ent/charts/zone/templates/deployment.yaml
platforms/r3-corda-ent/charts/zone/templates/pvc.yaml
platforms/r3-corda-ent/charts/zone/templates/service.yaml
platforms/r3-corda-ent/charts/zone/values.yaml
platforms/r3-corda-ent/images/enterprise-zone1.5.1.dockerfile

**Changelog**
- Add helm chart and dockerfile for CENM Zone service
#1735

[corda-ent] Added the helm chart and dockerfile for CENM Zone service

---

platforms/r3-corda-ent/charts/zone/templates/deployment.yaml
platforms/r3-corda-ent/charts/zone/values.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/zone.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/cenm/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/zone/README.md
platforms/r3-corda-ent/configuration/roles/setup/zone/tasks/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add ansible role for automation of CENM zone service
- Update cenm role to trigger zone service
#1743

[corda-ent] Added ansible role for automation of zone service

---

platforms/r3-corda-ent/charts/gateway/files/gateway.conf
platforms/r3-corda-ent/charts/gateway/templates/deployment.yaml
platforms/r3-corda-ent/charts/gateway/values.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/gateway.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/cenm/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/gateway/README.md
platforms/r3-corda-ent/configuration/roles/setup/gateway/tasks/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

Signed-off-by: nikhilagolla <nikhila.golla@accenture.com>
**Changelog**
- Add Ansible Role and tpl file for automation of gateway service.
@sownak @jagpreetsinghsasan @suvajit-sarkar 
#1734

[corda-ent] Added Ansible Role and tpl file for automation of gateway service.

---

platforms/r3-corda-ent/charts/gateway/files/gateway.conf
platforms/r3-corda-ent/charts/gateway/templates/deployment.yaml
platforms/r3-corda-ent/charts/gateway/values.yaml
platforms/r3-corda-ent/charts/zone/files/run.sh
platforms/r3-corda-ent/charts/zone/templates/deployment.yaml
platforms/r3-corda-ent/charts/zone/values.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/gateway.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/zone.tpl

Signed-off-by: nikhilagolla <nikhila.golla@accenture.com>
**Changelog**  
- Fix hard coded credentials from gateway and Zone charts.
#1753

[corda-ent] Removed hard coded credentials from gateway and Zone charts

---

platforms/hyperledger-indy/charts/indy-key-mgmt/templates/job.yaml

**Changelog**
- Fix Key management error because of curl not getting installed

[indy] Fix key-mgmt execution error

---

platforms/shared/configuration/roles/setup/Readme.md

**Changelog**
- Fixed a typographical error in a README file.
@sownak @jagpreetsinghsasan @suvajit-sarkar

fixed typo in shared role setup README

---

docs/source/operations/setting_dlt.md

What were originally html doc files were changed to md at some point. Updated the links to reflect

Some links in setting_dlt.md are broken

---

docs/source/operations/setting_dlt.md

Reverts hyperledger/bevel#1783
This PR fixes the links in GitHub view, but breaks the link in readthedocs. Reverting this merge as priority on docs is readthedocs view.
Solution should work in readthedocs view

Revert "Some links in setting_dlt.md are broken"

---

platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml
platforms/hyperledger-fabric/charts/orderernode/values.yaml
platforms/hyperledger-fabric/charts/peernode/templates/deployment.yaml
platforms/hyperledger-fabric/charts/peernode/values.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/orderernode.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/value_peer.tpl

**Changelog**
- Add logic to request and limit resources of pods through helm release files
#1770

[fabric] Request resources through helm release files

---

platforms/r3-corda/charts/node-initial-registration/templates/job.yaml
platforms/r3-corda/charts/node-initial-registration/values.yaml
platforms/r3-corda/charts/notary-initial-registration/templates/job.yaml
platforms/r3-corda/charts/notary-initial-registration/values.yaml
platforms/r3-corda/configuration/roles/create/node_component/templates/job.tpl
platforms/r3-corda/configuration/roles/create/node_component/templates/node.tpl

Signed-off-by: nikhilayadav <nikhila.golla@accenture.com>
**Changelog**
- Add logic to check crypto materials in vault 
#1760

[corda]Ensure successful storage of crypto materials

---

platforms/hyperledger-indy/charts/indy-key-mgmt/templates/job.yaml
platforms/hyperledger-indy/charts/indy-key-mgmt/values.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/crypto/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/crypto/templates/crypto-generate.tpl

**Changelog**
- Add logic to check storage to crypto materials in vault
#1763

[indy] Ensure successful storage of crypto materials in vault

---

CONTRIBUTING.md

Signed-off-by: Tracy Kuhrt <tracy.a.kuhrt@accenture.com>
**Changelog**
- Fix #1801 - Developer Guide link
@tkuhrt 
#1801

[docs] Fixes #1801

---

.github/workflows/docker_build.yml

**Changelog**
- Updated the docker_build.yml Bevel and Corda jobs to now push to ghcr.io instead of DockerHub.
#1780

Changed docker_build workflow to push to ghcr

---

docs/source/operations/adding_new_validator_node_besu.md
docs/source/operations/adding_new_validator_org_besu.md
docs/source/operations/besu_networkyaml.md
platforms/hyperledger-besu/charts/node_tessera/templates/configmap.yaml
platforms/hyperledger-besu/charts/node_tessera/templates/deployment.yaml
platforms/hyperledger-besu/charts/tessera_key_mgmt/templates/job.yaml
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/crypto_tessera.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/tessera.tpl
platforms/hyperledger-besu/configuration/samples/network-besu-new-memberorg.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-new-validatornode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu-new-validatororg.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml
platforms/hyperledger-besu/configuration/samples/network-proxy-none.yaml
platforms/network-schema.json

**Changelog**
- Fix log4j vulnerability 
- Update Besu and Tessera version to 21.10.6 and 21.7.3
- Update tessera config to use hashicorp vault natively
#1795

[besu] Besu and Tessera version upgrade

---

platforms/hyperledger-fabric/charts/catools/templates/configmap.yaml
platforms/hyperledger-fabric/charts/catools/templates/deployment.yaml
platforms/hyperledger-fabric/charts/catools/values.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-tools.tpl
platforms/shared/configuration/roles/check/setup/tasks/main.yaml

**Changelog**
- add in ca-tools chart logic to check the storage of cryptographic materials in the vault
- add a new role check/crypto_materials
#1761

[fabric] Ensure successful storage of crypto materials in vault

---

Dockerfile
docs/source/developer/bevel_minikube_setup.md

**Changelog**
- Fix link issue in docs

[docs] fixed a link issue in docs

---

.github/workflows/chaincode_test.yml
.github/workflows/corda_images_build.yml
.github/workflows/molecule_test.yml
.github/workflows/networkschema_test.yml
.github/workflows/quorum_images_build.yml

**Changelog**
- Add separate workflow file for Corda and Quorum
- Update docker build 
- Rename the workflows

[shared] separate workflow files for images

---

docs/source/roadmap.rst

**Changelog**
- Update roadmap

[docs] updated roadmap

---

Dockerfile
Dockerfile.jdk8
docs/source/developer/dev_prereq.md
docs/source/faq.md
docs/source/prerequisites.md

**Changelog**
- Fix versions in documentation

[skip ci] Updated versions in docs

---

examples/supplychain-app/fabric/chaincode_rest_server/rest-server/package.json
examples/supplychain-app/fabric/chaincode_rest_server/rest-server/yarn.lock

**Changelog**
- Fix Fabric restserver build

[skip ci] Fix Fabric restserver build

---

platforms/hyperledger-besu/charts/orion_key_mgmt/templates/job.yaml
platforms/hyperledger-besu/charts/orion_key_mgmt/values.yaml
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/crypto_orion.tpl
platforms/quorum/charts/crypto_ibft/templates/job.yaml
platforms/quorum/charts/crypto_ibft/values.yaml
platforms/quorum/configuration/roles/helm_component/templates/crypto_ibft_job.tpl

**Changelog**
- Add logic to check crypto materials in vault
#1762

[quorum][besu]check and ensure that the store certs are successfully storing the crypto materials

---

docs/source/roadmap.rst

Signed-off-by: suvajit sarkar <suvajit.sarkar@accenture.com>

[docs] Update roadmap

---

platforms/hyperledger-besu/charts/generate_ambassador_certs/Chart.yaml
platforms/hyperledger-besu/charts/generate_ambassador_certs/templates/job.yaml
platforms/hyperledger-besu/charts/generate_ambassador_certs/values.yaml
platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/Readme.md
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/ambassador_besu.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/node_besu.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/node_orion.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/validator.tpl
platforms/hyperledger-besu/configuration/roles/create/k8s_secrets/Readme.md
platforms/hyperledger-besu/configuration/roles/create/k8s_secrets/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
-Add generate_ambassador_certs chart and create/k8s_secrets role
-Update delete/vault_secret and create/certificates/ambassador roles
#1851

[besu] Ansible decoupling of create/certificates/ambassador role

---

platforms/hyperledger-fabric/charts/ca/templates/deployment.yaml
platforms/hyperledger-fabric/charts/operations_console/templates/deployment.yaml
platforms/hyperledger-fabric/charts/orderernode/templates/deployment.yaml
platforms/hyperledger-fabric/charts/peernode/templates/deployment.yaml
platforms/hyperledger-fabric/charts/zkkafka/templates/deployment.yaml

**Changelog**
- Update ca, operations_console, orderernode, zkkafka, peernode charts. Added or changed field, imagePullPolicy: IfNotPresent
#1882

[fabric] Change or add ImagePullPolicy to be IfNotPresent

---

platforms/hyperledger-besu/charts/node_besu/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_orion/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_tessera/templates/deployment.yaml
platforms/hyperledger-besu/charts/node_validator/templates/deployment.yaml

**Changelog**
- Update node_besu, node_orion, node_tessera, node_validator charts. Added or changed field, imagePullPolicy: IfNotPresent
#1884

[besu] Change or add ImagePullPolicy to be IfNotPresent

---

platforms/quorum/charts/node_constellation/templates/deployment.yaml
platforms/quorum/charts/node_quorum/templates/deployment.yaml
platforms/quorum/charts/node_quorum_member/templates/deployment.yaml
platforms/quorum/charts/node_quorum_validator/templates/deployment.yaml
platforms/quorum/charts/node_tessera/templates/deployment.yaml

**Changelog**
- Update node_constellacion, node_quorum, node_quorum_member, node_quorum_validator and node_tessera
charts. Added or changed field, imagePullPolicy: IfNotPresent
#1883

[quorum] Change or add ImagePullPolicy to be IfNotPresent

---

platforms/hyperledger-fabric/charts/invoke_chaincode/templates/invoke_chaincode.yaml
platforms/hyperledger-fabric/charts/invoke_chaincode/values.yaml
platforms/hyperledger-fabric/configuration/roles/create/channel_artifacts/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/invoke_chaincode_job.tpl

**Changelog**
- Fix vault secret path hard coded in some roles and chart

[fabric] fixed vault secret path hardcoding issues

---

platforms/quorum/charts/certs-ambassador-quorum/Chart.yaml
platforms/quorum/charts/certs-ambassador-quorum/templates/_helpers.tpl
platforms/quorum/charts/certs-ambassador-quorum/templates/configmap.yaml
platforms/quorum/charts/certs-ambassador-quorum/templates/job.yaml
platforms/quorum/charts/certs-ambassador-quorum/values.yaml
platforms/quorum/configuration/deploy-network.yaml
platforms/quorum/configuration/molecule/ambassador-certs/converge.yml
platforms/quorum/configuration/molecule/ambassador-certs/verify.yml
platforms/quorum/configuration/roles/create/certificates/ambassador/Readme.md
platforms/quorum/configuration/roles/create/certificates/ambassador/tasks/main.yaml
platforms/quorum/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/quorum/configuration/roles/create/k8s_secrets/tasks/main.yaml
platforms/quorum/configuration/roles/create/tessera/tasks/validator_main.yaml
platforms/quorum/configuration/roles/helm_component/templates/certs-ambassador-quorum.tpl
platforms/quorum/configuration/roles/helm_component/vars/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add Ansible decoupling  of create/certificates/ambassador role
#1854

[quorum] ansible decoupling  of create/certificates/ambassador role

---

platforms/hyperledger-fabric/charts/commit_chaincode/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/charts/commit_chaincode/values.yaml
platforms/hyperledger-fabric/charts/invoke_chaincode/templates/invoke_chaincode.yaml
platforms/hyperledger-fabric/configuration/add-organization.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/commit/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/k8s_secrets/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/commit_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/invoke_chaincode_job.tpl

**Changelog**
- Fix configuration/add-organization.yaml
- Update charts/invoke_chaincode/templates/invoke_chaincode.yaml
#1932

[fabric] add-organization file fix

---

platforms/hyperledger-fabric/configuration/roles/create/configtx/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrderer_default.tpl
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxProfile_default.tpl

**Changelog**
- Fix configtxOrderer_default.tpl and configtxProfile_default.tpl in create/configtx role
#1907

[fabric] Fix EtcdRaft.Consenters.Port generated

---

docs/source/architectureref/certificates_path_list_quorum.md

**Changelog**
- Update
- docs(quorum): update the readme bugs
#1886

[quorum] docs: update the readme bugs

---

examples/supplychain-app/besu/express_nodeJS/package-lock.json
examples/supplychain-app/corda/express_nodeJS/package-lock.json
examples/supplychain-app/fabric/chaincode_rest_server/rest-server/yarn.lock
examples/supplychain-app/fabric/express_nodeJs/package-lock.json
examples/supplychain-app/quorum/express_nodeJS/package-lock.json
examples/supplychain-app/quorum/smartContracts/package-lock.json
examples/supplychain-app/supplychain-frontend/package-lock.json
platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/write.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/k8s_secrets/tasks/main.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-kafka.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/hyperledger-fabric/configuration/samples/network-proxy-none.yaml
platforms/r3-corda/images/doorman/pom.xml
platforms/r3-corda/images/doorman/website/package-lock.json
platforms/r3-corda/images/networkmap/pom.xml
platforms/r3-corda/images/networkmap/website/package-lock.json

**Changelog**
- Update sample network.yamls for Fabic
- Fix install chaincode usage of git token

[fabric] Fix install chaincode errors

---

platforms/r3-corda/images/doorman/website/package-lock.json
platforms/r3-corda/images/networkmap/website/package-lock.json

**Changelog**
- Update package-lock.json file for networkmap website

[chore] updated package-lock.json file for corda images

---

platforms/r3-corda/images/doorman/website/package-lock.json
platforms/r3-corda/images/doorman/website/package.json
platforms/r3-corda/images/networkmap/website/package-lock.json

**Changelog**
- Add
- Fix
- Update
#issue_number

[chore]Develop

---

platforms/hyperledger-fabric/charts/catools/templates/configmap.yaml
platforms/hyperledger-fabric/charts/catools/templates/deployment.yaml
platforms/hyperledger-fabric/configuration/add-orderer.yaml
platforms/hyperledger-fabric/configuration/add-peer.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/users/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-tools.tpl

**Changelog**
- Update platforms/hyperledger-fabric/configuration/add-orderer.yaml and platforms/hyperledger-fabric/configuration/add-peer.yaml: 

[fabric]  Add orderer/peer update

---

platforms/hyperledger-indy/charts/indy-auth-job/templates/job.yaml
platforms/hyperledger-indy/charts/indy-key-mgmt/templates/job.yaml
platforms/hyperledger-indy/charts/indy-node/templates/statefulset.yaml

- Update image pull policy to IfNotPresent
#1885

[indy] update image pull policy

---

platforms/hyperledger-fabric/configuration/molecule/crypto/converge.yml
platforms/hyperledger-fabric/configuration/molecule/pre-vault-setup/converge.yml

**Changelog**
- Fix missing variable in converge.yaml

[fabric][quorum] molecule fix

---

README.md

**Changelog**
Just defined what the  Distributed Ledger Technology means before the initialism is used. Makes reading the docs easier for nubes like me :)

Define what DLT is before the initialism is used

---

examples/supplychain-app/charts/expressapp-quorum/templates/deployment.yaml
examples/supplychain-app/charts/frontend/templates/deployment.yaml
examples/supplychain-app/configuration/roles/helm_component/templates/expressapi-quorum.tpl
examples/supplychain-app/configuration/roles/helm_component/templates/frontend.tpl
platforms/quorum/charts/node_constellation/templates/service.yaml
platforms/quorum/charts/node_quorum/templates/service.yaml
platforms/quorum/charts/node_quorum_member/templates/service.yaml
platforms/quorum/charts/node_quorum_validator/templates/service.yaml
platforms/quorum/charts/node_tessera/templates/service.yaml
platforms/quorum/configuration/README.md
platforms/quorum/configuration/reset-network.yaml
platforms/quorum/configuration/roles/delete/flux_releases/Readme.md
platforms/quorum/configuration/roles/delete/flux_releases/tasks/main.yaml
platforms/quorum/configuration/roles/delete/gitops_files/tasks/main.yaml
platforms/quorum/configuration/roles/helm_component/templates/certs-ambassador-quorum.tpl
platforms/quorum/configuration/roles/helm_component/templates/constellation.tpl
platforms/quorum/configuration/roles/helm_component/templates/crypto_ibft_job.tpl
platforms/quorum/configuration/roles/helm_component/templates/crypto_tessera.tpl
platforms/quorum/configuration/roles/helm_component/templates/memberquorum.tpl
platforms/quorum/configuration/roles/helm_component/templates/quorum.tpl
platforms/quorum/configuration/roles/helm_component/templates/tessera.tpl
platforms/quorum/configuration/roles/helm_component/templates/validatorquorum.tpl
platforms/quorum/configuration/samples/network-quorum.yaml
platforms/shared/configuration/roles/create/shared_helm_component/templates/vault_kubernetes_job.tpl

**Changelog**
- Update  quorum helm value templates for flux v2.
#1928

[quorum] update quorum helm value templates for flux v2

---

.github/workflows/chaincode_test.yml
.github/workflows/molecule_test.yml
.github/workflows/networkschema_test.yml
Dockerfile
Dockerfile.jdk8
docs/source/prerequisites_machine.md

**Changelog**
- Version upgrades
- python 3.8
- ansible [core 2.12.6]
- openshift 0.13.1
- Updated docs with version change
- Updated bevel-build docker images
#1951

[shared] python, ansible, openshift version upgrade

---

examples/supplychain-app/configuration/roles/create/corda/frontend/tasks/main.yaml
examples/supplychain-app/configuration/roles/create/fabric/frontend/tasks/main.yaml
examples/supplychain-app/configuration/roles/create/quorum/frontend/tasks/main.yaml

**Changelog**
- Update k8s_facts to k8s_info because in more updated versions of ansible the error shown in the screenshot occurred
@suvajit-sarkar @jagpreetsinghsasan

[chore] Update k8s_facts to k8s_info

---

examples/supplychain-app/configuration/roles/create/corda/expressapi/vars/main.yaml
examples/supplychain-app/configuration/roles/create/corda/frontend/tasks/main.yaml
examples/supplychain-app/configuration/roles/create/corda/webserver/vars/main.yaml
examples/supplychain-app/configuration/roles/create/fabric/frontend/tasks/main.yaml
examples/supplychain-app/configuration/roles/create/quorum/frontend/tasks/main.yaml
examples/supplychain-app/configuration/roles/helm_component/templates/expressapi.tpl
examples/supplychain-app/configuration/roles/helm_component/templates/webserver.tpl
examples/supplychain-app/configuration/samples/network-cordav2.yaml
platforms/r3-corda/charts/doorman-tls/templates/service.yaml
platforms/r3-corda/charts/nms-tls/templates/service.yaml
platforms/r3-corda/configuration/reset-network.yaml
platforms/r3-corda/configuration/roles/create/k8_component/templates/create_doorman.tpl
platforms/r3-corda/configuration/roles/create/k8_component/templates/create_mongodb.tpl
platforms/r3-corda/configuration/roles/create/k8_component/templates/network_map.tpl
platforms/r3-corda/configuration/roles/create/node_component/templates/h2.tpl
platforms/r3-corda/configuration/roles/create/node_component/templates/job.tpl
platforms/r3-corda/configuration/roles/create/node_component/templates/node.tpl
platforms/r3-corda/configuration/samples/network-cordav2.yaml

**Changelog**
- Update corda tpl for flux v2
- Update Update k8s_facts to k8s_info
@suvajit-sarkar @jagpreetsinghsasan 
#1971

[corda] Update Corda helm value templates for flux v2

---

platforms/hyperledger-fabric/configuration/roles/create/storageclass/templates/gcp_sc.tpl
platforms/hyperledger-fabric/configuration/roles/create/storageclass/vars/main.yaml

**Changelog**
- Add GCP storageclass template for Fabric

[fabric] Added support for gcp

---

platforms/r3-corda-ent/configuration/reset-network.yaml
platforms/r3-corda-ent/configuration/roles/delete/gitops_files/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/auth.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/bridge.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/db.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/float.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/gateway.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/idman.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/nmap.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node_registration.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary_initial_registration.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/pki-generator-node.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/pki-generator.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/signer.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/zone.tpl

**Changelog**
- Update platform r3 corda-ent helm value templates for fluxv2
#1972

[corda]: update platform r3 corda-ent helm value templates for fluxv2

---

examples/identity-app/configuration/roles/create/helm_component/templates/employer.tpl
examples/identity-app/configuration/roles/create/helm_component/templates/university.tpl
examples/identity-app/configuration/roles/create/helm_component/templates/webserver.tpl
platforms/hyperledger-indy/configuration/cleanup.yaml
platforms/hyperledger-indy/configuration/roles/clean/flux/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/clean/gitops/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/auth_job/templates/auth_job.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/crypto/templates/crypto-generate.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/domain_genesis/templates/domain_genesis.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/ledger_txn/templates/ledger-txn.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/node/templates/node.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/pool_genesis/templates/pool_genesis.tpl

**Changelog**
- Update platform indy helm value templates for flux v2
#1984

[indy]: update platform indy helm value templates for flux v2

---

docs/source/prerequisites.md
platforms/hyperledger-besu/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl
platforms/hyperledger-fabric/charts/vault_kubernetes/templates/job.yaml
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/reviewer_rbac.tpl
platforms/hyperledger-indy/configuration/roles/create/k8_component/templates/admin_cluster_role_binding.tpl
platforms/hyperledger-indy/configuration/roles/create/k8_component/templates/cluster_role_binding.tpl
platforms/hyperledger-indy/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/quorum/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl
platforms/r3-corda-ent/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl
platforms/r3-corda-ent/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl
platforms/r3-corda/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/shared/charts/vault-k8s-mgmt/templates/job.yaml
platforms/shared/configuration/molecule/kubernetes-corda/converge.yml
platforms/shared/configuration/molecule/kubernetes-fabric/converge.yml
platforms/shared/configuration/molecule/kubernetes-indy/converge.yml
platforms/shared/configuration/roles/setup/flux/tasks/main.yaml

**Changelog**
- Update changes for k8s 1.21
#1715

[chore] k8s 1.21 updates

---

platforms/shared/configuration/roles/create/shared_helm_component/tasks/main.yaml
platforms/shared/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

[shared] Fix playbook_dir typo

---

platforms/shared/configuration/molecule/kubernetes-corda/converge.yml
platforms/shared/configuration/molecule/kubernetes-corda/verify.yml
platforms/shared/configuration/molecule/kubernetes-fabric/converge.yml
platforms/shared/configuration/molecule/kubernetes-fabric/verify.yml
platforms/shared/configuration/molecule/kubernetes-indy/converge.yml
platforms/shared/configuration/molecule/kubernetes-indy/verify.yml
platforms/shared/configuration/roles/create/shared_helm_component/tasks/main.yaml
platforms/shared/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

**Changelog**
- Removed molecule test for flux v2 installation
- Fix playbook_dir typo

[chore] Hotfix merges from develop

---

platforms/r3-corda/images/doorman/pom.xml
platforms/r3-corda/images/doorman/src/main/kotlin/com/acn/dlt/corda/doorman/utils/Options.kt

**Changelog**
- Add fix for kotlin v1.6.0 fix doorman build

[chore] doorman build fix on kotlin v1.6.0

---

.github/workflows/molecule_test.yml
platforms/quorum/charts/crypto_raft/Chart.yaml
platforms/quorum/charts/crypto_raft/templates/job.yaml
platforms/quorum/charts/crypto_raft/values.yaml
platforms/quorum/configuration/molecule/crypto-raft/converge.yml
platforms/quorum/configuration/molecule/crypto-raft/verify.yml
platforms/quorum/configuration/roles/create/crypto/raft/tasks/nested_main.yaml
platforms/quorum/configuration/roles/helm_component/templates/crypto_raft_job.tpl
platforms/quorum/configuration/roles/helm_component/vars/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

**Changelog**
- Add ansible decoupling raft crypto creation
#1835

[quorum] ansible decoupling raft crypto creation

---

platforms/hyperledger-besu/configuration/reset-network.yaml
platforms/hyperledger-fabric/configuration/reset-network.yaml
platforms/hyperledger-indy/configuration/cleanup.yaml
platforms/quorum/configuration/reset-network.yaml
platforms/r3-corda-ent/configuration/reset-network.yaml
platforms/r3-corda/configuration/reset-network.yaml

**Changelog**
- Fix absolute path for flux cli in reset network playbooks

[shared] added absolute path for the flux cli

---

docs/source/operations/refresh_certs_fabric.md
examples/supplychain-app/configuration/roles/create/fabric/expressapi/tasks/main.yaml
examples/supplychain-app/configuration/roles/helm_component/templates/restserver.tpl
examples/supplychain-app/configuration/roles/helm_component/templates/webserver-cordaent.tpl
examples/supplychain-app/configuration/samples/network-fabricv2.yaml
platforms/hyperledger-fabric/charts/catools/templates/configmap.yaml
platforms/hyperledger-fabric/charts/fabric_cli/templates/deployment.yaml
platforms/hyperledger-fabric/configuration/refresh_certificates.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/delete_old_certs.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/delete_old_certs.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/cli_pod/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/orderers/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/orderers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/peers/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/get_update_block.yaml
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/nested_main.yaml
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/templates/update_consenter_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/vars/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/fetch_old_cert/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/fetch_old_cert/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/reset_pod/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/reset_pod/tasks/main.yaml

**Changelog**
- Add the operation to refresh the certificates
- Fix image names and variable names in examples/supplychain-app/configuration/roles/create/fabric/expressapi/tasks/main.yaml, examples/supplychain-app/configuration/roles/helm_component/templates/restserver.tpl and examples/ supplychain-app/configuration/roles/helm_component/templates/webserver-cordaent.tpl for supplychain deployment to work with ghcr.io/hyperledger
The certificate rotation process has been carried out using this guide:
https://medium.com/coinmonks/certification-rotation-in-hyperledger-fabric-c9eb5fc68dec
@suvajit-sarkar @jagpreetsinghsasan 
#1429

[fabric] Certificate refresh

---

platforms/quorum/configuration/deploy-network.yaml

**Changelog**
- Fix raft consensus role
#issue_number

[quorum] raft consensus role fix

---

examples/identity-app/charts/acme/templates/statefulset.yaml
examples/identity-app/charts/alice/templates/statefulset.yaml
examples/identity-app/charts/faber/templates/statefulset.yaml
examples/identity-app/charts/webserver/templates/statefulset.yaml
platforms/hyperledger-indy/charts/indy-auth-job/templates/job.yaml

**Changelog**
- Updated image pull policy to IfNotPresent
- Disabled iss validation for vault auth

[indy] image pull policy and iss validation update

---

.github/workflows/corDapps_jar_build.yaml
.github/workflows/corda_images_build.yml
platforms/r3-corda/configuration/molecule/delete_node_flux_gitops/converge.yml
platforms/r3-corda/configuration/molecule/networkmap/converge.yml
platforms/r3-corda/configuration/molecule/node/converge.yml

**Changelog**
- Fix image build workflow failing with conflict error
#2008

[corda] image build workflow failing with conflict error

---

platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/nested_orderers.yaml
platforms/hyperledger-fabric/configuration/roles/delete/flux_releases/tasks/main.yaml

**Changelog**
- Fix issues related to helmrelease deletion
- Issues for copying orderer certs locally

[fabric] Fix getting orderer certs

---

docs/source/MAINTAINERS.md

Make into a pointer, like Cactus
Signed-off-by: Ry Jones <ry@linux.com>

[chore] Update MAINTAINERS.md

---

platforms/hyperledger-fabric/configuration/add-new-organization.yaml
platforms/hyperledger-fabric/configuration/add-orderer.yaml
platforms/hyperledger-fabric/configuration/remove-organization.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/appchannel/tasks/nested_main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/syschannel/tasks/nested_main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/gitops_files/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/existing_peer_cli.tpl
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/orderer_cli.tpl

**Changelog**
- Add remove_org variable in the remove-organization.yaml playbook, to avoid removing the flux mainfest when an organization is removed 
- Fix fabric operations: add_organization,remove_organization, add_peer, add_orderer, add_new_channel
@jagpreetsinghsasan @sownak  @suvajit-sarkar 
#1874

[fabric] Update operations

---

platforms/hyperledger-besu/configuration/reset-network.yaml
platforms/hyperledger-fabric/configuration/reset-network.yaml
platforms/hyperledger-indy/configuration/cleanup.yaml
platforms/quorum/configuration/reset-network.yaml
platforms/r3-corda-ent/configuration/reset-network.yaml
platforms/r3-corda/configuration/reset-network.yaml

**Changelog**
- Fix syntax error in reset-network playbooks
@suvajit-sarkar @jagpreetsinghsasan @sownak

[shared] Fix syntax error

---

docs/source/MAINTAINERS.md
platforms/hyperledger-besu/configuration/reset-network.yaml
platforms/hyperledger-fabric/configuration/reset-network.yaml
platforms/hyperledger-indy/configuration/cleanup.yaml
platforms/quorum/configuration/reset-network.yaml
platforms/r3-corda-ent/configuration/reset-network.yaml
platforms/r3-corda/configuration/reset-network.yaml

**Changelog**
- Add
- Fix
- Update
#issue_number

[chore] latest develop

---

platforms/hyperledger-besu/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/quorum/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/shared/configuration/roles/create/shared_helm_component/templates/vault_kubernetes_job.tpl

Signed-off-by: vishaalreddy <t.vishal.reddy@accenture.com>
**Changelog**
- Update : Updated to delete vault policy for (Besu ,quorum &  r3 corda)
@suvajit-sarkar @sownak

[shared] Updated to delete vault policy

---

.github/workflows/molecule_test.yml
platforms/hyperledger-besu/configuration/reset-network.yaml
platforms/hyperledger-fabric/configuration/reset-network.yaml
platforms/hyperledger-indy/configuration/cleanup.yaml
platforms/quorum/configuration/reset-network.yaml
platforms/quorum/configuration/samples/network-quorum-constellation.yaml
platforms/quorum/configuration/samples/network-quorum-newnode.yaml
platforms/quorum/configuration/samples/network-quorum-tessera.yaml
platforms/quorum/configuration/samples/network-quorum.yaml
platforms/r3-corda-ent/configuration/reset-network.yaml
platforms/r3-corda/configuration/reset-network.yaml

**Changelog**
- Update the lock var description
- Fix lint error in molecules test
@jagpreetsinghsasan  @suvajit-sarkar @sownak 
#2086

[ci-skip] Update the lock var description

---

platforms/hyperledger-besu/charts/generate_ambassador_certs/templates/job.yaml
platforms/hyperledger-besu/charts/node_tessera/templates/deployment.yaml
platforms/hyperledger-besu/charts/tessera_key_mgmt/templates/job.yaml
platforms/hyperledger-besu/charts/tessera_key_mgmt/values.yaml
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/crypto_tessera.tpl
platforms/shared/charts/vault-k8s-mgmt/templates/job.yaml
platforms/shared/images/alpine-utils.Dockerfile

Signed-off-by: adityajoshi12 <adityaprakashjoshi1@gmail.com>
**Changelog**
- Updated the charts to remove dependency of tools like jq, curl and openssl
- Added utility binaries to apline container image
#2073

[besu] refactoring charts to removing dependency on external tools and artifacts

---

.github/pull_request_template.md

feat(docs): update PR template
---------------
1. Updated .github/pull_request_template.md
Results from changes done in 1)
a. Removed reviewed_by field as github can track that information
b. Added fixes tag for auto-linking to the issue
Fixes hyperledger#2102

[ci-skip]feat(docs): update PR template

---

.github/workflows/img_bevel_alpine.yaml
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/ambassador_besu.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/crypto_tessera.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/node_besu.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/node_orion.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/tessera.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/validator.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/vars/main.yaml
platforms/shared/images/bevel-alpine-ext.Dockerfile
platforms/shared/images/bevel-alpine.Dockerfile

**Changelog**
- Renamed alpine-utils to bevel-alpine
- Added new bevel-alpine-ext img with mysql connector
- modified workflow to build and push the new bevel-apline images
- modified besu code to use the new images

[besu] alpine utils image changes

---

.github/workflows/besu_expressapi.yaml
examples/supplychain-app/besu/express_nodeJS/Dockerfile

**Changelog**
Added the workflow for bevel-supplychain-besu:express-app-latest 
.github/workflows/besu_expressapi.yaml
Updated examples/supplychain-app/besu/express_nodeJS/Dockerfile
@jagpreetsinghsasan @suvajit @sownak 
Linked issue
#2139

[besu] Add supplychain besu workflow

---

platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/crypto_tessera.tpl
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/tessera.tpl

**Changelog**
- Fix tpl syntax error and wrong image

[besu] hot fixes 

---

platforms/hyperledger-besu/configuration/roles/create/genesis/ibft/tasks/main.yaml

[besu] Deploy supplychain smart contract for IBFT
- Update platforms/hyperledger-besu/configuration/roles/create/genesis/ibft role
Fixes #2174
---

[besu] Deploy supplychain smart contract for IBFT

---

platforms/hyperledger-indy/configuration/roles/create/helm_component/crypto/templates/crypto-generate.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/ledger_txn/templates/ledger-txn.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/node/templates/node.tpl
platforms/hyperledger-indy/images/indy-key-mgmt/README.md
platforms/hyperledger-indy/images/indy-node/README.md
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

change indy image names in code to match with ghcr.io
- Update indy image names
Fixes #2188

[indy] change indy image names in code to match with ghcr.io

---

platforms/hyperledger-besu/configuration/roles/delete/gitrepositories/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/delete/kustomization/tasks/main.yaml

bug(besu): add resource checks to reset.yaml  
Added resource checks for the following K8s resources:
1. Gitrepositories
2. Kustomizations

[besu] add resource checks to reset.yaml

---

platforms/quorum/configuration/reset-network.yaml
platforms/quorum/configuration/roles/delete/clusterrole/tasks/main.yaml
platforms/quorum/configuration/roles/delete/clusterrolebindings/tasks/main.yaml
platforms/quorum/configuration/roles/delete/flux_namespaces/tasks/main.yaml
platforms/quorum/configuration/roles/delete/gitrepositories/tasks/main.yaml
platforms/quorum/configuration/roles/delete/helm_charts/tasks/main.yaml
platforms/quorum/configuration/roles/delete/helm_releases/tasks/main.yaml
platforms/quorum/configuration/roles/delete/helm_releases/tasks/nested.yaml
platforms/quorum/configuration/roles/delete/kustomization/tasks/main.yaml
platforms/quorum/configuration/roles/delete/organizations_namespaces/tasks/main.yaml

---
bug(quorum): updated reset.yaml
```
Added patching and deletion code for the following kubernetes resources
1. ClusterRole
2. ClusterRoleBinding
3. GitRepository
4. Kustomization
5. HelmChart
6. HelmRelease
7. Organizations namespaces
8. flux namespace
```
fixes #2157

[ci-skip] updated reset.yaml

---

docs/source/developer/shared.md
docs/source/faq.md
docs/source/operations/configure_prerequisites.md
docs/source/operations/upgrade_helm_deployments.md
platforms/hyperledger-fabric/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/shared/configuration/README.md
platforms/shared/configuration/add-new-organization.yaml

**Change log**
Fix add org playbook with new playbook names
Fix typo in k8s_secret role

[docs] update the readme and docs with updated playbook names

---

platforms/shared/configuration/delete-network.yaml
platforms/shared/configuration/roles/delete/gitops/tasks/main.yaml

**Change log**
- add delete for releases with org-namespace folder names

[ci-skip] add delete for releases with org-namespace folder names

---

platforms/r3-corda/configuration/roles/create/k8_component/Readme.md
platforms/r3-corda/configuration/roles/create/k8_component/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/k8_component/vars/main.yaml
platforms/r3-corda/configuration/roles/create/node_component/Readme.md
platforms/r3-corda/configuration/roles/create/node_component/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/doorman/Readme.md
platforms/r3-corda/configuration/roles/setup/doorman/tasks/main.yml
platforms/r3-corda/configuration/roles/setup/nms/Readme.md
platforms/r3-corda/configuration/roles/setup/nms/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/node/Readme.md
platforms/r3-corda/configuration/roles/setup/node/tasks/main.yaml
platforms/r3-corda/configuration/roles/setup/notary/Readme.md
platforms/r3-corda/configuration/roles/setup/notary/tasks/main.yaml
platforms/r3-corda/releases/README.md
platforms/shared/charts/vault-k8s-mgmt/templates/job.yaml
platforms/shared/configuration/roles/check/helm_component/Readme.md
platforms/shared/configuration/roles/check/helm_component/tasks/main.yaml
platforms/shared/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

--------------
1. Fixed deletion of realese files.
2. Fixed issue of detecting the completion of vault-k8s-job 
3 .Fixed undefined variable error in task to check if vault-k8s-job has completed
platforms/r3-corda/configuration/roles/create/k8_component/Readme.md 
platforms/r3-corda/configuration/roles/create/k8_component/tasks/main.yaml 
platforms/r3-corda/configuration/roles/create/k8_component/vars/main.yaml 
platforms/r3-corda/configuration/roles/create/node_component/Readme.md 
platforms/r3-corda/configuration/roles/create/node_component/tasks/main.yaml 
platforms/r3-corda/configuration/roles/setup/doorman/Readme.md 
platforms/r3-corda/configuration/roles/setup/doorman/tasks/main.yml …

[ci-skip] Reset network doesn't clean all git release

---

platforms/shared/configuration/roles/setup/flux/tasks/main.yaml

flux optimisation
- setting up strict flux version while installation
- skip watching other namespaces

[ci-skip] flux optimisation

---

platforms/hyperledger-besu/charts/generate_ambassador_certs/templates/job.yaml
platforms/hyperledger-besu/charts/node_besu/templates/deployment.yaml
platforms/hyperledger-besu/configuration/roles/create/helm_component/templates/node_besu.tpl
platforms/hyperledger-besu/configuration/samples/network-besu.yaml
platforms/shared/configuration/add-new-organization.yaml

---
**feat(besu): add 'none' as a new option for transaction manager.**
```
Updated the following files to introduce the new option for transaction manager:
1. sample network-besu.yaml file.
2. deployment.yaml file of chart node_besu.
3. node_besu.tpl template.
In addition to the above changes, I also made the following updates:
1. added a label to the job.yaml file of the generate_ambassador_certs chart
2. corrected playbook names in the add-new-organization.yaml file
```
fixes #2163

[besu] add 'none' as a new option for transaction manager

---

platforms/hyperledger-besu/charts/generate_ambassador_certs/templates/job.yaml
platforms/hyperledger-besu/charts/orion_key_mgmt/templates/job.yaml
platforms/hyperledger-besu/charts/tessera_key_mgmt/templates/job.yaml
platforms/hyperledger-fabric/charts/generate_cacerts/templates/job.yaml
platforms/hyperledger-fabric/charts/vault_kubernetes/templates/job.yaml
platforms/hyperledger-indy/charts/indy-auth-job/templates/job.yaml
platforms/hyperledger-indy/charts/indy-key-mgmt/templates/job.yaml
platforms/quorum/charts/certs-ambassador-quorum/templates/job.yaml
platforms/quorum/charts/crypto_ibft/templates/job.yaml
platforms/quorum/charts/crypto_raft/templates/job.yaml
platforms/quorum/charts/tessera_key_mgmt/templates/job.yaml
platforms/r3-corda-ent/charts/gateway/templates/job.yaml

**Change log**
- Fixes retry exhaust on job check roles

[ci-skip] add app labels on helm chart jobs

---

platforms/hyperledger-besu/charts/generate_ambassador_certs/templates/job.yaml
platforms/hyperledger-besu/configuration/roles/create/genesis/ibft/tasks/main.yaml

--------------
1. Add extradata field in genesis file. platforms/hyperledger-besu/configuration/roles/create/genesis role
2. Fixed duplicate app label in platforms/hyperledger-besu/charts/generate_ambassador_certs
platforms/hyperledger-besu/charts/generate_ambassador_certs/templates/job.yaml 
platforms/hyperledger-besu/configuration/roles/create/genesis/ibft/tasks/main.yaml

[besu] Add extradata field in genesis file

---

platforms/network-schema.json

bug(fabric): fixed the job length in the network-schema.json
fixes: #2212

[ci-skip]: fixed the job length.

---

docs/source/contributing.md

Fix formatting in contributing guidelines

---

platforms/hyperledger-fabric/configuration/add-new-channel.yaml
platforms/hyperledger-fabric/configuration/add-organization.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/syschannel/tasks/create_orderer.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/syschannel/tasks/update_orderer.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/syschannel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/get_update_block.yaml

Added fix for add-org not working when proxy == none

[ci-skip] Fixed add org for proxy none

---

platforms/quorum/charts/node_quorum/Chart.yaml
platforms/quorum/charts/node_quorum_member/Chart.yaml
platforms/quorum/charts/node_tessera/Chart.yaml
platforms/quorum/charts/tessera_key_mgmt/Chart.yaml

Update to complete the Quorum chart releases

[quorum] Update chart.yaml for failed releases

---

platforms/quorum/charts/certs-ambassador-quorum/Chart.yaml
platforms/quorum/charts/certs-ambassador-quorum/README.md
platforms/quorum/charts/crypto_ibft/Chart.yaml
platforms/quorum/charts/crypto_ibft/README.md
platforms/quorum/charts/crypto_raft/Chart.yaml
platforms/quorum/charts/crypto_raft/README.md
platforms/quorum/charts/node_constellation/Chart.yaml
platforms/quorum/charts/node_constellation/README.md
platforms/quorum/charts/node_quorum/Chart.yaml
platforms/quorum/charts/node_quorum/README.md
platforms/quorum/charts/node_quorum_member/Chart.yaml
platforms/quorum/charts/node_quorum_member/README.md
platforms/quorum/charts/node_quorum_validator/Chart.yaml
platforms/quorum/charts/node_quorum_validator/README.md
platforms/quorum/charts/quorum-connector/Chart.yaml
platforms/quorum/charts/quorum-connector/README.md
platforms/quorum/charts/quorum_node_tessera/Chart.yaml
platforms/quorum/charts/quorum_node_tessera/README.md
platforms/quorum/charts/quorum_tessera_key_mgmt/Chart.yaml
platforms/quorum/charts/quorum_tessera_key_mgmt/README.md

---
**feat(quorum): improved descriptions in Chart.yaml files for Quorum platform Helm charts**
```
- This commit enhances the descriptions in the Chart.yaml files for all Quorum platform Helm charts.
- The updates ensure that the descriptions accurately reflect the functionality and purpose of each Helm chart.
Additionally:
- Fix the Verification section of each README.md's file.
```

[ci-skip] improved descriptions in Chart.yaml files for all Helm charts

---

platforms/hyperledger-besu/charts/besu-connector/Chart.yaml
platforms/hyperledger-besu/charts/besu-connector/README.md
platforms/hyperledger-besu/charts/generate_ambassador_certs/Chart.yaml
platforms/hyperledger-besu/charts/generate_ambassador_certs/README.md
platforms/hyperledger-besu/charts/generate_ambassador_certs/templates/_helpers.tpl
platforms/hyperledger-besu/charts/generate_ambassador_certs/values.yaml
platforms/hyperledger-besu/charts/node_besu/Chart.yaml
platforms/hyperledger-besu/charts/node_besu/README.md
platforms/hyperledger-besu/charts/node_besu/values.yaml
platforms/hyperledger-besu/charts/node_key_mgmt/Chart.yaml
platforms/hyperledger-besu/charts/node_key_mgmt/README.md
platforms/hyperledger-besu/charts/node_key_mgmt/templates/_helpers.tpl
platforms/hyperledger-besu/charts/node_key_mgmt/values.yaml
platforms/hyperledger-besu/charts/node_orion/Chart.yaml
platforms/hyperledger-besu/charts/node_orion/README.md
platforms/hyperledger-besu/charts/node_orion/values.yaml
platforms/hyperledger-besu/charts/node_tessera/Chart.yaml
platforms/hyperledger-besu/charts/node_tessera/README.md
platforms/hyperledger-besu/charts/node_tessera/values.yaml
platforms/hyperledger-besu/charts/node_validator/Chart.yaml
platforms/hyperledger-besu/charts/node_validator/README.md
platforms/hyperledger-besu/charts/node_validator/values.yaml
platforms/hyperledger-besu/charts/orion_key_mgmt/Chart.yaml
platforms/hyperledger-besu/charts/orion_key_mgmt/README.md
platforms/hyperledger-besu/charts/orion_key_mgmt/templates/_helpers.tpl
platforms/hyperledger-besu/charts/orion_key_mgmt/values.yaml
platforms/hyperledger-besu/charts/tessera_key_mgmt/Chart.yaml
platforms/hyperledger-besu/charts/tessera_key_mgmt/README.md
platforms/hyperledger-besu/charts/tessera_key_mgmt/templates/_helpers.tpl
platforms/hyperledger-besu/charts/tessera_key_mgmt/values.yaml

--------------
1. Add readme files for all charts
2. Add _helpers.tpl files for all charts
3. Update the values.yaml files
4. Update the version in chart.yaml files
Modifications in  
platforms/hyperledger-besu/charts platforms/hyperledger-besu/charts/besu-connector
platforms/hyperledger-besu/charts/generate_ambassador_certs platforms/hyperledger-besu/charts/node_besu
platforms/hyperledger-besu/charts/node_key_mgmt
platforms/hyperledger-besu/charts/node_orion
platforms/hyperledger-besu/charts/node_tessera
platforms/hyperledger-besu/charts/node_validator
platforms/hyperledger-besu/charts/orion_key_mgmt
platforms/hyperledger-besu/charts/tessera_key_mgmt
Fixes #2287

[ci-skip] Add README.md files

---

platforms/hyperledger-indy/charts/indy-auth-job/Chart.yaml
platforms/hyperledger-indy/charts/indy-auth-job/README.md
platforms/hyperledger-indy/charts/indy-auth-job/templates/_helpers.tpl
platforms/hyperledger-indy/charts/indy-domain-genesis/Chart.yaml
platforms/hyperledger-indy/charts/indy-domain-genesis/README.md
platforms/hyperledger-indy/charts/indy-domain-genesis/templates/_helpers.tpl
platforms/hyperledger-indy/charts/indy-key-mgmt/Chart.yaml
platforms/hyperledger-indy/charts/indy-key-mgmt/README.md
platforms/hyperledger-indy/charts/indy-key-mgmt/templates/_helpers.tpl
platforms/hyperledger-indy/charts/indy-ledger-txn/Chart.yaml
platforms/hyperledger-indy/charts/indy-ledger-txn/README.md
platforms/hyperledger-indy/charts/indy-ledger-txn/templates/_helpers.tpl
platforms/hyperledger-indy/charts/indy-node/Chart.yaml
platforms/hyperledger-indy/charts/indy-node/README.md
platforms/hyperledger-indy/charts/indy-node/templates/_helpers.tpl
platforms/hyperledger-indy/charts/indy-pool-genesis/Chart.yaml
platforms/hyperledger-indy/charts/indy-pool-genesis/README.md
platforms/hyperledger-indy/charts/indy-pool-genesis/templates/_helpers.tpl

docs(indy): Added readme's for all the helm charts for platform indy
Add readme files for all charts
Add _helpers.tpl files for all charts
fixes #2288

[ci-skip] Added readme's for all the helm charts

---

docs/source/roadmap.rst
platforms/hyperledger-besu/configuration/add-validator.yaml
platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/validator_vote.yaml
platforms/hyperledger-fabric/configuration/add-orderer-organization.yaml
platforms/hyperledger-fabric/configuration/add-organization.yaml
platforms/hyperledger-fabric/configuration/add-peer.yaml
platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/external-chaincode-ops.yaml
platforms/hyperledger-fabric/configuration/generate-artefacts-deploy.yaml
platforms/shared/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

- code indentation
- roadmap docs
- missing variable in playbooks calling sc and vault k8s creation

[ci-skip] corrected missing variables

---

platforms/r3-corda/charts/h2/values.yaml
platforms/r3-corda/charts/mongodb-tls/values.yaml
platforms/r3-corda/charts/mongodb/values.yaml
platforms/r3-corda/charts/nms-tls/values.yaml
platforms/r3-corda/charts/nms/values.yaml
platforms/r3-corda/charts/node-initial-registration/values.yaml
platforms/r3-corda/charts/node/values.yaml
platforms/r3-corda/charts/notary-initial-registration/values.yaml
platforms/r3-corda/charts/notary/values.yaml

docs(corda): fix default values in values.yaml
fix default values in values.yaml

[ci-skip] fix default values in values.yaml

---

platforms/hyperledger-fabric/configuration/add-orderer.yaml
platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/roles/create/anchorpeer/tasks/nested_anchorpeer.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca_tools/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels_join/tasks/nested_channel_join.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/anchorpeer_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/approve_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-orderer.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-peer.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-tools.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/cacerts_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/cli.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/commit_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/create_channel_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/install_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/install_external_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/instantiate_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/invoke_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/join_channel_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/orderernode.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/upgrade_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/value_peer.tpl
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/existing_peer_cli.tpl
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/orderer_cli.tpl
platforms/network-schema.json
platforms/shared/charts/vault-k8s-mgmt/templates/job.yaml

--------------
1. Added creation of Vault auths through cluster_id.
2. Fixed errors related to storage class for the add orderer operation
platforms/hyperledger-fabric/configuration/add-orderer.yaml platforms/hyperledger-fabric/configuration/deploy-network.yaml platforms/hyperledger-fabric/configuration/roles/create/anchorpeer/tasks/nested_anchorpeer.yaml 
platforms/hyperledger-fabric/configuration/roles/create/ca_tools/orderer/tasks/main.yaml 
platforms/hyperledger-fabric/configuration/roles/create/channels/tasks/valuefile.yaml 
platforms/hyperledger-fabric/configuration/roles/create/channels_join/tasks/nested_channel_join.yaml 
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel …

[fabric] Added creation of Vault auths through cluster_id.

---

platforms/hyperledger-fabric/configuration/roles/create/configtx/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrderer_default.tpl
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrg_default.tpl
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxinit_default.tpl

-------------------
1. Updated .tpl files related to creation of the configtx.yaml file with new features of the fabric 2.5 version
platforms/hyperledger-fabric/configuration/roles/create/configtx/tasks/main.yaml 
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrderer_default.tpl platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrg_default.tpl 
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxinit_default.tpl
Fixes
#2350

[fabric] Update configtx.yaml file

---

docs/source/operations/upgrading_chaincode.md
platforms/hyperledger-fabric/charts/install_external_chaincode/README.md
platforms/hyperledger-fabric/charts/install_external_chaincode/values.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/network-schema.json

Fixes #2370 
Updated documentation regarding use of `sequence` for chaincodes

[fabric] update docs regarding using sequence in network.yaml

---

platforms/r3-corda/charts/doorman-tls/templates/service.yaml
platforms/r3-corda/charts/doorman/templates/service.yaml
platforms/r3-corda/charts/nms-tls/templates/service.yaml
platforms/r3-corda/charts/nms/templates/service.yaml
platforms/r3-corda/charts/node/templates/service.yaml
platforms/r3-corda/charts/notary/templates/service.yaml
platforms/shared/configuration/setup-k8s-environment.yaml

This PR will provide the support of using latest ambassador edge-stack
changes:
• Updated all services to use the latest Ambassador Edge Stack routing rules.
fixes https://github.com/hyperledger/bevel/issues/2359

feat(r3-corda): enable latest ambassador edge-stack

---

platforms/hyperledger-fabric/charts/anchorpeer/templates/anchorpeer.yaml
platforms/hyperledger-fabric/charts/anchorpeer/templates/configmap.yaml
platforms/hyperledger-fabric/charts/orderernode/templates/configmap.yaml
platforms/hyperledger-fabric/charts/osn_create_channel/Chart.yaml
platforms/hyperledger-fabric/charts/osn_create_channel/README.md
platforms/hyperledger-fabric/charts/osn_create_channel/templates/_helpers.tpl
platforms/hyperledger-fabric/charts/osn_create_channel/templates/configmap.yaml
platforms/hyperledger-fabric/charts/osn_create_channel/templates/osn_create_channel.yaml
platforms/hyperledger-fabric/charts/osn_create_channel/values.yaml
platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels_join/tasks/nested_channel_join.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrderer_default.tpl
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrg_default.tpl
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxProfile_default.tpl
platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/osnchannels/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/osnchannels/tasks/orderercheck.yaml
platforms/hyperledger-fabric/configuration/roles/create/osnchannels/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/create_channel_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/orderernode.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/osn_create_channel_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/vars/main.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/network-schema.json
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

--------------
1. Updated confitx.yaml
2. Updated genesis file creation command.
3. Updatded orderer node
4. Created channel using the osnadmin commands
5. Updated anchorpeer job using configtxlator
6. Tested that version 2.2.2 still works.
Modifications in charts
platforms/hyperledger-fabric/charts/anchorpeer
platforms/hyperledger-fabric/charts/create_channel 
platforms/hyperledger-fabric/charts/orderernode
platforms/hyperledger-fabric/charts/osn_create_channel
platforms/hyperledger-fabric/configuration/deploy-network.yaml 
platforms/hyperledger-fabric/configuration/roles/create/channels_join 
platforms/hyperledger-fabric/configuration/roles/create/configtx …

[fabric] Channel creation with osnadmin commands

---

platforms/shared/configuration/roles/setup/edge-stack/tasks/main.yaml

---
- #### A when condition has been added to ensure that elasticIp is only fetched when it is actually available.
---

[shared] ensure elasticIp is available

---

platforms/hyperledger-fabric/charts/fabric-orderernode/templates/configmap.yaml
platforms/hyperledger-fabric/charts/fabric-orderernode/templates/deployment.yaml
platforms/hyperledger-fabric/charts/fabric-osnadmin-channel-create/templates/configmap.yaml
platforms/hyperledger-fabric/charts/fabric-osnadmin-channel-create/templates/osn_create_channel.yaml
platforms/hyperledger-fabric/configuration/add-orderer.yaml
platforms/hyperledger-fabric/configuration/add-peer.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/templates/update_channel_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/orderers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/osnchannels/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/nested_main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/orderernode.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/osn_create_channel_job.tpl

--------------
1.add_peer updated for version 2.5.4
2.add_orderer updated for version 2.5.4
Modifications
platforms/hyperledger-fabric/charts/fabric-orderernode 
platforms/hyperledger-fabric/charts/fabric-osnadmin-channel-create 
platforms/hyperledger-fabric/configuration/add-orderer.yaml 
platforms/hyperledger-fabric/configuration/add-peer.yaml 
platforms/hyperledgerfabric/configuration/roles/create/new_orderer/create_appchannel_block/templates/update_channel_script.tpl 
platforms/hyperledger-fabric/configuration/roles/create/orderers/tasks/main.yaml 
platforms/hyperledger-fabric/configuration/roles/create/osnchannels/tasks/valuefile.yaml 
platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/main.yaml …

[fabric] Update add_peer and add_orderer to 2.5.4

---

docs/source/operations/upgrading_chaincode.md
platforms/hyperledger-fabric/configuration/external-chaincode-ops.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install_ext/tasks/nested_main.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/peer_certs/tasks/generate_certs.yaml
platforms/hyperledger-fabric/configuration/roles/create/external_chaincode_server/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_peer/update_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/fetch/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-external-chaincode.yaml
platforms/network-schema.json

--------------
1.Support upgrade/update chaincode operation for the external chaincode
Modifications
docs/source/operations/upgrading_chaincode.md
platforms/hyperledger-fabric/configuration/external-chaincode-ops.yaml 
platforms/hyperledger-fabric/configuration/roles/create/chaincode/install_ext/tasks/nested_main.yaml 
platforms/hyperledger-fabric/configuration/roles/create/chaincode/peer_certs/tasks/generate_certs.yaml 
platforms/hyperledger-fabric/configuration/roles/create/external_chaincode_server/tasks/valuefile.yaml 
platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/main.yaml 
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-external-chaincode.yaml platforms/network-schema.json
fixes #2352

[fabric] Support upgrade chaincode for the external chaincode

---

platforms/shared/charts/bevel-scripts/scripts/bevel-vault.sh

```
feat(shared): update bevel-vault.sh script for sh shell compatibility
Change:
- Modified bevel-vault.sh script for sh shell compatibility.
fixes #quick-fix
```

[shared] update bevel-vault.sh script for sh shell compatibility

---

platforms/hyperledger-fabric/charts/fabric-chaincode-approve/templates/approve_chaincode.yaml
platforms/hyperledger-fabric/charts/fabric-chaincode-approve/values.yaml
platforms/hyperledger-fabric/charts/fabric-chaincode-commit/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/charts/fabric-chaincode-commit/values.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-external-chaincode.yaml
platforms/network-schema.json

--------------
1. Support init required option for chaincode approval and commit operation

[fabric] init required in the chaincode

---

platforms/hyperledger-fabric/charts/fabric-chaincode-commit/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/nested_valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/approve_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/commit_chaincode_job.tpl

1. Added the init_required field in the tpl files.
2. Fixed error in the invoke chaincode job.
3. Fixed errors in variable names.
**Modifications**
platforms/hyperledger-fabric/charts/fabric-chaincode-commit/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/nested_valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/approve_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/commit_chaincode_job.tpl

[fabric] Hotfix init required

---

MAINTAINERS.md
platforms/hyperledger-indy/images/indy-key-mgmt/Dockerfile

Emergency fix for indy-key-mgmt build error

[indy] Fix for indy-key-mgmt container to build correctly

---

platforms/quorum/charts/quorum-tessera-key-mgmt/templates/job.yaml
platforms/quorum/charts/quorum-tessera-node/templates/deployment.yaml
platforms/quorum/charts/quorum-tlscerts-gen/templates/job.yaml
platforms/quorum/configuration/roles/helm_component/templates/certs-ambassador-quorum.tpl
platforms/quorum/configuration/roles/helm_component/templates/crypto_ibft_job.tpl
platforms/quorum/configuration/roles/helm_component/templates/crypto_raft_job.tpl
platforms/quorum/configuration/roles/helm_component/templates/crypto_tessera.tpl
platforms/quorum/configuration/roles/helm_component/templates/memberquorum.tpl
platforms/quorum/configuration/roles/helm_component/templates/tessera.tpl
platforms/quorum/configuration/roles/helm_component/templates/validatorquorum.tpl

---
**feat(quorum): update vault authentication path**
```
Changes:
- Update Quorum codebase to use the correct authPath.
- Update containers to start with 'sh' as the default shell.
These changes will facilitate the smooth deployment and reset of the Quorum network.
```
**fixes #quick-fixes**

[quorum] update vault authentication path

---

docs/source/guides/networkyaml-substrate.md
platforms/substrate/charts/substrate-genesis/templates/job.yaml
platforms/substrate/configuration/roles/create/helm_component/templates/dscp_ipfs_node.tpl
platforms/substrate/configuration/roles/create/helm_component/templates/genesis_job.tpl
platforms/substrate/configuration/roles/create/helm_component/templates/node_substrate.tpl
platforms/substrate/configuration/roles/create/helm_component/templates/substrate_keys_job.tpl

1. Updated Fabric config file
2. Fixed authpath hardcode in tpl files
fixes #2465

update(docs): Substrate configuration file.

---

platforms/hyperledger-fabric/charts/README.md
platforms/hyperledger-fabric/charts/fabric-ca-server/templates/ca-job-cleanup.yaml
platforms/hyperledger-fabric/charts/fabric-ca-server/templates/statefulset.yaml
platforms/hyperledger-fabric/charts/fabric-ca-server/values.yaml
platforms/hyperledger-fabric/charts/fabric-cacerts-gen/values.yaml
platforms/hyperledger-fabric/charts/fabric-catools/templates/configmap.yaml
platforms/hyperledger-fabric/charts/fabric-catools/templates/deployment.yaml
platforms/hyperledger-fabric/charts/fabric-catools/values.yaml
platforms/hyperledger-fabric/charts/fabric-cli/templates/deployment.yaml
platforms/hyperledger-fabric/charts/fabric-genesis/.helmignore
platforms/hyperledger-fabric/charts/fabric-genesis/Chart.yaml
platforms/hyperledger-fabric/charts/fabric-genesis/README.md
platforms/hyperledger-fabric/charts/fabric-genesis/files/configtx.yaml.tpl
platforms/hyperledger-fabric/charts/fabric-genesis/templates/_helpers.tpl
platforms/hyperledger-fabric/charts/fabric-genesis/templates/configmap.yaml
platforms/hyperledger-fabric/charts/fabric-genesis/templates/genesis-job-cleanup.yaml
platforms/hyperledger-fabric/charts/fabric-genesis/templates/job.yaml
platforms/hyperledger-fabric/charts/fabric-genesis/values.yaml
platforms/hyperledger-fabric/charts/fabric-orderernode/templates/configmap.yaml
platforms/hyperledger-fabric/charts/fabric-orderernode/templates/node-statefulset.yaml
platforms/hyperledger-fabric/charts/fabric-orderernode/values.yaml
platforms/hyperledger-fabric/charts/fabric-peernode/templates/node-statefulset.yaml
platforms/hyperledger-fabric/charts/values/noproxy-and-novault/ordererOrganization/genesis.yaml
platforms/hyperledger-fabric/charts/values/noproxy-and-novault/ordererOrganization/orderer.yaml
platforms/hyperledger-fabric/charts/values/noproxy-and-novault/peerOrganization/ca-server.yaml
platforms/hyperledger-fabric/charts/values/noproxy-and-novault/peerOrganization/peer.yaml
platforms/hyperledger-fabric/charts/values/proxy-and-vault/ordererOrganization/genesis.yaml
platforms/hyperledger-fabric/charts/values/proxy-and-vault/peerOrganization/ca-server.yaml

1. Deploy fabric 2.5.4 without a channel using helm charts.
2. Deploy fabric 2.2.2 without a channel using helm charts.
3. Add new job platforms/hyperledger-fabric/charts/fabric-genesis
4. Deploy with Ansible is pending
5. Update README.md files is pending
**Changes in charts**
platforms/hyperledger-fabric/charts/fabric-ca-server 
platforms/hyperledger-fabric/charts/fabric-cacerts-gen 
platforms/hyperledger-fabric/charts/fabric-catools 
platforms/hyperledger-fabric/charts/fabric-genesis
platforms/hyperledger-fabric/charts/fabric-orderernode 
platforms/hyperledger-fabric/charts/fabric-peernode
fixes #2536

[fabric] Create configtx and genesis files using just helm

---

platforms/r3-corda-ent/charts/README.md
platforms/r3-corda-ent/charts/cenm-idman/templates/service.yaml
platforms/r3-corda-ent/charts/cenm-networkmap/templates/service.yaml
platforms/r3-corda-ent/charts/cenm/requirements.yaml
platforms/r3-corda-ent/charts/cenm/templates/_helpers.tpl
platforms/r3-corda-ent/charts/cenm/templates/hooks-pre-install.yaml
platforms/r3-corda-ent/charts/enterprise-node/files/node-initial-registration.sh
platforms/r3-corda-ent/charts/enterprise-node/files/node.conf
platforms/r3-corda-ent/charts/enterprise-node/files/run.sh
platforms/r3-corda-ent/charts/enterprise-node/requirements.yaml
platforms/r3-corda-ent/charts/enterprise-node/templates/service.yaml
platforms/r3-corda-ent/charts/enterprise-node/templates/statefulset.yaml
platforms/r3-corda-ent/charts/values/noproxy-and-novault/node.yaml
platforms/r3-corda-ent/charts/values/proxy-and-vault/cenm.yaml
platforms/r3-corda-ent/charts/values/proxy-and-vault/init.yaml
platforms/r3-corda-ent/charts/values/proxy-and-vault/node.yaml
platforms/r3-corda-ent/charts/values/proxy-and-vault/notary.yaml

**Change log**
- Added code to enable deployment using vault(hashicorp) and proxy (ambassador)
Fixes #2540

feat(r3-corda-ent): helm only deployment using proxy and vault

---

docs/source/guides/fabric/add-cli.md
platforms/hyperledger-fabric/charts/README.md
platforms/hyperledger-fabric/charts/fabric-cli/README.md
platforms/hyperledger-fabric/charts/fabric-cli/templates/_helpers.tpl
platforms/hyperledger-fabric/charts/fabric-cli/templates/deployment.yaml
platforms/hyperledger-fabric/charts/fabric-cli/templates/volume.yaml
platforms/hyperledger-fabric/charts/fabric-cli/values.yaml
platforms/hyperledger-fabric/charts/fabric-orderernode/requirements.yaml
platforms/hyperledger-fabric/charts/fabric-peernode/requirements.yaml

- Chart version update in dependencies
- `add-cli` readme updated with helm install option

[fabric] Fix Chart versions and add-cli via helm chart

---

docs/source/guides/fabric/deploy-fabric-operator.md
platforms/hyperledger-fabric/configuration/roles/delete/operator/tasks/delete_channel.yaml
platforms/hyperledger-fabric/configuration/roles/operator/create/ca/user/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/operator/create/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/operator/create/peer/tasks/main.yaml
platforms/shared/configuration/roles/setup/istio/tasks/main.yaml

[fabric] Operator readme updates

---

platforms/substrate/configuration/roles/create/helm_component/templates/dscp_ipfs_node.tpl
platforms/substrate/configuration/roles/create/helm_component/templates/genesis_job.tpl
platforms/substrate/configuration/roles/create/helm_component/templates/node_substrate.tpl
platforms/substrate/configuration/roles/create/helm_component/templates/substrate_keys_job.tpl
platforms/substrate/configuration/roles/create/ipfs_bootnode/tasks/main.yaml
platforms/substrate/configuration/roles/create/member_node/tasks/main.yaml
platforms/substrate/configuration/roles/create/validator_node/tasks/main.yaml
platforms/substrate/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/substrate/configuration/samples/network-sample.yaml
platforms/substrate/configuration/samples/network-substrate.yaml
reset.sh
run.sh

---
**feat(substrate): refactor codebase for effective deployment**
```
This PR improves Substrate DLT deployment using code from the main branch.
Changes:
- Updated the 'Vault-Auth' path for pods to match the expected Vault Authentication Engine in Vault.
- Updated the 'Storage-class' name for pods to match the name of the expected 'storage-class'.
```
fixes #quick-fix

[substrate] refactor codebase for effective deployment

---

platforms/shared/configuration/add-new-organization.yaml

Fixed the execution of the playbook chaincode-ops.yaml when running the playbook add-organization.yaml

fabric: hot fix

---

platforms/shared/configuration/roles/create/job_component/vars/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

Fixed files in the shared folder that were causing deployment errors.

shared: hot fix

---

.github/workflows/scorecard.yml
CHANGELOG.md
GOVERNANCE.md
README.md
ROADMAP.md
SECURITY.md
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/nested_main.yaml
platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/templates/update_consenter_script.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/approve_chaincode_job.tpl
platforms/hyperledger-indy/configuration/roles/check/k8_component/tasks/main.yaml
platforms/hyperledger-indy/configuration/samples/network-indy-newnode-to-baf-network.yaml
platforms/hyperledger-indy/configuration/samples/network-indy-newnode-to-non-baf-network.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube-aries.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube.yaml
platforms/network-schema.json
platforms/shared/configuration/add-new-organization.yaml
reset.sh

chore: merged changes from main to develop

---

platforms/hyperledger-indy/charts/indy-node/Chart.yaml
platforms/substrate/charts/dscp-ipfs-node/Chart.yaml
platforms/substrate/charts/substrate-genesis/Chart.yaml
platforms/substrate/charts/substrate-key-mgmt/Chart.yaml
platforms/substrate/charts/substrate-node/Chart.yaml

**feat(indy & substrate): upgrade chart version to 1.1.0**
- Upgraded the chart version to 1.1.0 for both the Indy and Substrate platforms.
fixes #quick-fix

feat(indy & substrate): upgrade chart version to 1.1.0

---

platforms/hyperledger-besu/charts/besu-genesis/templates/genesis-job-init.yaml
platforms/hyperledger-besu/charts/besu-node/templates/node-hooks-pre-install.yaml

This PR includes: 
- Fix on besu-genesis/templates/genesis-job-init.yaml
- Fix on besu-node/templates/node-hooks-pre-install.yaml

feat(2638): added conditions for no-vault approach
