.github/ISSUE_TEMPLATE/release-checklist-template.md

Added a release checklist issue template, this will be used to create an issue for release checklist items before any release.

Release checklist template

---

platforms/hyperledger-fabric/configuration/roles/create/channel_artifacts/tasks/main.yaml

The configtxgen tool is executed on the Ansible host.
Thus the downloaded version has to be based on the `install_os` and `install_arch` variables.

Fabric: Base configtxgen download on Ansible host

---

platforms/shared/configuration/roles/git_push/tasks/main.yaml

Converts the git push output to a more readable format.
Old format:
```
TASK [/Users/hendrik.leppelsack/Code/blockchain-automation-framework/platforms/hyperledger-fabric/configuration/../../shared/configuration/roles/git_push : Output for gitpush] ***
ok: [localhost] => {
"GIT_OUTPUT.stdout": "---------------SHOW CONTENT OF DIR---------------\n.\n..\n.git\n.github\n.gitignore\nCODEOWNERS\nCODE_OF_CONDUCT.md\nDockerfile\nLICENSE\nMAINTAINERS.md\nREADME.md\nautomation\nbuild\ndocs\nexamples\nplatforms\nrelease\nrelease-notes.md\nrun.sh\n---------------GIT PUSH---------------\nOn branch develop\nYour branch is ahead of 'origin/develop' by 11 commits.\n  (use \"git push\" to publish your local commits)\n\nnothing to commit, working tree clean"
}
```
New format:
```
ok: [localhost] => {
"msg": …
```

Prettier git output

---

docs/source/prerequisites.md

Ansible's `unarchive` task requires gnu tar.
MacOS come with bsdtar by default.
This adds a note to the prerequisites documentation.

Install "gnu tar on MacOS" notice to prerequisites

---

docs/source/developer/mac_minikube_setup.md
platforms/hyperledger-indy/charts/indy-ledger-txn/templates/job.yaml
platforms/hyperledger-indy/charts/indy-ledger-txn/values.yaml
platforms/hyperledger-indy/charts/indy-node/templates/service.yaml
platforms/hyperledger-indy/charts/indy-node/values.yaml
platforms/hyperledger-indy/configuration/deploy-network.yaml
platforms/hyperledger-indy/configuration/roles/check/validation/tasks/check_count.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/auth_job/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/ledger_txn/tasks/nested_main.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/ledger_txn/templates/ledger-txn.tpl
platforms/hyperledger-indy/configuration/roles/create/helm_component/node/templates/node.tpl
platforms/hyperledger-indy/configuration/roles/setup/endorsers/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/setup/endorsers/tasks/nested_main.yaml
platforms/hyperledger-indy/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/hyperledger-indy/images/indy-cli/indy-ledger.sh
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

Fixed bugs:
- charts/indy-ledger-txn:
- wrong volume names
- printing Kubernetes Token on console out
- wrong Vault Role for access to auth method via service account
- wrong path to seed in file
- deploy-network:
- Role: 'Create Endorser Identities':
- missing needed variables (undefined variables in nested tasks)
- check-count:
- typo in function
- missing task to reset variable for counting (wrong counting of Endorser in Organization)
- auth_job:
- wrong getting address of Kubernetes (new function returns still only one -> this is correct)
- ledger_txn:
- missing task to check if release directory exists
- the same name of HelmRelease, which exists in BAF
- wrong service account name
- wrong  auth path
- typo of variable names
- setup/endorser:
- missing loop of organization
- missing …

Indy test on minikube

---

release-notes.md

Updating the release notes to point at the correct, most up-to date GitHub release notes

Point Release Notes to GitHub releases

---

platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

**Changelog**
- Update Ansible role for create steward's port list. Change group by IP of steward to group by kubecontext (group by k8s cluster)
@sownak 
#674

[indy] Fix creating a list steward's port for ambassador (#674)

---

.travis.yml

**Changelog**
- Add specific molecule version for travis ci

Specifying  molecule version to 3.0.6 for travis ci

---

platforms/corda-ent/charts/idman/templates/pvc.yaml
platforms/corda-ent/charts/nmap/templates/pvc.yaml
platforms/corda-ent/charts/node/templates/pvc.yaml
platforms/corda-ent/charts/notary/templates/pvc.yaml
platforms/corda-ent/configuration/deploy-network.yaml
platforms/corda-ent/configuration/roles/create/certificates/ambassador/idman/tasks/main.yaml
platforms/corda-ent/configuration/roles/create/certificates/ambassador/nmap/tasks/main.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/create_signer.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/db.tpl
platforms/corda-ent/configuration/roles/setup/bridge/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/float/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/idman/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/nmap/tasks/main.yml
platforms/corda-ent/configuration/roles/setup/node_registration/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/notary/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/tlscerts/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/tlscerts/tasks/nested_main.yaml

**Changelog**
- Add feature to create the tls certificate of cenm services from the path mentioned in network.yaml
- Fix large memory size for resources such as db
- Updated code to move the tls certificate creation tasks within the corresponding CENM service creation role itself to have distinctive roles in network.yaml
#972

[ Corda-Ent ] General fixes for code uniformity across Corda Opensource and Corda Enterprise platforms

---

platforms/corda-ent/charts/idman/files/idman.conf
platforms/corda-ent/charts/idman/files/run.sh
platforms/corda-ent/charts/idman/templates/deployment.yaml
platforms/corda-ent/charts/idman/templates/pvc.yaml
platforms/corda-ent/charts/idman/templates/service.yaml
platforms/corda-ent/charts/idman/values.yaml
platforms/corda-ent/charts/node/values.yaml
platforms/corda-ent/charts/notary/templates/deployment.yaml
platforms/corda-ent/charts/notary/values.yaml
platforms/corda-ent/charts/signer/files/signer.conf
platforms/corda-ent/charts/signer/templates/deployment.yaml
platforms/corda-ent/charts/signer/templates/service.yaml
platforms/corda-ent/charts/signer/values.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/create_signer.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/idman.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/notary.tpl
platforms/corda-ent/configuration/roles/setup/idman/tasks/main.yaml

**Changelog**
- Add Docker images for Signer & Idman to private repository, updated associated roles/templates
- Update  `platforms/shared/configuration/site.yaml` to have option to reset Corda Enterprise network
- Update `values.yaml` for Signer; as well as any mentions of those values in K8s components, templates & Ansible roles
- Update `values.yaml` for Idman; as well as any mentions of those values in K8s components, templates & Ansible roles
- Fixed inconsistencies in the use of `imagePullSecret` from `value.yaml` file vs. hardcoding the secret
- Removed unneeded, hanging pieces of code both in `value.yaml` files & K8s components
#943

[ Corda-Ent ] Update Signer & Idman, cleanup

---

platforms/corda-ent/charts/idman/values.yaml
platforms/corda-ent/charts/nmap/files/nmap.conf
platforms/corda-ent/charts/nmap/files/run.sh
platforms/corda-ent/charts/nmap/files/set-network-parameters.sh
platforms/corda-ent/charts/nmap/templates/deployment.yaml
platforms/corda-ent/charts/nmap/templates/pvc.yaml
platforms/corda-ent/charts/nmap/templates/service.yaml
platforms/corda-ent/charts/nmap/values.yaml
platforms/corda-ent/configuration/roles/helm_component/tasks/main.yaml
platforms/corda-ent/configuration/roles/helm_component/templates/nmap.tpl
platforms/corda-ent/configuration/roles/helm_component/templates/notary_initial_registration.tpl
platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/corda-ent/configuration/roles/setup/nmap/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/notary-initial-registration/tasks/main.yaml
platforms/corda-ent/configuration/roles/setup/notary/tasks/main.yaml

**Changelog**
- Fix `pod.resources` in `idman/values.yaml`
- Update `values.yaml` file for networkmap; as well as any mentions of these values in K8s files & Ansible roles
- Clean up `platforms/corda-ent/configuration/roles/helm_component/templates/nmap.tpl` to be in the same order as the `value.yaml` file
- Update `platforms/corda-ent/charts/nmap/templates/deployment.yaml` to add a check to `main` container, to verify that `setnparam` init-container has run
- Cleanup logic of referencing Docker images in `platforms/corda-ent/configuration/roles/helm_component/tasks/main.yaml`; as well as update the variables in `platforms/corda-ent/configuration/roles/helm_component/vars/main.yaml` …

[ Corda-Ent ] Fix cleanup of networkmap

---

platforms/quorum/charts/node_constellation/Chart.yaml
platforms/quorum/charts/node_constellation/templates/deployment.yaml
platforms/quorum/charts/node_tessera/Chart.yaml

**Changelog**
- Update the Quorum constellation charts to be compatible with Helm 3
- Majority of the 'general' Quorum changes were already done in issue #892 / PR #1035 
- Revert `apiVersion` of both Tesseract & Constellation to `v1`
#950

[ Quorum ] Update network charts to Helm 3

---

platforms/hyperledger-fabric/configuration/reset-network.yaml

**Changelog**
- Fix `reset-playbook.yaml` error - `delete/genesis` role will not loop over channels anymore 
#1028

[ Fabric ] Fix reset playbook error

---

docs/source/architectureref/certificates_path_list_fabric.md
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/orderer_cli.tpl
platforms/hyperledger-fabric/configuration/roles/k8_component/vars/main.yaml

**Changelog**
- Add the system channel name while creating the genesis file
- Add the orderer_cli in k8_component/templates/orderer_cli.tpl 
- Add the crypto material of admin of orderer org to the vault and delete it on reset.
#1072

[ Fabric ] Add the support of orderer cli in fabric.

---

platforms/hyperledger-fabric/charts/approve_chaincode/Chart.yaml
platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml
platforms/hyperledger-fabric/charts/commit_chaincode/Chart.yaml
platforms/hyperledger-fabric/charts/commit_chaincode/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/configuration/chaincode-install-instantiate.yaml
platforms/hyperledger-fabric/configuration/create-join-channel.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/approve_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/commit_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/create_channel_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/join_channel_job.tpl

**Changelog**
- Update Fabric v2.2 code to compatible with Helm 3 
- Fix `createchannel`/`joinchannel` duplicate release name when adding new channel
- Fix `create-join-channel.yaml` annotations for incorporating `channel_status`
- Add task names to `chaincode-install-instantiate.yaml` to be able to use the `--start-with-task` flag on the `ansible-playbook` command
---
The following components have been (manually) tested:
- Main network deployment
- Add new organization
- Add new channel
- Install & instantiate chaincode on new organization
- Upgrade chaincode to next version
(A more detailed description of the components are found on the ticket description #1098)
@lakshyakumar @suvajit-sarkar @jagpreetsinghsasan …

[ Fabric ] Upgrade Fabric v2.2 to Helm 3

---

docs/source/operations/upgrading_chaincode.md
platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml
platforms/hyperledger-fabric/charts/commit_chaincode/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/configuration/add-organization.yaml
platforms/hyperledger-fabric/configuration/add-peer.yaml
platforms/hyperledger-fabric/configuration/chaincode-install-instantiate.yaml
platforms/hyperledger-fabric/configuration/chaincode-upgrade.yaml

**Changelog**
- Add the support of upgarding chaincode for Fabric 2.2 using `chaincode-install-instantiate.yaml` playbook
- Fix the comments in the playbooks.
- Update operational guide for upgarding the chaincode in Fabric.
#1133

[ Fabric ] Adding the support of upgarding chaincode for Fabric 2.2

---

platforms/r3-corda-ent/charts/notary-initial-registration/templates/job.yaml
platforms/r3-corda-ent/charts/notary/templates/deployment.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/db.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/node_registration.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary_initial_registration.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/bridge/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/float/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/node/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/node_registration/tasks/nested_main.yaml
platforms/r3-corda-ent/configuration/roles/setup/notary-initial-registration/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/notary/tasks/main.yaml
platforms/r3-corda-ent/images/notary.dockerfile

**Changelog**
- Update Helm templates to directly reference the `network.yaml`
- `node.tpl`
- `node_initial_registration.tpl`
- `notary.tpl`
- `notary_initial_registration.tpl`
- Update Notary Docker image to Enterprise version 4.4
- Update Notary & Notary initial registration charts to change `jarPath` - moved to `opt/cenm/bin`
- Update `roles/setup/notary/main.yaml` to add `network.version`
- Update `roles/setup/notary_initial_registration/main.yaml` to add `network.version`
- Added `org.version` to organization where `type == node` - used to determine the Docker images for Node + Firewall
- Updated private Docker repository with new tags of images (old ones will be deleted upon merge & pipeline completion)
**NOTE** A PR will be made …

[ Corda-Ent ] Update docker images & Helm templates

---

platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml

Signed-off-by: NthMetal <832529@gmail.com>
**Changelog**
- Fix
platforms\hyperledger-fabric\charts\install_chaincode\templates\install_chaincode.yaml
CC_SRC_PATH is not resolved when lang: "node". This causes install to fail when using node chaincode.
Updated yaml to move chaincode and resolve CC_SRC_PATH

[Fabric][fix] Install chaincode with lang node

---

platforms/hyperledger-fabric/configuration/roles/helm_component/templates/create_channel_job.tpl

**Changelog**
- Fix
Flux ignores the new files pushed to the Github for a new
channel creation. Appending the channel name along with
the organization name will make it a unique channel name for
a peer node/organization.
#1158

[Fabric][Fix] Append the channel name to the HelmRelease

---

platforms/hyperledger-fabric/charts/peernode/templates/deployment.yaml
platforms/hyperledger-fabric/charts/peernode/templates/pvc.yaml

**Changelog**
- Update peer CouchDB to use a volume instead of in-memory for its files
@jagpreetsinghsasan @lakshyakumar 
#1132 - see issue for more info on approach for this story, major reworks were deemed out of scope and bug(s) were created

[ Fabric ] Add peer couchdb volume in case of DR

---

docs/source/operations/besu_networkyaml.md
docs/source/operations/corda_networkyaml.md
docs/source/operations/fabric_networkyaml.md
docs/source/operations/indy_networkyaml.md
docs/source/operations/quorum_networkyaml.md
platforms/hyperledger-besu/configuration/samples/network-besu-newnode.yaml
platforms/hyperledger-besu/configuration/samples/network-besu.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv-add-peer.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft-add-orderer.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3-aries.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml
platforms/quorum/configuration/samples/network-quorum-newnode.yaml
platforms/quorum/configuration/samples/network-quorum.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml
platforms/r3-corda/configuration/samples/network-cordav2.yaml
platforms/shared/charts/ambassador/templates/service.yaml
platforms/shared/charts/ambassador/values.yaml
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml

Signed-off-by: jwavoetacn <68590662+jwavoetacn@users.noreply.github.com>
**Changelog**
- Added the following lines to the ./ambassador/templates/service.yaml:
- 53: `type: LoadBalancer`
- 54: `{{- if .Values.ambassador.loadBalancerSourceRanges }}`
- 55: `loadBalancerSourceRanges: {{ .Values.ambassador.loadBalancerSourceRanges }}`
- 56: `{{- end }} `
- Added the 'loadBalancerSourceRanges' value to ./ambassador/values.yaml.
- Added '--set ambassador.loadBalancerSourceRanges={{ network.env.loadBalancerSourceRanges }}' to 'KUBECONFIG=' in the ./ambassador/tasks/main.yaml.
- Added 'loadBalancerSourceRanges:' to the network-cordav2.yaml.
These changes make it possible to add custom IPs to the inbound rules for the ports in the range: 30000-32767
@sauveergoel …

[Shared] Add custom IPs to inbound ambassador rules

---

platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/peercheck.yaml

**Changelog**
- Fix Ansible role to fetch peer certificates from Vault 
@lakshyakumar @jagpreetsinghsasan 
#1178

[ Fabric ] Fix rerun issue with peer certificates

---

platforms/r3-corda-ent/charts/node/templates/deployment.yaml
platforms/r3-corda-ent/charts/notary-initial-registration/templates/job.yaml
platforms/r3-corda-ent/charts/notary/templates/deployment.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/templates/notary_initial_registration.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml

Signed-off-by: srinivasan.sankaran <srinivasan.sankaran@accenture.com>
**Changelog**
- Updated the notary vars with enterprise corda node image
- Changed the Corda jar path in notary_initial_registration.tpl and notary.tpl.
- Updated the JVM version as per enterprise node image in notary_inititial_registration and notary job.
- Used cat to replace env values in a file in notary_inititial_registration  job.
- Updated the permission of Cordapps folder in notary deployment.
#1187

[ R3-Corda-Ent ] Use enterprise corda node image in notary with validating as true

---

platforms/hyperledger-fabric/charts/invoke_chaincode/templates/invoke_chaincode.yaml
platforms/hyperledger-fabric/charts/invoke_chaincode/values.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/Readme.md
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/invoke_chaincode_job.tpl

**Changelog**
- Add the `add_organization` flag to the `invoke chaincode tpl` file and the `invoke chaincode chart` to invoke with the correct command and condition.
- Fix the arguments passed with the init function in case of fabric version 1.4.x .
- Fix the `chaincode Invoke role` to invoke the chaincode after the addition of new organization in fabric version 1.4.x and 2.2.x .
#1206

[ Fabric ] Fix invoke chaincode for Fabric version 2.2.x and 1.4.x

---

platforms/hyperledger-fabric/configuration/roles/create/peers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/peers/vars/main.yaml

**Changelog**
- Update peer CouchDB image for HLF 2.2.0 from `hyperledger/fabric-couchdb:0.4.18` to `couchdb:3.1`
@jagpreetsinghsasan @lakshyakumar 
Resolves #1088

[ Fabric ] Update couchdb image for HLF 2.2.0

---

.github/workflows/molecule_test.yml

**Changelog**
- Add github workflows for molecule test on develop branch PRs
- The workflow test coverage is for molecule tests only and corda and fabrics DLTs for now
- The tests stages will run only for PRs with title containing the following tags : [shared] or [corda] or [fabric]
@sownak 
#1227

Added Workflow for molecule test on develop branch PRs

---

platforms/hyperledger-fabric/charts/anchorpeer/templates/configmap.yaml
platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml
platforms/hyperledger-fabric/charts/commit_chaincode/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/charts/create_channel/templates/configmap.yaml
platforms/hyperledger-fabric/charts/fabric_cli/templates/deployment.yaml
platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml
platforms/hyperledger-fabric/charts/instantiate_chaincode/templates/instantiate_chaincode.yaml
platforms/hyperledger-fabric/charts/invoke_chaincode/templates/invoke_chaincode.yaml
platforms/hyperledger-fabric/charts/join_channel/templates/configmap.yaml
platforms/hyperledger-fabric/charts/join_channel/templates/join_channel.yaml
platforms/hyperledger-fabric/charts/peernode/templates/configmap.yaml
platforms/hyperledger-fabric/charts/upgrade_chaincode/templates/upgrade_chaincode.yaml
platforms/hyperledger-fabric/charts/verify_chaincode/templates/verify_chaincode.yaml

**Changelog**
- Updated paths to get the TLS CA instead of the CA for CORE_PEER_TLS_ROOTCERT_FILE 
#1263

Fix the CA certificate being mapped to TLSCA certificate

---

.all-contributorsrc

Signed-off-by: Jagpreet Singh Sasan <jagpreet.singh.sasan@accenture.com>
**Changelog**
- Add all-contributors file for badges
- Created on master branch for the badge to work
@sownak

Added all-contributors file for badges

---

platforms/hyperledger-fabric/configuration/add-organization.yaml
platforms/hyperledger-fabric/configuration/roles/create/cli_pod/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/create_block/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/syschannel_block/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/syschannel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/syschannel_block/templates/syschannel_update_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/new_organization/syschannel_block/vars/main.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/fetch/tasks/nested_fetch_role.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/sign_and_update/tasks/main.yaml

**Changelog**
- Added new setup/genesis folder where the genesis block is updated by the orderer using syschannel to add the org to the existing consortium
- Fixed the creation of a new anchorpeer for the new org 
- Updated some files related to the sign and update of the block to have that org in the desired channel
**Screenshots**
In this screenshot, we can see that the existing creator org (calv) and the new org (malv) are in the same consortium
In this screenshot, we can see that both orgs have one anchorpeer each, the existing one and the new one created.
#1297

[ Fabric ] New Org is added to existing consortium and to the existing channel

---

platforms/hyperledger-fabric/configuration/roles/create/crypto_script/templates/organisation_script.tpl

Changelog
Fixed line in platforms/hyperledger-fabric/configuration/roles/create/crypto_script/templates/organisation_script.tpl for the affiliation, which was getting the name "carrier" or "manufacturer" from subject instead of the name of the organization.
Reviewed by
Linked issue
#1306 
Now, user1 has every certificate, as expected:

[ Fabric ] Changed affiliation to fully save the certificates for user1

---

Dockerfile.jdk8
docs/source/developer/baf_minikube_setup.md
docs/source/developer/docker-build.md

**Changelog**
- Add Dockerfile.jdk8 for Corda and Corda Enterprise
- Updated Dockerfile to use ubuntu 20.04 and jdk14
@pppazos
#1023

update to java14

---

Dockerfile

**Changelog**
- Fix
The openshift versions before 0.11.0 do not handle
K8s config from Azure clusters.
Ref: https://github.com/kubernetes-client/python-base/pull/141/files
@sownak 
#1466

Update the openshift version

---

.github/workflows/molecule_test.yml

**Changelog**
- Fixed molecule tests to run specifically for non-caps platform names, '[shared],[docs],[indy],[fabric],[corda],[besu],[quorum],[corda-ent]'
#issue_number

[shared] changing molecule tests to run specifically for non-caps platform names

---

Dockerfile
Dockerfile.jdk8
platforms/r3-corda-ent/charts/idman/templates/service.yaml
platforms/r3-corda-ent/charts/nmap/templates/deployment.yaml
platforms/r3-corda-ent/charts/nmap/templates/service.yaml
platforms/r3-corda-ent/charts/node-initial-registration/templates/job.yaml
platforms/r3-corda-ent/charts/node/templates/deployment.yaml
platforms/r3-corda-ent/charts/node/templates/service.yaml
platforms/r3-corda-ent/charts/notary-initial-registration/templates/job.yaml
platforms/r3-corda-ent/charts/notary/templates/deployment.yaml
platforms/r3-corda-ent/charts/notary/templates/service.yaml
platforms/r3-corda-ent/configuration/roles/create/certificates/cenm/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/create/certificates/node/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/credentials/tasks/node_tasks_nested.yaml
platforms/r3-corda-ent/configuration/roles/setup/idman/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/nmap/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/node/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/notary/tasks/main.yaml

**Changelog**
- in cenm (idman, network, notaries) trust tls root ca in cenm organization
- in nodes (include idman and network crts in corda truststore)
- k8s tls secrets created in the org namespace
@sownak 
#996 #1462

[corda-ent] certificates for ambassador

---

platforms/hyperledger-besu/charts/node_orion/templates/service.yaml
platforms/hyperledger-fabric/charts/ca/templates/service.yaml
platforms/hyperledger-fabric/charts/orderernode/templates/service.yaml
platforms/hyperledger-fabric/charts/peernode/templates/service.yaml
platforms/quorum/charts/node_tessera/templates/service.yaml
platforms/r3-corda-ent/charts/idman/templates/service.yaml
platforms/r3-corda-ent/charts/nmap/templates/service.yaml
platforms/r3-corda-ent/charts/node/templates/service.yaml
platforms/r3-corda-ent/charts/notary/templates/service.yaml
platforms/r3-corda/charts/doorman-tls/templates/service.yaml
platforms/r3-corda/charts/doorman/templates/service.yaml
platforms/r3-corda/charts/nms-tls/templates/service.yaml
platforms/r3-corda/charts/nms/templates/service.yaml
platforms/r3-corda/charts/node/templates/service.yaml
platforms/r3-corda/charts/notary/templates/service.yaml
platforms/shared/charts/ambassador/templates/service.yaml
platforms/shared/configuration/molecule/kubernetes-corda/converge.yml
platforms/shared/configuration/molecule/kubernetes-corda/verify.yml
platforms/shared/configuration/molecule/kubernetes-fabric/converge.yml
platforms/shared/configuration/molecule/kubernetes-fabric/verify.yml
platforms/shared/configuration/roles/setup/ambassador/tasks/main.yaml
platforms/shared/configuration/roles/setup/haproxy-ingress/tasks/main.yaml

Signed-off-by: pppazos <hgartti@gmail.com>
**Changelog**
- Add default TLSContext for ambassador
- Add min_tls_version: v1.2 in all Ambassador TLSContext objects
- Remove ELBSecurityPolicy-TLS-1-2-2017-01 annotation
#1500

[shared] only TLS 1.2+ allowed

---

platforms/network-schema.json
platforms/shared/configuration/network-schema-validator.yaml

**Changelog**
- Add quorum and besu in the validation network.type enum
- Fix need to have network.yaml in build folder for validation 

[shared] removed need to have network.yaml in build folder for validation

---

platforms/quorum/configuration/molecule/crypto-ibft/cleanup.yml
platforms/quorum/configuration/roles/setup/golang/tasks/main.yaml

**Changelog**
- Fixed task to get the permissions for extracting the go tarball in /usr/local/ directory. 
@sownak 
#1611

[quorum] Quick fix to get permissions to extract go tarball in  /usr/local/ path

---

platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/main.yaml
platforms/shared/configuration/roles/check/helm_component/tasks/main.yaml

**Changelog**
- Updated vault write command to use a file instead of cat command while writing to the vault, to support large file sizes.
#1642

[fabric] Updated vault write command to support large file sizes

---

platforms/hyperledger-fabric/charts/ca_server/templates/job.yaml
platforms/hyperledger-fabric/charts/vault_kubernetes/templates/configmap.yaml
platforms/hyperledger-fabric/charts/vault_kubernetes/templates/job.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/orderer/tasks/orderer.yaml
platforms/hyperledger-fabric/configuration/roles/create/crypto/peer/tasks/peer.yaml
platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca_server_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/install_chaincode_job.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/value_peer.tpl

**Changelog**
- Add configmap in charts /vault_kubernetes
- Fix create/crypto/orderer  and create/crypto/peer (add a new condition in task Get all ambassador secrets from Vault) 
- Fix create/genesis in main.yaml change vault write for vault kv put in task "Create genesis block"
- Fix value_per.tpl and install_chaincode_job.tpl change metadata for data in vault paths
- Update vault_kubernetes_job and ca_server_job to vaultv2
@alvaropicazo 
#1657

[fabric] Access policies from the configmaps and deployment frabic to vaultv2

---

docs/source/architectureref/certificates_path_list_corda.md
platforms/r3-corda/charts/node-initial-registration/templates/job.yaml
platforms/r3-corda/charts/node-initial-registration/values.yaml
platforms/r3-corda/charts/node/values.yaml
platforms/r3-corda/charts/notary-initial-registration/templates/job.yaml
platforms/r3-corda/charts/notary-initial-registration/values.yaml
platforms/r3-corda/charts/notary/values.yaml
platforms/r3-corda/configuration/roles/create/certificates/node/Readme.md
platforms/r3-corda/configuration/roles/create/certificates/node/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/certificates/notary/Readme.md
platforms/r3-corda/configuration/roles/create/certificates/notary/tasks/main.yaml
platforms/r3-corda/configuration/roles/create/node_component/templates/job.tpl
platforms/r3-corda/configuration/roles/create/node_component/templates/node.tpl
platforms/r3-corda/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

**Changelog**
- Fix/removed root token being used in store-certs post registration
- Added create and update capabilities in policy to vault auth token
@sownak 
#1713

[corda] fixed node/notary registration charts using roottoken

---

platforms/r3-corda-ent/charts/auth/templates/deployment.yaml
platforms/r3-corda-ent/charts/auth/values.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/templates/auth.tpl
platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/auth/README.md
platforms/r3-corda-ent/configuration/roles/setup/auth/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/cenm/tasks/main.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml

Signed-off-by: angelaalagbe <angela.alagbe@accenture.com>
**Changelog**
- Added auth service tpl file, ansible role, readme file, added task to deploy auth service to setup/cenm role
- 
- Updated the deployment file to use same helm version as BAF, updated the syntax of my tpl file to match the charts, updated the values file to match the tpl file, updated helm linting file to include auth service, updated helm_component variables file to include auth service details. 
#1726

[corda-ent] Auth service automation added and readme file

---

platforms/hyperledger-fabric/charts/approve_chaincode/templates/approve_chaincode.yaml
platforms/hyperledger-fabric/charts/commit_chaincode/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml

**Changelog**
- Add version checking in chaincode operations to allow pod to be redeployed without throwing error.
@arsulegai 
#[1784](https://github.com/hyperledger/bevel/issues/1784)

[fabric] check if version exists during chaincode operations

---

.github/workflows/docker_build.yml

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>
**Changelog**
- Updated the docker_build.yml github workflow quorum jobs to now push to ghcr.io instead of DockerHub.
#1780

[ci skip] Updated docker_build workflow quorum jobs

---

platforms/hyperledger-fabric/charts/install_chaincode/templates/install_chaincode.yaml

**Changelog**
- Add a new condition in platforms/hyperledger-fabric/charts/install_chaincode , for both chaincodes to work
This is the configuration used in the network.yaml for the network display with the chain code:
github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic/chaincode-go
#1797

[fabric] Test automated deployment of latest fabric go chaincode

---

platforms/README.md

**Changelog**
- Updated the platforms directory README.md to include all the DLT platforms supported by HL-Bevel.
#1838

updated platforms' README file to include all supported DLT platforms

---

platforms/hyperledger-fabric/configuration/reset-network.yaml
platforms/hyperledger-fabric/configuration/roles/delete/gitops_files/tasks/main.yaml
platforms/shared/configuration/kubernetes-env-setup.yaml
platforms/shared/configuration/roles/git_push/tasks/main.yaml
platforms/shared/configuration/roles/setup/flux/tasks/main.yaml

**Changelog**
- Update the setup flux role to setup flux-v2
- Installs flux cli
- In case the git protocol is ssh, it updates the git host
- Bootstraps the flux (this creates the flux namespace as well)
- Update reset network of fabric to uninstall flux
- Added task to delete the flux manifest on reset of network
- **The installations are idempotent in itself so don't require checks before installation**
@sownak 
#1898

[fabric] update flux to flux v2 setup

---

platforms/shared/configuration/molecule/kubernetes-corda/converge.yml
platforms/shared/configuration/molecule/kubernetes-corda/verify.yml
platforms/shared/configuration/molecule/kubernetes-fabric/converge.yml
platforms/shared/configuration/molecule/kubernetes-fabric/verify.yml
platforms/shared/configuration/molecule/kubernetes-indy/converge.yml
platforms/shared/configuration/molecule/kubernetes-indy/verify.yml

**Changelog**
- Flux v2 installation requires valid repo and user creds, removing the flux installation test as the flux v2 installation is idempotent by default and difficult to do test

[shared] Molecule: Remove flux  v2 installation test

---

examples/supplychain-app/besu/express_nodeJS/controllers/product.js

Unsanitized input from `req.body.trackingID` flows `trackingID` into `res.send`, where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS).
Signed-off-by: Bhaskar Ram <bhaskarvilles@duck.com>

fix(security):Cross Site Scripting Attack (XSS)

---

platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrderer_default.tpl
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-mixed.tpl

**Changelog**
- Fix platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-mixed.tpl. The secretRef field has been removed, because it causes the error shown in the following image.
- Update platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrderer_default.tpl. The value of the BlockValidation field has been modified because it produced an error in the approvechaincode job.
@suvajit-sarkar @jagpreetsinghsasan

mixed-org fixes base code

---

platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/syschannel_block/tasks/nested_create_cli.yaml

**Changelog**
- Add some conditions in  platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml to avoid error when executing the playbook to add an organization with only peers in its configuration
- Add tasks to get the correct desired cli pod name in platforms/hyperledger-fabric/configuration/roles/create/ca-tools/orderer/tasks/main.yaml
@suvajit-sarkar @jagpreetsinghsasan

[fabric] Fix add-new-organization playbook

---

platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/tasks/nested_create_cli.yaml

**Changelog**
- Add tasks to get the correct desired cli pod name in platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_syschannel_block/tasks/nested_create_cli.yaml
@suvajit-sarkar @jagpreetsinghsasan 
#issue_number

[fabric ] Fix add-peer add-orderer playbooks

---

platforms/hyperledger-fabric/charts/catools/templates/configmap.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-tools/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrderer_default.tpl
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxProfile_default.tpl
platforms/network-schema.json

**Changelog**
- Add the following fields in the network.yaml:
*network.consensus
*network.channels[*].orderer.name (is a list)
*network.organizations[*].orderer_org (This field should only be added in peer organizations. Indicate from which
organization takes the orderers)
- Update create/configtx and create/ca-tools roles to perform deployments with multiple orderer organizations
- Update Network-schema.json
- Fix bug in ca-tools chart that causes an infinite loop in the case of having two organizations with orderer
#2038

[fabric] Fix multiple orderers - MixedOrganization

---

platforms/hyperledger-besu/configuration/reset-network.yaml
platforms/hyperledger-fabric/configuration/reset-network.yaml
platforms/hyperledger-indy/configuration/cleanup.yaml
platforms/quorum/configuration/reset-network.yaml
platforms/r3-corda-ent/configuration/reset-network.yaml
platforms/r3-corda/configuration/reset-network.yaml

**Changelog**
Fixed flux uninstall by removing the individual k8s components and then deleting namespace in reset-network.yaml instead of directly removing the namespace
#2039

[shared] fixed flux uninstall in reset-network.yaml

---

platforms/hyperledger-besu/configuration/add-validator.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/check_vault.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/validator_vote.yaml

**Changelog**
- Changed made to split crypto generation and node joining process during validator addition
- Fixed the vault authention when adding a new org to the existing besu network
`add-validator.yaml` playbook can be invoked by setting up `crypto_only: true` in network.yaml.
#2110

[besu] split crypto generation while adding validator nodes

---

platforms/hyperledger-fabric/charts/vault_kubernetes/templates/job.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca-server/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/reviewer_rbac.tpl
platforms/hyperledger-fabric/configuration/roles/setup/vault_kubernetes/tasks/main.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-new-channel.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-ordererorg.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-peer.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-remove-organization.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2-raft-add-orderer.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabricv2.yaml
platforms/hyperledger-fabric/configuration/samples/network-proxy-none.yaml
platforms/shared/configuration/roles/check/setup/tasks/main.yaml

**Changelog**
- remove reviewer token in Vault_Kubernetes chart
- Add vault-auth as system:auth-delegator
- Add checks for certificate creation so that job checks are not carried again (jobs vanish when cluster restarts)
- Remove unnecessary fields from network.yaml samples for raft consensus

[ci-skip] Fix vault-auth when restart

---

platforms/hyperledger-besu/configuration/reset-network.yaml
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/certificates/ambassador/tasks/nested_main.yaml
platforms/shared/configuration/roles/setup/certmanager/tasks/main.yml

changes:
Removed the helm module while creation of TLS cert by cert manager because we are deploying helm chart using shell module
changed the order of organization.issuer to check if it is defined/undefined and then to check the value if it is default/letsencrypt instead of first checking value and then checking if it is defined
Reviewers:
Fixes:
hotfix

[besu] fixed the helm ansible module for TLS cert creation using cert manager

---

platforms/hyperledger-fabric/configuration/reset-network.yaml
platforms/hyperledger-fabric/configuration/roles/delete/clusterrole/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/clusterrolebindings/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/flux_namespaces/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/gitrepositories/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/helm_charts/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/helm_releases/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/helm_releases/tasks/nested.yaml
platforms/hyperledger-fabric/configuration/roles/delete/kustomization/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/organizations_namespaces/tasks/main.yaml

Changes:
Updated the reset-network.yaml to have new roles under roles/delete, there new roles would delete  the  cluster roles, clusterrolebindings, patch and delete gitrepositories, patch and delete kustomizations, helm charts, helm releases and the namespaces
"delete/clusterrole"
"delete/clusterrolebindings"
"delete/gitrepositories"
"delete/kustomization" 
"delete/helm_charts"
"delete/helm_releases"
"delete/organizations_namespaces"
"delete/flux_namespaces"
Reviewers:
Fixes:
#2157

[ci-skip] reset fixes

---

platforms/quorum/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl
platforms/r3-corda-ent/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl
platforms/r3-corda/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl
platforms/r3-corda/configuration/roles/delete/vault_secrets/tasks/nested_main.yaml

--------------
1. Fixed permission denied error for vault.
2. Fixed vault-auth bug 
3. Fixed removal of vault policies for r3-corda
platforms/quorum/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl 
platforms/r3-corda-ent/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl 
platforms/r3-corda/configuration/roles/create/k8_component/templates/reviewer_rbac.tpl 
platforms/r3-corda/configuration/roles/delete/vault_secrets/tasks/nested_main.yaml

[ci-skip] Pods crashes post Kubernetes cluster nodes are restarted

---

platforms/shared/configuration/roles/setup/flux/tasks/main.yaml

Reverts hyperledger/bevel#2224
Helm releases are not getting installed post this change, reverting the PR. Kindly test and and create PR.

[ci-skip] Revert "flux optimisation"

---

platforms/shared/configuration/roles/setup/cactus-connector/tasks/main.yaml
platforms/shared/configuration/roles/setup/cactus-connector/tasks/nested_main.yaml

---
bug(besu): update path for generating cactus-connector helm release file
```
Description:
- The generated Helm release file for the Cactus connector is currently not stored in its own organization directory within the release folder for the Besu platform. As a result, improper resetting of the entire Besu network occurs.
- This pull request proposes an update to the path, ensuring that the cactus-connector Helm release file is generated within the respective organizations.
Solution:
- Update the path for generating the cactus-connector Helm release file to the appropriate organization directory within the release folder for the Besu platform.
- This adjustment will enable successful deletion and resetting of the Besu network.
```

[besu] update path for generating cactus-connector helm release file.

---

docs/source/operationalguide.rst
docs/source/operations/setup_cactus_connector_fabric.md

--------------
1. Added operation guide on deploying fabric cacti connector
Modifications in docs
docs/source/operationalguide.rst
docs/source/operations/setup_cactus_connector_fabric.md

[ci-skip] Create operation guide on deploying cacti connector

---

docs/source/faq.md
docs/source/prerequisites.md
platforms/shared/configuration/roles/setup/vault/defaults/main.yaml

--------------
1. Update Hashicorp Vault version to 1.13.1. To carry out the tests, a vault has been deployed following the steps in this video. https://www.youtube.com/watch?v=eKMDgKshjQ8&list=PL0MZ85B_96CFJUzic2ZF9rposfx2hr2rm.
Using  version of helm search repo hashicorp/vault --versions.
Modifications
-------------
docs/source/faq.md
docs/source/prerequisites.md
platforms/shared/configuration/roles/setup/vault/defaults/main.yaml
Fixes
#2282

[ci-skip] Upgrade Hashicorp Vault version

---

platforms/quorum/charts/quorum-connector/.helmignore
platforms/quorum/charts/quorum-connector/Chart.yaml
platforms/quorum/charts/quorum-connector/README.md
platforms/quorum/charts/quorum-connector/templates/_helpers.tpl
platforms/quorum/charts/quorum-connector/templates/configmap.yaml
platforms/quorum/charts/quorum-connector/templates/deployment.yaml
platforms/quorum/charts/quorum-connector/templates/service.yaml
platforms/quorum/charts/quorum-connector/values.yaml
platforms/quorum/configuration/setup-cactus-connector.yaml
platforms/shared/configuration/roles/helm_lint/vars/main.yaml
platforms/shared/configuration/roles/setup/cactus-connector/tasks/main.yaml
platforms/shared/configuration/roles/setup/cactus-connector/templates/quorum-connector.tpl
platforms/shared/configuration/roles/setup/cactus-connector/vars/main.yml

---
**feat(quorum): enable Cactus connector for the GoQuorum platform**
```
This commit introduces the integration of the Cactus connector into the GoQuorum platform. Key highlights of this integration include:
• Added Cactus connector to the Quorum platform
• The connector promotes interoperability between different decentralized networks, furthering the growth and adoption of blockchain technology.
• The integration improves the overall functionality of the system.
```
fixes #2253

[ci-skip] enable cactus connector.

---

platforms/quorum/charts/certs-ambassador-quorum/Chart.yaml
platforms/quorum/charts/certs-ambassador-quorum/README.md
platforms/quorum/charts/certs-ambassador-quorum/values.yaml
platforms/quorum/charts/crypto_ibft/Chart.yaml
platforms/quorum/charts/crypto_ibft/README.md
platforms/quorum/charts/crypto_ibft/templates/_helpers.tpl
platforms/quorum/charts/crypto_ibft/values.yaml
platforms/quorum/charts/crypto_raft/Chart.yaml
platforms/quorum/charts/crypto_raft/README.md
platforms/quorum/charts/crypto_raft/templates/_helpers.tpl
platforms/quorum/charts/crypto_raft/values.yaml
platforms/quorum/charts/node_constellation/README.md
platforms/quorum/charts/node_constellation/values.yaml
platforms/quorum/charts/node_quorum/README.md
platforms/quorum/charts/node_quorum/values.yaml
platforms/quorum/charts/node_quorum_member/README.md
platforms/quorum/charts/node_quorum_member/values.yaml
platforms/quorum/charts/node_quorum_validator/README.md
platforms/quorum/charts/node_quorum_validator/values.yaml
platforms/quorum/charts/node_tessera/README.md
platforms/quorum/charts/node_tessera/values.yaml
platforms/quorum/charts/tessera_key_mgmt/README.md
platforms/quorum/charts/tessera_key_mgmt/templates/_helpers.tpl
platforms/quorum/charts/tessera_key_mgmt/values.yaml

---
**docs(quorum): add README.md file for each GoQuorum Helm chart**
```
This commit adds the README.md file for each GoQuorum Helm chart. The README.md files provide essential information and instructions about the respective Helm charts, enabling users and developers to deploy each chart individually.
Additionally, the following changes have been made:
- Updated values.yaml of each Helm chart with default values to provide a clear configuration reference.
- Added helpers.tpl template file only to Helm charts where it was missing, ensuring consistency across the charts.
- Updated the description field of certain required charts.yaml files to provide accurate and informative descriptions.
These changes enhance the usability and documentation of the GoQuorum Helm charts, making it easier …
```

[ci-skip]: add README.md files.

---

platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/roles/create/prometheus/tasks/main.yaml
platforms/hyperledger-besu/configuration/roles/create/prometheus/tasks/nested_loop.yaml
platforms/hyperledger-besu/configuration/roles/create/prometheus/templates/prometheus_release.j2

feat(besu): enable prometheus for besu node metrics 
prometheus server deployments for individual organizations
fixes #2290

[ci-skip] enable prometheus for besu node metrics

---

platforms/hyperledger-besu/configuration/deploy-network.yaml
platforms/hyperledger-besu/configuration/generate-crypto.yaml
platforms/hyperledger-fabric/configuration/add-orderer-organization.yaml
platforms/hyperledger-fabric/configuration/add-organization.yaml
platforms/hyperledger-fabric/configuration/add-peer.yaml
platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/deploy-operator-network.yaml
platforms/hyperledger-indy/configuration/deploy-network.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/node/templates/node.tpl
platforms/quorum/configuration/deploy-network.yaml
platforms/r3-corda-ent/configuration/deploy-network.yaml
platforms/r3-corda-ent/configuration/deploy-nodes.yaml
platforms/r3-corda-ent/configuration/roles/setup/float-environment/tasks/main.yaml
platforms/r3-corda/configuration/deploy-network.yaml
platforms/r3-corda/configuration/deploy-nodes.yaml
platforms/r3-corda/configuration/roles/create/k8_component/templates/create_doorman.tpl
platforms/r3-corda/configuration/roles/create/k8_component/templates/create_mongodb.tpl
platforms/r3-corda/configuration/roles/create/k8_component/templates/network_map.tpl
platforms/r3-corda/configuration/roles/create/node_component/templates/h2.tpl
platforms/r3-corda/configuration/roles/create/node_component/templates/node.tpl
platforms/shared/charts/storage_class/templates/_helpers.tpl
platforms/shared/configuration/roles/create/shared_helm_component/templates/storage_class.tpl
platforms/shared/configuration/roles/delete/k8s_resources/tasks/main.yaml
platforms/shared/configuration/roles/setup/storageclass/tasks/main.yaml
platforms/shared/configuration/roles/setup/vault_kubernetes/templates/cordaos-policy.tpl

This pull request addresses to refactor the current implementation of creating helm releases using GitOps to a more flexible approach by leveraging the ansible helm module and moving the creation of storage class roles to a share folder.
The six platforms that have been modified to make them compatible with the shared "storage class" charts and roles are:
• Hyperledger-Besu
• Hyperledger-Fabric
• R3-corda
• R3-corda-Ent
• Quorum
• Hyperledger- Indy
Changes Made:
Instead of using gitOps to create helm release, used helm module from ansible by creating jinja(j2) template. Moved the creation of storage class roles to a shared folder to use them across all the platforms.
Fixes: #2306

feat(shared): Simplifying storage class creation with helm module 

---

platforms/network-schema.json

The network schema doesn't have node in the validating enum so fails the build - #2375

[fabric] Added 'node' option to fabric_chaincode network schema

---

platforms/hyperledger-fabric/configuration/add-new-channel.yaml
platforms/shared/configuration/roles/setup/vault_kubernetes/tasks/main.yaml

**Fix**
- Doorman, NMS and notary vault k8s release files will be created under the org name folder, which is deleted on reset.
- Added missing variables in `setup vault kubernetes` task, in add-new-channel playbook.
- Removed service account and clusterolebinding checks. This fixes nms and notary vault k8 jobs getting skipped.

bug(r3cordaos) vault k8s release files not getting removed on reset

---

platforms/network-schema.json
platforms/r3-corda-ent/charts/corda-ent-node/templates/deployment.yaml
platforms/r3-corda-ent/charts/corda-ent-notary/templates/deployment.yaml
platforms/r3-corda-ent/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/helm_component/vars/main.yaml
platforms/r3-corda-ent/configuration/samples/network-addNotary.yaml
platforms/r3-corda-ent/configuration/samples/network-cordaent.yaml
platforms/r3-corda-ent/images/node4.10.dockerfile

---
**Changes:**
- `Node` and `Notary` nodes have been upgraded to version 4.10 (specifically, version 4.10.3) from 4.7.
- Introduced a new Dockerfile, named `node4.10.dockerfile`, to build the version 4.10 image.
- Updated the codebase to fetch the latest version 4.10 properly when the user defines it in the network configuration file.
**Additional changes:**
- Added the missing vault delete commands.
- Fixed the code to delete the vault policy correctly.
- Updated sample network configuration files to facilitate smooth deployment.
---
fixes #2398

[r3-corda-ent] upgrade to version 4.10

---

platforms/hyperledger-fabric/charts/fabric-chaincode-commit/templates/commit_chaincode.yaml
platforms/hyperledger-fabric/charts/fabric-chaincode-invoke/templates/invoke_chaincode.yaml
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/existing_peer_cli.tpl

--------------
1.Fixed error in the commit chaincode and invoke chaincode jobs because the organization name contains a '-' 
2.Fixed conflict of the variable orderer.address in platforms/hyperledger-fabric/configuration/roles/k8_component/templates/existing_peer_cli.tpl that caused errors in fabric operations or in deployment of the external chaincode
Modifications
platforms/hyperledger-fabric/charts/fabric-chaincode-commit/templates/commit_chaincode.yaml 
platforms/hyperledger-fabric/charts/fabric-chaincode-invoke/templates/invoke_chaincode.yaml 
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/existing_peer_cli.tpl
fixes #2451

[fabric] Chaincode commit not working

---

.github/workflows/aws_corda_ent_deploy.yaml
platforms/r3-corda-ent/configuration/roles/create/namespace_serviceaccount/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/cenm/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/float-environment/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/node/tasks/main.yaml
platforms/r3-corda-ent/configuration/roles/setup/notary/tasks/notary_node.yaml
platforms/r3-corda-ent/configuration/samples/workflow/network-no-proxy-cordaent.yaml
platforms/r3-corda-ent/configuration/samples/workflow/network-proxy-cordaent.yaml

---
**feat(r3-corda-ent): enable DLT deployment via GitHub Workflow & Action**
**Changes**:
- Introduced a new GitHub Workflow enabling the deployment of Hyperledger Bevel's R3-CORDA-ENT DLT Platform to an EKS Cluster.
- Introduced a new directory at path: `platforms/r3-corda-ent/configuration/samples/workflow`, containing two new sample network configuration files:
1. `network-proxy-cordaent.yaml`: Supports deployment with Ingress controller.
2. `network-no-proxy-cordaent.yaml`: Supports deployment without an Ingress controller, specifically designed for deployment on Minikube.
**Additional Changes**:
- Resolved duplicacy in code related to `ServiceAccount` and `Cluster-role-binding`.
- Replaced the Ambassador Ansible task with new Ambassador-Edge-Stack.
**fixes #2416**

[r3-corda-ent] enable DLT deployment via GitHub Workflow & Action

---

.github/workflows/aws_besu_deploy.yaml
platforms/hyperledger-besu/configuration/samples/workflow/network-no-proxy-besu.yaml
platforms/hyperledger-besu/configuration/samples/workflow/network-proxy-besu.yaml
platforms/shared/charts/bevel-vault-mgmt/templates/serviceAccount.yaml
platforms/shared/configuration/roles/setup/kubectl/tasks/main.yaml

Changes:
Introduced a new GitHub Workflow enabling the deployment of Hyperledger Bevel's BESU DLT Platform to an EKS Cluster. Introduced a new directory at path: platforms/hyperledger-besu/configuration/samples/workflow, containing two new sample network configuration files: 
network-proxy-besu: Supports deployment with Ingress controller. 
network-no-proxy-besu: Supports deployment without an Ingress controller, specifically designed for deployment on Minikube.
Additional Changes:
1)Replaced the Ambassador Ansible task with new Ambassador-Edge-Stack. 
2)platforms/shared/charts/bevel-vault-mgmt/templates/serviceAccount.yaml 3)platforms/shared/configuration/roles/setup/kubectl/tasks/main.yaml
fixes #2416

feat(besu): enable DLT deployment via GitHub Workflow & Action.

---

platforms/hyperledger-fabric/configuration/external-chaincode-ops.yaml

1. Allow invoke chaincode job to run on version 2.5.4 when chaincode is external.

[fabric] Allow invoke chaincode job to run

---

platforms/hyperledger-fabric/charts/fabric-cli/templates/deployment.yaml
platforms/hyperledger-fabric/configuration/add-orderer-organization.yaml
platforms/hyperledger-fabric/configuration/cleanup.yaml
platforms/hyperledger-fabric/configuration/deploy-network.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxOrg_default.tpl
platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/appchannel/templates/update_channel_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/syschannel/tasks/create_orderer.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/syschannel/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/syschannel/tasks/nested_main.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/syschannel/templates/orderer_org.tpl
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/syschannel/templates/syschannel_update_address_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/orderers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/genesis/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/delete/vault_secrets/tasks/main.yaml

1. Fixed deployment add-orderer-organization.yaml playbook for fabric 2.2.2.
2. Added support for deploying add-orderer-organization.yaml playbook for Fabric 2.5.4.
3. Added deletion of genesis file in platforms/hyperledger-fabric/configuration/roles/delete/genesis role.
**Modifications**
platforms/hyperledger-fabric/configuration/add-orderer-organization.yaml 
platforms/hyperledger-fabric/configuration/cleanup.yaml 
platforms/hyperledger-fabric/configuration/deploy-network.yaml 
platforms/hyperledger-fabric/configuration/roles/create/configtx 
platforms/hyperledger-fabric/configuration/roles/create/genesis 
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org 
platforms/hyperledger-fabric/configuration/roles/create/new_organization/order …

[fabric] Support add-orderer-organization.yaml playbook

---

platforms/shared/configuration/roles/setup/storageclass/tasks/main.yaml

chore: Added kubeconfig configuration for creating storage class using Helm chart
This commit adds the `kubeconfig` configuration field to the task responsible for creating a storage class using a Helm chart.

chore: Updated kubeconfig configuration in storage class helm chart

---

platforms/hyperledger-fabric/configuration/deploy-network.yaml

1. The roles related to channel have been removed from the site.yaml file.
2. The create/configtx, create/channel_artifacts and create/genesis" roles aren't executed by version 2.5.4.
3. Channel creation can be done afterwards by running the add-new-channel.yaml playbook.

feat(fabric): Fabric deployment without channel

---

docs/source/guides/networkyaml-substrate.md
platforms/network-schema.json
platforms/shared/configuration/roles/setup/edge-stack/tasks/main.yaml
platforms/substrate/charts/dscp-ipfs-node/Chart.yaml
platforms/substrate/charts/dscp-ipfs-node/requirements.yaml
platforms/substrate/charts/dscp-ipfs-node/templates/secret.yaml
platforms/substrate/charts/dscp-ipfs-node/templates/statefulset.yaml
platforms/substrate/charts/substrate-genesis/Chart.yaml
platforms/substrate/charts/substrate-genesis/templates/generate-keys.yaml
platforms/substrate/charts/substrate-genesis/templates/genesis.yaml
platforms/substrate/charts/substrate-node/Chart.yaml
platforms/substrate/charts/substrate-node/requirements.yaml
platforms/substrate/charts/substrate-node/templates/_helpers.tpl
platforms/substrate/charts/substrate-node/templates/statefulset.yaml
platforms/substrate/configuration/deploy-network.yaml
platforms/substrate/configuration/roles/create/certificates/ambassador/tasks/main.yaml
platforms/substrate/configuration/roles/create/generate_genesis/tasks/main.yaml
platforms/substrate/configuration/roles/create/generate_genesis/tasks/nodes.yaml
platforms/substrate/configuration/roles/create/helm_component/templates/dscp_ipfs_node.tpl
platforms/substrate/configuration/roles/create/helm_component/templates/genesis_job.tpl
platforms/substrate/configuration/roles/create/helm_component/templates/node_substrate.tpl
platforms/substrate/configuration/roles/create/ipfsbootnodefile/tasks/get_bootnode_data.yaml
platforms/substrate/configuration/roles/create/member_node/tasks/ipfs_node.yaml
platforms/substrate/configuration/roles/create/member_node/tasks/main.yaml
platforms/substrate/configuration/roles/create/member_node/tasks/member_node.yaml
platforms/substrate/configuration/roles/create/member_node/templates/ipfsbootnode.tpl
platforms/substrate/configuration/roles/create/secrets/tasks/main.yaml
platforms/substrate/configuration/roles/delete/vault_secrets/tasks/main.yaml
platforms/substrate/configuration/samples/substrate-network-config.yaml

---
**feat(substrate): enable platform deployment via ansible server**
```
This commit introduces support for deploying a decentralized ledger technology (DLT) network using Ansible automation. The changes include:
- Added a new network configuration file to define nodes (Bootnode, Validator, Member, IPFS) within a single organization.
- Updated the `deployment-network.yaml` to support the new network configuration.
- Updated multiple Ansible roles, Helm release templates, and charts to align with the new network configuration.
- Updated the user guide documentation to assist users/developers in correctly configuring the network.
```
**fixes #2547**

[substrate] enable platform deployment via ansible server

---

docs/source/guides/fabric/add-cli.md
docs/source/guides/fabric/add-new-channel.md
docs/source/guides/fabric/add-new-peer.md
platforms/hyperledger-fabric/charts/fabric-channel-join/templates/join_channel.yaml
platforms/hyperledger-fabric/charts/fabric-genesis/README.md
platforms/hyperledger-fabric/charts/fabric-genesis/templates/genesis-job-cleanup.yaml
platforms/hyperledger-fabric/charts/fabric-genesis/templates/job.yaml
platforms/hyperledger-fabric/charts/fabric-genesis/values.yaml
platforms/hyperledger-fabric/configuration/roles/delete/vault_secrets/tasks/main.yaml

- Update fabric-genesis to include new channel creation
- Documentation update

[fabric] Genesis update and add new channel

---

platforms/hyperledger-fabric/charts/fabric-catools/templates/deployment.yaml
platforms/hyperledger-fabric/charts/fabric-catools/values.yaml
platforms/hyperledger-fabric/configuration/manage-user-certificate.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca_tools/peer/tasks/delete_old_certs.yaml
platforms/hyperledger-fabric/configuration/roles/create/ca_tools/peer/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/helm_component/templates/ca-tools.tpl

This PR contains updates in the manage-user-certificate playbook, as well as minor changes in the ca-tools role to consider the refresh-user-certs variable so whenever this playbook is run, only the user certificates will be affected (updated).

feat(fabric): update manage-user-certificate playbook to refresh user certificates

---

platforms/hyperledger-indy/charts/indy-node/templates/statefulset.yaml
platforms/hyperledger-indy/configuration/roles/check/k8_component/tasks/main.yaml
platforms/hyperledger-indy/configuration/roles/create/helm_component/node/templates/node.tpl
platforms/hyperledger-indy/configuration/roles/create/k8_component/templates/serviceaccount.tpl
platforms/hyperledger-indy/configuration/samples/network-indy-newnode-to-baf-network.yaml
platforms/hyperledger-indy/configuration/samples/network-indy-newnode-to-non-baf-network.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3-aries.yaml
platforms/hyperledger-indy/configuration/samples/network-indyv3.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube-aries.yaml
platforms/hyperledger-indy/configuration/samples/network-minikube.yaml
platforms/network-schema.json
platforms/shared/configuration/roles/setup/edge-stack/templates/aes-custom-values.tpl

---
**feat(indy): refactor codebase for effective deployment**
```
This PR enhances our deployment process for the Indy DLT platform by using the Main branch code.
Changes:
- Updated various 'tasks' and the 'Helmrelease' template file.
- Added support for the new Indy version 1.12.6.
```
fixes #quick-fix

[indy] refactor codebase for effective deployment

---

platforms/hyperledger-besu/charts/besu-cacti-connector/Chart.yaml
platforms/hyperledger-besu/charts/besu-genesis/Chart.yaml
platforms/hyperledger-besu/charts/besu-node/Chart.yaml
platforms/hyperledger-besu/charts/besu-propose-validator/Chart.yaml
platforms/hyperledger-besu/charts/besu-tessera-node/Chart.yaml
platforms/hyperledger-besu/charts/besu-tlscert-gen/Chart.yaml
platforms/quorum/charts/quorum-cacti-connector/Chart.yaml
platforms/quorum/charts/quorum-genesis/Chart.yaml
platforms/quorum/charts/quorum-node/Chart.yaml
platforms/quorum/charts/quorum-propose-validator/Chart.yaml
platforms/quorum/charts/quorum-tessera-node/Chart.yaml
platforms/quorum/charts/quorum-tlscert-gen/Chart.yaml

feat(quorum & besu): upgrade charts version to 1.1.0
- Upgrade chart version to 1.1.0 for both Quorum and Besu platforms.

feat(shared): Update quorum and besu charts version to 1.1.0

---

docs/source/guides/fabric/add-new-org.md
platforms/hyperledger-fabric/charts/fabric-channel-join/templates/anchorpeer.yaml
platforms/hyperledger-fabric/charts/fabric-genesis/templates/job.yaml
platforms/hyperledger-fabric/configuration/add-organization.yaml
platforms/hyperledger-fabric/configuration/roles/create/channels_join/tasks/nested_channel_join.yaml
platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/get_peer_msp_config.yaml
platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/genesis/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/fetch/tasks/get_new_org_data.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/fetch/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/fetch/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/fetch/tasks/nested_fetch_role.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/sign_and_update/tasks/nested_sign_and_update.yaml
platforms/hyperledger-fabric/configuration/roles/setup/config_block/sign_and_update/tasks/nested_update_channel.yaml
platforms/hyperledger-fabric/configuration/samples/network-fabric-add-organization.yaml
platforms/shared/configuration/roles/create/job_component/templates/fabric_genesis.tpl
platforms/shared/configuration/roles/create/job_component/templates/join_channel_job.tpl

1 .Updated playbook platforms/hyperledger-fabric/configuration/network-fabric-add-organization.yaml to add organizations that only have peers
fixes #2599

[fabric] Update ansible playbooks add-organization

---

docs/source/guides/besu/add-new-member-org.md
docs/source/guides/besu/add-new-validator-node.md
docs/source/guides/besu/add-new-validator-org.md
docs/source/guides/networkyaml-besu.md
docs/source/guides/networkyaml-fabric.md
docs/source/guides/networkyaml-quorum.md
docs/source/guides/networkyaml-substrate.md

[docs] fix typos

---

platforms/quorum/charts/README.md

---
**docs(quorum): update node names for accuracy**
```
- Updated README to specify the installation of the first 4 nodes (validators) with fixed names (validator-0, validator-1, validator-2, validator-3).
- Any additional nodes can be deployed with user-chosen names.
```
fixes #2612

docs(quorum): update node names for accuracy

---

docs/source/guides/fabric/add-new-orderer-peer.md
platforms/hyperledger-fabric/charts/fabric-cli/templates/deployment.yaml
platforms/hyperledger-fabric/configuration/add-orderer.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/tasks/nested_create_appchannel_block.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/tasks/nested_create_cli.yaml
platforms/hyperledger-fabric/configuration/roles/create/new_orderer/create_appchannel_block/templates/update_channel_script.tpl
platforms/hyperledger-fabric/configuration/roles/create/new_organization/orderer_org/appchannel/tasks/nested_main.yaml
platforms/hyperledger-fabric/configuration/roles/create/orderers/tasks/main.yaml
platforms/hyperledger-fabric/configuration/roles/create/osnchannels/tasks/valuefile.yaml
platforms/hyperledger-fabric/configuration/roles/k8_component/templates/orderer_cli.tpl
platforms/shared/configuration/roles/create/job_component/templates/osn_create_channel_job.tpl
platforms/shared/configuration/roles/create/job_component/vars/main.yaml

This PR includes the following changes:
- Updates on charts to support  ___add orderer node___ operation using helm charts
- Updates on playbooks to support ___add orderer node___ operation using playbooks
- Updates on documentation
- Other minor adjustments on tpl files
As a side note:
The new orderer added is a follower. Possible future improvements: *Make the new orderer as consenter*

feat(fabric): Support of add orderer node operation

---

platforms/hyperledger-fabric/charts/fabric-cli/templates/deployment.yaml

The paths for the tls secrets where wrong, as well as the name of the keys for the json file to retrieve the certificates, that were overwriting others which are needed for the correct functioning of the peer cli.

fix(fabric): Update paths for admin tls secrets when no-vault no-proxy

---

docs/source/concepts/integrate-aws-secrets-manager-with-eks.md
platforms/quorum/charts/README.md
platforms/quorum/charts/quorum-genesis/templates/genesis-job-init.yaml
platforms/quorum/charts/quorum-node/templates/node-hooks-pre-install.yaml
platforms/quorum/charts/quorum-node/templates/node-statefulset.yaml
platforms/quorum/charts/values/noproxy-and-novault/genesis-sec.yaml
platforms/quorum/charts/values/noproxy-and-novault/genesis.yaml
platforms/quorum/charts/values/noproxy-and-novault/txnode-sec.yaml
platforms/quorum/charts/values/noproxy-and-novault/txnode.yaml
platforms/quorum/charts/values/noproxy-and-novault/validator.yaml
platforms/shared/charts/bevel-scripts/scripts/aws-secret-manager-script.py
platforms/shared/charts/bevel-scripts/scripts/package-manager.sh
platforms/shared/charts/bevel-scripts/templates/configmap.yaml
platforms/shared/charts/bevel-vault-mgmt/templates/serviceAccount.yaml

---
**feat(quorum): integrate aws secrets manager**
```
This PR will allow the use of the AWS service called Secrets Manager to store sensitive information, similar to how we use HashiCorp Vault for the same purpose.
- A guide named `integrate-aws-secrets-manager-with-eks.md` has been introduced to help users securely connect their EKS cluster with Secrets Manager using OIDC.
- The Quorum master README has been updated to guide users on how to deploy a network with AWS Secrets Manager.
- A Python script has been added that contains the CRUD operation code for AWS Secrets Manager, injecting the script into the container via ConfigMap.
- The Quorum Genesis and Node charts code have been updated to support Secrets Manager.
````
fixes #2200

[quorum] integrate aws secrets manager

---

platforms/hyperledger-besu/charts/besu-tessera-node/templates/configmap.yaml

Password field to connect to mysql was empty, and it is needed the password for the user that was set on the mysql init container.
Tessera is up and running after the fix.

fix(fabric): Update configmap from tessera node chart
